- stream/src/main/java/org/apache/kafka/streaming/processor/internals/ProcessorNode.java
- stream/src/main/java/org/apache/kafka/streaming/processor/internals/SinkNode.java
> disallow SinkNode.addChild()

- stream/src/main/java/org/apache/kafka/streaming/kstream/internals/KStreamImpl.java
- stream/src/test/java/org/apache/kafka/streaming/kstream/internals/KStreamBranchTest.java
> fix KStreamBranchTest

- clients/src/main/java/org/apache/kafka/common/utils/Utils.java
- stream/src/main/java/org/apache/kafka/streaming/KafkaStreaming.java
- stream/src/main/java/org/apache/kafka/streaming/examples/KStreamJob.java
- stream/src/main/java/org/apache/kafka/streaming/examples/ProcessorJob.java
- stream/src/main/java/org/apache/kafka/streaming/processor/RestoreFunc.java
@ymatsuda 
Also some minor fixes.
> KafkaStreaming refactored: not implement Runnable

- stream/src/main/java/org/apache/kafka/streaming/processor/internals/Stamped.java
- stream/src/test/java/org/apache/kafka/streaming/processor/internals/MinTimestampTrackerTest.java
@ymatsuda Rebased to replace #23
> Fix min timestamp tracker test

- stream/src/main/java/org/apache/kafka/streaming/examples/KStreamJob.java
- stream/src/main/java/org/apache/kafka/streaming/kstream/SlidingWindowDef.java
- stream/src/main/java/org/apache/kafka/streaming/processor/TopologyBuilder.java
- stream/src/main/java/org/apache/kafka/streaming/processor/internals/StreamThread.java
@guozhangwang 
I found that we don't subscribe topics while I was trying to run an example. :(
> get source topic names from builder and subscribe topics

- stream/src/main/java/org/apache/kafka/streaming/KafkaStreaming.java
@guozhangwang 
It is already done by AbstractConfig.
> unnecessary check

- stream/src/main/java/org/apache/kafka/streaming/processor/internals/StreamThread.java
> make the close method work

- stream/src/main/java/org/apache/kafka/streaming/processor/internals/ProcessorTopology.java
- stream/src/main/java/org/apache/kafka/streaming/processor/internals/StreamTask.java
> make sure Processor.close() is called at the end of task

- stream/src/main/java/org/apache/kafka/streaming/examples/KStreamJob.java
- stream/src/main/java/org/apache/kafka/streaming/kstream/KStream.java
- stream/src/main/java/org/apache/kafka/streaming/kstream/KStreamBuilder.java
- stream/src/main/java/org/apache/kafka/streaming/kstream/internals/KStreamImpl.java
- stream/src/main/java/org/apache/kafka/streaming/processor/TopologyBuilder.java
- stream/src/main/java/org/apache/kafka/streaming/processor/internals/PartitionGroup.java
- stream/src/main/java/org/apache/kafka/streaming/processor/internals/RecordQueue.java
- stream/src/main/java/org/apache/kafka/streaming/processor/internals/SinkNode.java
- stream/src/main/java/org/apache/kafka/streaming/processor/internals/SourceNode.java
- stream/src/main/java/org/apache/kafka/streaming/processor/internals/StreamTask.java
- stream/src/main/java/org/apache/kafka/streaming/processor/internals/StreamThread.java
- stream/src/test/java/org/apache/kafka/streaming/processor/internals/StreamTaskTest.java
@guozhangwang 
* enabled default SerDe (from(topic), sendTo(topic), addSource(name, topics...)), addSink(name, topic, parentNames...)
* removed unnecessary SuppressWarnings
* pushed down addRecords to RecordQueue
> enable default SerDe, optimize record inserts

- stream/src/main/java/org/apache/kafka/streaming/processor/internals/ProcessorTopology.java
- stream/src/main/java/org/apache/kafka/streaming/processor/internals/StreamThread.java
> logging exceptions

- stream/src/main/java/org/apache/kafka/streaming/processor/TopologyBuilder.java
Our style checker doesn't seem to understand javadoc and complains unused imports.
> fix unused imports

- streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java
@guozhangwang 
* remove the node stack fro StreamTask.
* make sure reset currNode and currRecord at the end of StreamTask.process using try ~ finally
> remove nodestack

- streams/src/test/java/org/apache/kafka/test/KStreamTestDriver.java
- streams/src/test/java/org/apache/kafka/test/MockProcessorContext.java
> Remove nodestack from test code

- streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java
@guozhangwang 
* flush records before offset commit
* clear the commitRequested flag after commit
> flush records before offset commit

- streams/src/main/java/org/apache/kafka/streams/processor/internals/ProcessorTopology.java
- streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java
- streams/src/test/java/org/apache/kafka/test/KStreamTestDriver.java
- streams/src/test/java/org/apache/kafka/test/MockProcessorContext.java
@guozhangwang 
* make ProcessorTopolgy immutable
* let StreamTask do init and close of processor nodes and set currNode correctly
> make ProcessorTopology immutable

- streams/src/main/java/org/apache/kafka/streams/examples/ProcessorJob.java
- streams/src/main/java/org/apache/kafka/streams/processor/ProcessorContext.java
- streams/src/main/java/org/apache/kafka/streams/processor/internals/ProcessorContextImpl.java
- streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java
- streams/src/test/java/org/apache/kafka/test/MockProcessorContext.java
> remove processor arg from schedule call

- streams/src/main/java/org/apache/kafka/streams/processor/internals/ProcessorStateManager.java
@guozhangwang 
We won't have an ack'ed offset if a state store hasn't write any changelog. We should use the offset in restoredOffsets in such a case, otherwise we will lose the local state after restart.
> use restoredOffset if ack'ed offset is not available

- streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java
> call statemgr.close()

- streams/src/test/java/org/apache/kafka/streams/processor/internals/PartitionGroupTest.java
- streams/src/test/java/org/apache/kafka/streams/processor/internals/RecordQueueTest.java
- streams/src/test/java/org/apache/kafka/streams/processor/internals/StreamTaskTest.java
- streams/src/test/java/org/apache/kafka/test/MockTimestampExtractor.java
@ymatsuda 
Also change the behavior of MockTimestampExtractor to use the offset as the timestamp.
> Add unit tests for PartitionGroup and RecordQueue

- streams/src/main/java/org/apache/kafka/streams/processor/internals/PartitionGroup.java
- streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java
- streams/src/test/java/org/apache/kafka/streams/processor/internals/PartitionGroupTest.java
> merge nextQueue and getRecord into nextRecord

- streams/src/main/java/org/apache/kafka/streams/processor/internals/ProcessorStateManager.java
- streams/src/test/java/org/apache/kafka/streams/processor/internals/ProcessorStateManagerTest.java
* added ProcessorStateManagerTest
* bug fix: correctly unassign a changelog partition (instead of unsubscribing)
@guozhangwang
> add ProcessorStateManagerTest

- streams/src/main/java/org/apache/kafka/streams/kstream/SlidingWindowDef.java
- streams/src/main/java/org/apache/kafka/streams/processor/internals/PartitionGroup.java
- streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java
> Address some comments

- streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamThread.java
- streams/src/test/java/org/apache/kafka/streams/processor/internals/StreamThreadTest.java
@guozhangwang 
a test for assignment changes only.
> add StreamThreadTest

- streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamThread.java
- streams/src/test/java/org/apache/kafka/streams/processor/internals/StreamThreadTest.java
@guozhangwang 
* Added a test for state directory clean up
* Fixed a bug in state directory clean up. The bug is in time interval calculation.
> add a test for statedir cleanup and fix a bug

- streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamThread.java
- streams/src/test/java/org/apache/kafka/streams/processor/internals/StreamThreadTest.java
* added testMaybeCommit
@guozhangwang
> Test periodical commit

- streams/src/main/java/org/apache/kafka/streams/processor/internals/ProcessorContextImpl.java
- streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java
> set the initialized flag in context

- streams/src/main/java/org/apache/kafka/streams/examples/ProcessorJob.java
Maybe need to emphasize with a try/finally.
> Docs say that iterators must be closed.

- build.gradle
> build.gradle: add installAll and install_{2_10_5, 2_11_7} gradle tasks

- build.gradle
Streams was missing from the packages. Note, it's already fixed in trunk.
> HOTFIX: Added streams to pkgs

- bin/kafka-run-class.sh
- streams/examples/main/java/org/apache/kafka/streams/examples/pageview/PageViewTypedJob.java
- streams/examples/main/java/org/apache/kafka/streams/examples/pageview/PageViewUnTypedJob.java
- streams/examples/main/java/org/apache/kafka/streams/examples/pipe/PipeJob.java
- streams/examples/main/java/org/apache/kafka/streams/examples/wordcount/WordCountJob.java
- streams/examples/main/java/org/apache/kafka/streams/examples/wordcount/WordCountProcessorJob.java
> MINOR: Remove some unused imports, and duplicate RocksDB dependency jar

- bin/kafka-run-class.sh
> Fix a system test issue

- clients/src/main/java/org/apache/kafka/common/Cluster.java
- streams/src/main/java/org/apache/kafka/streams/KafkaStreams.java
- streams/src/main/java/org/apache/kafka/streams/StreamsConfig.java
- streams/src/main/java/org/apache/kafka/streams/StreamsMetrics.java
- streams/src/main/java/org/apache/kafka/streams/kstream/KStream.java
- streams/src/main/java/org/apache/kafka/streams/kstream/KTable.java
- streams/src/main/java/org/apache/kafka/streams/kstream/Transformer.java
- streams/src/main/java/org/apache/kafka/streams/kstream/TransformerSupplier.java
- streams/src/main/java/org/apache/kafka/streams/kstream/UnlimitedWindows.java
- streams/src/main/java/org/apache/kafka/streams/kstream/ValueTransformer.java
- streams/src/main/java/org/apache/kafka/streams/kstream/ValueTransformerSupplier.java
- streams/src/main/java/org/apache/kafka/streams/kstream/Windowed.java
- streams/src/main/java/org/apache/kafka/streams/processor/DefaultPartitionGrouper.java
- streams/src/main/java/org/apache/kafka/streams/processor/PartitionGrouper.java
- streams/src/main/java/org/apache/kafka/streams/processor/ProcessorSupplier.java
- streams/src/main/java/org/apache/kafka/streams/processor/TimestampExtractor.java
- streams/src/main/java/org/apache/kafka/streams/processor/TopologyBuilder.java
- streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamPartitionAssignor.java
- streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamThread.java
- streams/src/main/java/org/apache/kafka/streams/state/KeyValueIterator.java
- streams/src/main/java/org/apache/kafka/streams/state/KeyValueStore.java
- streams/src/main/java/org/apache/kafka/streams/state/Serdes.java
- streams/src/main/java/org/apache/kafka/streams/state/Stores.java
- streams/src/main/java/org/apache/kafka/streams/state/WindowStoreIterator.java
- streams/src/main/java/org/apache/kafka/streams/state/WindowStoreUtils.java
- streams/src/test/java/org/apache/kafka/streams/processor/TopologyBuilderTest.java
@miguno @ijuma @ymatsuda @enothereska @fpj @granders The following commits are back-ported:
2a58ba9fd893979f89aec251579b10f5cda41d10
f676cfeb83195f032e3ad8908288a7e04011c830
This marks the code-freeze for this branch (finger crossed).
> Backport recent changes from trunk/streams: batch #3

- streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamPartitionAssignor.java
Author: Michael G. Noll <michael@confluent.io>
Reviewers: Ewen Cheslack-Postava <ewen@confluent.io>
Closes #1001 from miguno/KAFKA-3324
@guozhangwang @enothereska @granders :  Critical (but small) bug fix for Kafka Streams.
> KAFKA-3324; NullPointerException in StreamPartitionAssignor

- streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamPartitionAssignor.java
Author: Guozhang Wang <wangguoz@gmail.com>
Reviewers: Michael G. Noll <michael@confluent.io>
Closes #1004 from guozhangwang/KStreamPANPE
> HOTFIX: Avoid NPE in StreamsPartitionAssignor

- streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamPartitionAssignor.java
@ymatsuda @miguno for reviews. We need to re-package it unfortunately..
> HOTFIX: remove job id prefix from internal topic.

- streams/src/main/java/org/apache/kafka/streams/state/internals/CachingWindowStore.java
> failing to close this iterator causes leaks in rocksdb

- core/src/main/scala/kafka/coordinator/GroupMetadataManager.scala
- core/src/main/scala/kafka/log/Log.scala
- core/src/main/scala/kafka/log/LogValidator.scala
- core/src/main/scala/kafka/tools/DumpLogSegments.scala
- core/src/test/scala/unit/kafka/log/LogCleanerTest.scala
- core/src/test/scala/unit/kafka/log/LogSegmentTest.scala
- core/src/test/scala/unit/kafka/log/LogTest.scala
- core/src/test/scala/unit/kafka/message/BaseMessageSetTestCases.scala
The Java->Scala conversion broke, so the server side objects needed a bit of massaging
> Fix build failures due to Jason's cleanup. 

- clients/src/main/java/org/apache/kafka/common/protocol/Protocol.java
- clients/src/main/java/org/apache/kafka/common/requests/InitPidRequest.java
- clients/src/test/java/org/apache/kafka/common/requests/RequestResponseTest.java
- core/src/main/scala/kafka/coordinator/GroupMetadata.scala
- core/src/main/scala/kafka/coordinator/GroupMetadataManager.scala
- core/src/main/scala/kafka/coordinator/PidManager.scala
- core/src/main/scala/kafka/coordinator/PidMetadata.scala
- core/src/main/scala/kafka/coordinator/TransactionCoordinator.scala
- core/src/main/scala/kafka/coordinator/TransactionLogManager.scala
- core/src/main/scala/kafka/coordinator/TransactionMetadata.scala
- core/src/main/scala/kafka/server/KafkaApis.scala
- core/src/test/scala/unit/kafka/coordinator/PidManagerTest.scala
- core/src/test/scala/unit/kafka/coordinator/TransactionCoordinatorTest.scala
- core/src/test/scala/unit/kafka/coordinator/TransactionLogManagerTest.scala
1. Added message formats for transactionalid -> pid mapping, and pid -> transaction-state mapping.
2. Added transaction timeout to InitPidRequest.
> Transaction log message format

- Jenkinsfile
Branch builder should show up at https://jenkins.confluent.io/job/confluentinc/job/kafka
Jenkinsfile is copied from ce-kafka. There doesn't appear to be a better way to test other than checking this in, unfortunately.
> MINOR: Add Jenkinsfile for CK branch builder

- tests/kafkatest/tests/core/log_dir_failure_test.py
> CONFLUENT: Disable confluent support metrics in log_dir_failure_test.py

- support-metrics-client/src/main/java/io/confluent/support/metrics/MetricsReporter.java
- support-metrics-common/src/main/java/io/confluent/support/metrics/BaseMetricsReporter.java
Remove compile-time ZK dependency in BaseMetricsReporter so that components extending this without ZK configs dont have dependency on core jar.
> CPKAFKA-3136: Avoid static core dependency on BaseMetricsReporter

- bin/support-metrics-bundle
> MINOR: Add missing support-metrics-bundle script

- Jenkinsfile
> CONFLUENT: Build cp-downstream-builds as part of Jenkins PR Job

- build.gradle
Skip signing for 5.4.x-beta
* as this is not a rc candidate.
> Skip signing

- gradle.properties
- streams/quickstart/java/src/main/resources/archetype-resources/pom.xml
- tests/kafkatest/__init__.py
- tests/kafkatest/version.py
> Bump version to 5.3.2-ccs-SNAPSHOT

- Jenkinsfile
Adjusts the Jenkinsfile to capture tests as part of the same stage as the test run.
> jenkins: capture test results on downstream build failure

- build.gradle
- gradle/dependencies.gradle
- Verified that the resulting tarball no longer contained incorrect jackson-databind versions
- Also upgrade to avro 1.9.1 which has some desired bugfixes
> Override the jackson-databind that gets pulled in by avro.

- bin/kafka-run-class.sh
This reverts commit bc070fa9d61ae5e9730fc5f56ba012979bf98ed1.
> Revert "CONFLUENT: kafka-run-class: set default log dir to /var/log/kafka"

- gradle.properties
- streams/quickstart/java/src/main/resources/archetype-resources/pom.xml
- tests/kafkatest/__init__.py
- tests/kafkatest/version.py
> MINOR: Bump version to 5.3.3-ccs-SNAPSHOT

- Jenkinsfile
> CONFLUENT: Update muckrake version map to include 2.4 and 2.5

- gradle/dependencies.gradle
> Update to jackson databind 2.9.10.2

- Jenkinsfile
The Jenkinsfile is a copy of one in master. Adding it to the branch to
create Jenkins job for this branch
> CONFLUENT: Add Jenkinsfile to 2.2 branch

- gradle/dependencies.gradle
Jackson patch version upgrade. ./gradlew clean install passes locally.
> Update to jackson databind 2.9.10.3

- Jenkinsfile
This is the same behavior we configured for PR builds in Apache Kafka.
> CONFLUENT: Enable retries for PR builds

- docs/js/templateData.js
- gradle.properties
- kafka-merge-pr.py
- streams/quickstart/java/pom.xml
- streams/quickstart/java/src/main/resources/archetype-resources/pom.xml
- streams/quickstart/pom.xml
- tests/kafkatest/__init__.py
- tests/kafkatest/version.py
> CONFLUENT: Bump up version to 5.4.2

- Jenkinsfile
Without a license RAT complains. Now `gradlew rat` passes.
> CONFLUENT: Add license to Jenkinsfile

- Makefile
> MINOR: Add Makefile for std layout patch changes

- .gitignore
- docs/ops.html
- streams/src/main/java/org/apache/kafka/streams/kstream/internals/KTableImpl.java
- streams/src/main/java/org/apache/kafka/streams/kstream/internals/foreignkeyjoin/CombinedKeySchema.java
- streams/src/main/java/org/apache/kafka/streams/kstream/internals/foreignkeyjoin/ForeignJoinSubscriptionSendProcessorSupplier.java
- streams/src/main/java/org/apache/kafka/streams/kstream/internals/foreignkeyjoin/SubscriptionResolverJoinProcessorSupplier.java
- streams/src/main/java/org/apache/kafka/streams/kstream/internals/foreignkeyjoin/SubscriptionWrapperSerde.java
- streams/src/main/java/org/apache/kafka/streams/processor/internals/InternalTopologyBuilder.java
- streams/src/test/java/org/apache/kafka/streams/integration/KTableKTableForeignKeyJoinDefaultSerdeTest.java
- streams/src/test/java/org/apache/kafka/streams/kstream/internals/foreignkeyjoin/CombinedKeySchemaTest.java
- streams/src/test/java/org/apache/kafka/streams/kstream/internals/foreignkeyjoin/SubscriptionResolverJoinProcessorSupplierTest.java
- streams/src/test/java/org/apache/kafka/streams/kstream/internals/foreignkeyjoin/SubscriptionWrapperSerdeTest.java
- streams/src/test/java/org/apache/kafka/streams/utils/UniqueTopicSerdeScope.java
minor conflict in .gitignore. Kept both
> Sync from upstream ak -> ccs (additional fixes) 29 apr 2020

- clients/src/main/resources/common/message/FetchQuorumRecordsRequest.json
- clients/src/test/java/org/apache/kafka/clients/MockClient.java
- core/src/main/scala/kafka/raft/KafkaNetworkChannel.scala
- core/src/test/scala/unit/kafka/raft/KafkaNetworkChannelTest.scala
- raft/src/main/java/org/apache/kafka/raft/RaftResponse.java
I found a few bugs in the `KafkaNetworkChannel` implementation in #301. This patch fixes those bugs and adds missing test cases.
> Fix bugs in KafkaNetworkChannel and add test cases

- raft/src/test/java/org/apache/kafka/raft/RaftEventSimulationTest.java
> KCORE MINOR: Correct Quorum size in simulation tests

- clients/src/main/java/org/apache/kafka/common/config/ConfigDef.java
- raft/src/main/java/org/apache/kafka/raft/KafkaRaftClient.java
- raft/src/main/java/org/apache/kafka/raft/RaftConfig.java
- raft/src/test/java/org/apache/kafka/raft/KafkaRaftClientTest.java
- raft/src/test/java/org/apache/kafka/raft/MockNetworkChannel.java
- raft/src/test/java/org/apache/kafka/raft/NoOpStateMachine.java
- raft/src/test/java/org/apache/kafka/raft/RaftConfigTest.java
Amend some test gaps in `KafkaRaftClient` and a starting point for `RaftConfig` test.
> KCORE-361: Add raft test coverage

- raft/src/test/java/org/apache/kafka/raft/MockLog.java
- raft/src/test/java/org/apache/kafka/raft/MockLogTest.java
This patch includes a few small fixes in `MockLog`. In particular, it makes the range checking consistent with the standard `Log` implementation. It also adds some additional testing and fixes some of the start offset return logic in `read`.
> MINOR: Improve range checking in MockLog

- clients/src/main/java/org/apache/kafka/common/utils/Utils.java
- clients/src/test/java/org/apache/kafka/common/utils/UtilsTest.java
- streams/src/main/java/org/apache/kafka/streams/errors/TaskMigratedException.java
- streams/src/main/java/org/apache/kafka/streams/kstream/internals/FullChangeSerde.java
- streams/src/main/java/org/apache/kafka/streams/processor/internals/AbstractTask.java
- streams/src/main/java/org/apache/kafka/streams/processor/internals/ActiveTaskCreator.java
- streams/src/main/java/org/apache/kafka/streams/processor/internals/ProcessorRecordContext.java
- streams/src/main/java/org/apache/kafka/streams/processor/internals/RecordCollector.java
- streams/src/main/java/org/apache/kafka/streams/processor/internals/RecordCollectorImpl.java
- streams/src/main/java/org/apache/kafka/streams/processor/internals/StandbyTask.java
- streams/src/main/java/org/apache/kafka/streams/processor/internals/StandbyTaskCreator.java
- streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java
- streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamThread.java
- streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamsMetadataState.java
- streams/src/main/java/org/apache/kafka/streams/processor/internals/Task.java
- streams/src/main/java/org/apache/kafka/streams/processor/internals/TaskManager.java
- streams/src/main/java/org/apache/kafka/streams/state/internals/BufferValue.java
- streams/src/main/java/org/apache/kafka/streams/state/internals/ContextualRecord.java
- streams/src/main/java/org/apache/kafka/streams/state/internals/InMemoryTimeOrderedKeyValueBuffer.java
- streams/src/main/java/org/apache/kafka/streams/state/internals/TimeOrderedKeyValueBufferChangelogDeserializationHelper.java
- streams/src/test/java/org/apache/kafka/streams/integration/RestoreIntegrationTest.java
- streams/src/test/java/org/apache/kafka/streams/kstream/internals/FullChangeSerdeTest.java
- streams/src/test/java/org/apache/kafka/streams/processor/internals/RecordCollectorTest.java
- streams/src/test/java/org/apache/kafka/streams/processor/internals/StandbyTaskTest.java
- streams/src/test/java/org/apache/kafka/streams/processor/internals/StreamTaskTest.java
- streams/src/test/java/org/apache/kafka/streams/processor/internals/TaskManagerTest.java
- streams/src/test/java/org/apache/kafka/streams/state/internals/TimeOrderedKeyValueBufferTest.java
- streams/src/test/java/org/apache/kafka/test/MockRecordCollector.java
- streams/test-utils/src/main/java/org/apache/kafka/streams/TopologyTestDriver.java
- tests/kafkatest/services/kafka/kafka.py
> Sync AK 2.6 -> CCS 2.6 28-June-2020 

- checkstyle/import-control.xml
- clients/src/main/java/org/apache/kafka/common/protocol/ApiKeys.java
- clients/src/main/java/org/apache/kafka/common/requests/AbstractResponse.java
- clients/src/main/java/org/apache/kafka/common/requests/DescribeQuorumRequest.java
- clients/src/main/java/org/apache/kafka/common/requests/DescribeQuorumResponse.java
- clients/src/main/resources/common/message/DescribeQuorumRequest.json
- clients/src/main/resources/common/message/DescribeQuorumResponse.json
- core/src/main/scala/kafka/raft/KafkaMetadataLog.scala
- core/src/main/scala/kafka/server/KafkaApis.scala
- core/src/main/scala/kafka/server/RaftServer.scala
- raft/src/main/java/org/apache/kafka/raft/KafkaRaftClient.java
- raft/src/main/java/org/apache/kafka/raft/LeaderState.java
- raft/src/main/java/org/apache/kafka/raft/ReplicatedLog.java
- raft/src/test/java/org/apache/kafka/raft/KafkaRaftClientTest.java
- raft/src/test/java/org/apache/kafka/raft/LeaderStateTest.java
- raft/src/test/java/org/apache/kafka/raft/MockLog.java
- raft/src/test/java/org/apache/kafka/raft/MockLogTest.java
- raft/src/test/java/org/apache/kafka/raft/RaftEventSimulationTest.java
- raft/src/test/java/org/apache/kafka/raft/SimpleKeyValueStoreTest.java
- raft/src/test/java/org/apache/kafka/raft/internals/KafkaRaftMetricsTest.java
Add the DescribeQuorum API as stated in KIP-595.
> KC-298: Add DescribeQuorum API

- Jenkinsfile
After I merge this to the master branch I will cherry-pick this back to the older branches starting with 1.0 up to 2.6
> ST-3402: Refactored Jenkinsfile to get secrets from Vault instead of Jenkins credential store

- gradle/dependencies.gradle
v2.9.10.5 fixes 16 critical/high CVEs present in v2.9.10.3
> MINOR: Upgrade jackson-databind version

- gradle.properties
- streams/quickstart/java/src/main/resources/archetype-resources/pom.xml
- tests/kafkatest/__init__.py
- tests/kafkatest/version.py
CP 5.3.4 is out, time to bump this version to 5.3.5
> MINOR: Bump AK CSS version to 5.3.5

- clients/src/main/java/org/apache/kafka/clients/consumer/internals/AbstractCoordinator.java
- clients/src/test/java/org/apache/kafka/clients/consumer/KafkaConsumerTest.java
Cherry-pick https://github.com/apache/kafka/commit/3bc2df7651d8b9029d2478a3f39b3b223c0532b7 to ksql release
> Cherry-pick 10134 to ksql 0.13

- config/kip500-single-node.properties
- config/server-kip500.properties
- core/src/main/scala/kafka/server/KafkaConfig.scala
Adding:
* registration.heartbeat.interval.ms
* registration.lease.timeout.ms
* metadata.log.dir
Also adding server-kip500.properties with some default values
> Adding more configs from KIP-631

- build.gradle
- metadata/src/test/java/org/apache/kafka/controller/ConfigurationControlManagerTest.java
- metadata/src/test/java/org/apache/kafka/controller/ControllerPurgatoryTest.java
- metadata/src/test/java/org/apache/kafka/controller/LocalLogManagerTest.java
- metadata/src/test/java/org/apache/kafka/controller/QuorumControllerTest.java
- metadata/src/test/java/org/apache/kafka/metadata/BrokerStateTest.java
- metadata/src/test/java/org/apache/kafka/metadata/MetadataParserTest.java
- metadata/src/test/java/org/apache/kafka/timeline/BaseHashTableTest.java
- metadata/src/test/java/org/apache/kafka/timeline/SnapshotRegistryTest.java
- metadata/src/test/java/org/apache/kafka/timeline/SnapshottableHashTableTest.java
- metadata/src/test/java/org/apache/kafka/timeline/TimelineHashMapTest.java
- metadata/src/test/java/org/apache/kafka/timeline/TimelineHashSetTest.java
> Migrate metadata module to JUnit 5

- gradle.properties
- streams/quickstart/java/src/main/resources/archetype-resources/pom.xml
- streams/quickstart/pom.xml
- tests/kafkatest/__init__.py
- tests/kafkatest/version.py
5.4.3 is out the door - Time for the CP-5.4 version bump to the next.
> MINOR: Bump CCS 2.4 to version 5.4.4-ccs-SNAPSHOT

- .gitignore
- core/src/test/scala/unit/kafka/coordinator/group/GroupMetadataManagerTest.scala
> Manual AK to CCS 2.3 Merge

- .gitignore
- core/src/main/scala/kafka/coordinator/group/GroupCoordinator.scala
- core/src/test/scala/unit/kafka/coordinator/group/GroupCoordinatorTest.scala
Manual merge for 2.5, bringing in other changes, so PR-ing them here.
> Manual AK to CCS 2.5 Merge

- core/src/main/scala/kafka/tools/StorageTool.scala
Restore compatibility w/ Scala 2.12
> Restore compatibility w/ Scala 2.12

- core/src/main/scala/kafka/server/KafkaConfig.scala
- core/src/test/scala/unit/kafka/server/KafkaConfigTest.scala
KC-1107: Ensure controller.listeners are not in advertised.listeners
> KC-1107: Ensure controller.listeners are not in advertised.listeners

- core/src/main/scala/kafka/server/BrokerLifecycleManager.scala
Eliminates these errors:
```
[Error] confluentinc/kafka/core/src/main/scala/kafka/server/BrokerLifecycleManager.scala:59: type BrokerState is not a member of package kafka.server.metadata
[Error] confluentinc/kafka/core/src/main/scala/kafka/server/BrokerLifecycleManager.scala:62: type BrokerState is not a member of package kafka.server.metadata
[Error] confluentinc/kafka/core/src/main/scala/kafka/server/BrokerLifecycleManager.scala:90: type BrokerState is not a member of package kafka.server.metadata
[Error] confluentinc/kafka/core/src/main/scala/kafka/server/BrokerLifecycleManager.scala:90: type BrokerState is not a member of package kafka.server.metadata
[Error] confluentinc/kafka/core/src/main/scala/kafka/server/BrokerLifecycleManager.scala:96: type BrokerState is not a member of …
```
> Fix Scala 2.12 compile errors

- core/src/main/scala/kafka/server/KafkaBroker.scala
Test cases in `kafka.metrics.MetricsTest` were failing because of the name change from `KafkaServer` to `KafkaBroker`. This patch introduces an alternate registration path for these metrics.
> MINOR: Fix failing metrics tests due to `KafkaServer` rename

- core/src/main/scala/kafka/log/LogManager.scala
- core/src/main/scala/kafka/server/ConfigHandler.scala
- core/src/main/scala/kafka/server/LegacyBroker.scala
- core/src/main/scala/kafka/server/metadata/BrokerMetadataListener.scala
- core/src/main/scala/kafka/server/metadata/PartitionMetadataProcessor.scala
- core/src/test/scala/unit/kafka/server/metadata/PartitionMetadataProcessorTest.scala
> Process ConfigRecord

- clients/src/main/java/org/apache/kafka/common/errors/InvalidClusterIdException.java
> Add missing InvalidClusterIdException class

- core/src/main/scala/kafka/server/LegacyBroker.scala
> Fix post-merge compilation error w/ Scala 2.12

- core/src/main/scala/kafka/server/BrokerToControllerChannelManager.scala
Problem introduced by https://github.com/confluentinc/kafka/commit/a60fce7b0df1b887feba35abfe84cde37d0fa185
> fix issue in BrokerToControllerChannelManager

- config/kip500-broker-node.properties
- config/kip500-controller-node.properties
- core/src/main/scala/kafka/server/BrokerToControllerChannelManager.scala
- core/src/main/scala/kafka/server/Kip500Broker.scala
> Fix Broker Controller discovery w/ LocalLogManager

- core/src/main/scala/kafka/server/BrokerToControllerChannelManager.scala
Fix compilation w/ Scala 2.12 after the recent merge
> Fix compilation w/ Scala 2.12 after the recent merge

- core/src/main/scala/kafka/server/BrokerLifecycleManager.scala
- core/src/main/scala/kafka/server/BrokerToControllerChannelManager.scala
- core/src/main/scala/kafka/server/KafkaConfig.scala
- core/src/main/scala/kafka/server/KafkaServer.scala
- core/src/main/scala/kafka/server/Kip500Broker.scala
- core/src/main/scala/kafka/server/Kip500Controller.scala
- core/src/test/java/kafka/testkit/KafkaClusterTestKit.java
- core/src/test/scala/unit/kafka/server/KafkaConfigTest.scala
> KC-1312: Reconcile KIP-631 configurations with the KIP

- core/src/main/scala/kafka/server/metadata/BrokerMetadataListener.scala
- core/src/main/scala/kafka/server/metadata/PartitionMetadataProcessor.scala
- core/src/test/scala/unit/kafka/server/metadata/BrokerMetadataListenerTest.scala
- core/src/test/scala/unit/kafka/server/metadata/PartitionMetadataProcessorTest.scala
> Remove out-of-band Broker registration event processor

- core/src/main/scala/kafka/server/ControllerApis.scala
Implements `ControllerApis.handleIncrementalAlterConfigs()` to invoke already-existing code in `QuorumController`.  System tests in `message_format_change_test.py` now get past the previous issue when this change is present; they still don't succeed, but it is now a different issue.
> ControllerApis.handleIncrementalAlterConfigs()

- core/src/main/scala/kafka/server/KafkaBroker.scala
- core/src/main/scala/kafka/server/KafkaRaftServer.scala
- core/src/main/scala/kafka/server/Kip500Broker.scala
- core/src/main/scala/kafka/server/Server.scala
Server won't start.  This PR fixes it.
> Fix startup

- shell/src/main/java/org/apache/kafka/shell/MetadataShell.java
Fix compile error in MetadataShell
> Fix compile error in MetadataShell

- core/src/main/scala/kafka/server/BrokerServer.scala
- core/src/main/scala/kafka/server/ControllerServer.scala
- core/src/main/scala/kafka/server/KafkaRaftServer.scala
- core/src/test/java/kafka/testkit/KafkaClusterTestKit.java
- core/src/test/scala/integration/kafka/server/ControllerServerTest.scala
Fix a couple more naming divergences with upstream:
Kip500Broker -> BrokerServer
Kip500Controller -> ControllerServer
> Converge Kip500Broker and Kip500Controller names with upstream

- connect/runtime/src/main/java/org/apache/kafka/connect/runtime/distributed/DistributedHerder.java
- connect/runtime/src/test/java/org/apache/kafka/connect/runtime/distributed/DistributedHerderTest.java
> KAFKA-10763: Fix incomplete cooperative rebalances preventing connector/task revocations (apache#9765)

- connect/runtime/src/main/java/org/apache/kafka/connect/runtime/Worker.java
- connect/runtime/src/main/java/org/apache/kafka/connect/runtime/WorkerSourceTask.java
- connect/runtime/src/main/java/org/apache/kafka/connect/runtime/WorkerTask.java
- connect/runtime/src/test/java/org/apache/kafka/connect/integration/ConnectWorkerIntegrationTest.java
- connect/runtime/src/test/java/org/apache/kafka/connect/integration/ConnectorHandle.java
- connect/runtime/src/test/java/org/apache/kafka/connect/integration/MonitorableSourceConnector.java
- connect/runtime/src/test/java/org/apache/kafka/connect/runtime/ErrorHandlingTaskTest.java
- connect/runtime/src/test/java/org/apache/kafka/connect/runtime/WorkerSourceTaskTest.java
- connect/runtime/src/test/java/org/apache/kafka/connect/runtime/WorkerTest.java
Cherry picking https://github.com/apache/kafka/pull/10016 to 2.5
> KAFKA-10340: Proactively close producer when cancelling source tasks (apache#10016)

- gradle/dependencies.gradle
This has already been done for 2.4 https://github.com/confluentinc/kafka/pull/518/files
> kc-1457: Upgrade HttpClient for CVE-2020-13956

- gradle/dependencies.gradle
> fix: CVE-2021-28168

- gradle/dependencies.gradle
https://github.com/confluentinc/kafka/pull/552
> fix: CVE-2021-28168 Upgrade jersey to 2.34

- gradle/dependencies.gradle
As per slack discussion, we are going with avro update in 5.2 and 5.3  branches.
> KC-1729: Update avro version to "1.9.2"

- clients/src/main/java/org/apache/kafka/clients/admin/ConfigEntry.java
- clients/src/main/java/org/apache/kafka/common/config/ConfigDef.java
- clients/src/main/java/org/apache/kafka/common/utils/ConfigUtils.java
- clients/src/test/java/org/apache/kafka/common/utils/ConfigUtilsTest.java
- core/src/main/scala/kafka/server/DynamicBrokerConfig.scala
- core/src/main/scala/kafka/server/ZkAdminManager.scala
This is a backport of
KC-1752
1. https://github.com/confluentinc/ce-kafka/commit/05f28fc3b1e46f1a6b990918381d265387738f4c
2. https://github.com/confluentinc/ce-kafka/commit/cc570c6f4d7515019a95261e9bbd00915dbc5e34
KC-1625
1. https://github.com/confluentinc/ce-kafka/commit/da01e73a93ba5534e227c673482cb8a2f681a42f
2. https://github.com/confluentinc/ce-kafka/commit/ee159ace5fa5f9bc923a4db435afd99f96523ffd
> Backport secret logging leakage fixes to 2.8

- clients/src/main/java/org/apache/kafka/clients/admin/ConfigEntry.java
- clients/src/main/java/org/apache/kafka/common/config/ConfigDef.java
- clients/src/main/java/org/apache/kafka/common/utils/ConfigUtils.java
- clients/src/test/java/org/apache/kafka/common/utils/ConfigUtilsTest.java
- core/src/main/scala/kafka/log/LogConfig.scala
- core/src/main/scala/kafka/log/LogManager.scala
- core/src/main/scala/kafka/network/RequestChannel.scala
- core/src/main/scala/kafka/server/AdminManager.scala
- core/src/main/scala/kafka/server/DynamicBrokerConfig.scala
- core/src/main/scala/kafka/server/KafkaConfig.scala
- core/src/test/scala/unit/kafka/log/LogConfigTest.scala
- gradle/spotbugs-exclude.xml
This change includes:
https://confluentinc.atlassian.net/browse/KC-1752
https://confluentinc.atlassian.net/browse/KC-1625
https://confluentinc.atlassian.net/browse/KSTORAGE-1626
Backport of as well: https://github.com/confluentinc/kafka/pull/584/commits/52ca61075e82817a544ac3ae34734152a019a0d3
> Fix a series of secret logging leakage issues

- connect/runtime/src/main/java/org/apache/kafka/connect/runtime/rest/InternalRequestSignature.java
- connect/runtime/src/main/java/org/apache/kafka/connect/runtime/rest/resources/ConnectorPluginsResource.java
- connect/runtime/src/test/java/org/apache/kafka/connect/runtime/distributed/DistributedHerderTest.java
Sync stuck on conflict in `connect/runtime/src/test/java/org/apache/kafka/connect/runtime/distributed/DistributedHerderTest.java` -Resolved by taking AK's changes.
> AK/2.7 sync to CCS/2.7

- gradle/dependencies.gradle
Fixes merge conflict in dependencies.gradle
> chore:fix merge conflict in dependencies.gradle

- build.gradle
> [CVE-2019-10782] Upgrade com.puppycrawl.tools:checkstyle to version 8.29

- gradle/dependencies.gradle
Upgrading bcpkix to also upgrade bcprov-jdk15on
Release notes: https://www.bouncycastle.org/releasenotes.html
> [CVE-2020-28052] Upgrade bcprov-jdk15on

- build.gradle
release notes: https://commons.apache.org/proper/commons-codec/changes-report.html#a1.15
> MINOR: force commons-codec version

- gradle/dependencies.gradle
Aligns the CP netty version to 4.1.65.Final.
> DGS-2161: Update netty version to 4.1.65.Final

- gradle/dependencies.gradle
Changelog: https://github.com/netty/netty/issues?q=is%3Aclosed+milestone%3A4.1.73.Final
Reviewers: Manikumar Reddy <manikumar.reddy@gmail.com>
> MINOR: Upgrade netty to 4.1.73.Final (2.7)

- gradle/dependencies.gradle
Changelog: https://github.com/netty/netty/issues?q=is%3Aclosed+milestone%3A4.1.73.Final
Reviewers: Manikumar Reddy <manikumar.reddy@gmail.com>
> MINOR: Upgrade netty to 4.1.73.Final (2.6)

- gradle/dependencies.gradle
Changelog: https://github.com/netty/netty/issues?q=is%3Aclosed+milestone%3A4.1.73.Final
Reviewers: Manikumar Reddy <manikumar.reddy@gmail.com>
> MINOR: Upgrade netty to 4.1.73.Final (2.5)

- gradle/dependencies.gradle
Changelog: https://github.com/netty/netty/issues?q=is%3Aclosed+milestone%3A4.1.73.Final
Reviewers: Manikumar Reddy <manikumar.reddy@gmail.com>
> MINOR: Upgrade netty to 4.1.73.Final (2.4)

- build.gradle
- gradle/dependencies.gradle
> KC-1933; Upgrade confluent-log4j to 1.2.17-cp8

- build.gradle
- gradle/dependencies.gradle
> KC-1933; Upgrade confluent-log4j to 1.2.17-cp2.2

- clients/src/main/java/org/apache/kafka/clients/telemetry/TelemetryManagementInterface.java
- clients/src/test/java/org/apache/kafka/clients/telemetry/TelemetryManagementInterfaceTest.java
https://confluentinc.atlassian.net/browse/CLIENTS-1914
> Adding unit tests

- clients/src/main/java/org/apache/kafka/clients/telemetry/DefaultClientTelemetry.java
- clients/src/main/java/org/apache/kafka/clients/telemetry/TelemetrySubscription.java
Initial implementation of first fetch spread.
> CLIENTS-1899: 

- clients/src/main/java/org/apache/kafka/clients/FetchSessionHandler.java
- clients/src/main/java/org/apache/kafka/clients/admin/KafkaAdminClient.java
- clients/src/main/java/org/apache/kafka/clients/admin/internals/MetadataOperationContext.java
- clients/src/main/java/org/apache/kafka/clients/consumer/KafkaConsumer.java
- clients/src/main/java/org/apache/kafka/clients/consumer/internals/ConsumerCoordinator.java
- clients/src/main/java/org/apache/kafka/clients/producer/KafkaProducer.java
- clients/src/main/java/org/apache/kafka/clients/producer/internals/RecordAccumulator.java
- clients/src/main/java/org/apache/kafka/common/config/AbstractConfig.java
- clients/src/test/java/org/apache/kafka/clients/admin/KafkaAdminClientTest.java
- clients/src/test/java/org/apache/kafka/clients/consumer/KafkaConsumerTest.java
- clients/src/test/java/org/apache/kafka/clients/producer/KafkaProducerTest.java
- clients/src/test/java/org/apache/kafka/common/config/AbstractConfigTest.java
- connect/runtime/src/main/java/org/apache/kafka/connect/util/KafkaBasedLog.java
- connect/runtime/src/main/java/org/apache/kafka/connect/util/RetryUtil.java
- connect/runtime/src/main/java/org/apache/kafka/connect/util/TopicAdmin.java
- connect/runtime/src/test/java/org/apache/kafka/connect/util/KafkaBasedLogTest.java
- connect/runtime/src/test/java/org/apache/kafka/connect/util/RetryUtilTest.java
- connect/runtime/src/test/java/org/apache/kafka/connect/util/TopicAdminTest.java
- core/src/main/scala/kafka/server/AlterIsrManager.scala
- core/src/test/scala/integration/kafka/api/AuthorizerIntegrationTest.scala
- core/src/test/scala/unit/kafka/network/SocketServerTest.scala
- docs/streams/developer-guide/dsl-api.html
- streams/src/main/java/org/apache/kafka/streams/StreamsConfig.java
- streams/src/main/java/org/apache/kafka/streams/processor/internals/StateDirectory.java
- streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamThread.java
- streams/src/main/java/org/apache/kafka/streams/processor/internals/TaskManager.java
- streams/src/main/java/org/apache/kafka/streams/processor/internals/TopologyMetadata.java
- streams/src/main/java/org/apache/kafka/streams/processor/internals/namedtopology/KafkaStreamsNamedTopologyWrapper.java
- streams/src/main/java/org/apache/kafka/streams/processor/internals/namedtopology/RemoveNamedTopologyResult.java
- streams/src/test/java/org/apache/kafka/streams/integration/ConsistencyVectorIntegrationTest.java
There was a merge conflict in `TaskManager` and `TopologyMetadata` so I am manually merging.
The way we handle topology updates in the task manager and the topologyMetadata changed so that threads were not reregistered when they were shutdown. I accepted the most recent changes. Something must have got wrong with a previous merge to cause these conflicts.
> Merge AK into CCS

- clients/src/main/java/org/apache/kafka/clients/NetworkClient.java
- clients/src/main/java/org/apache/kafka/clients/telemetry/ClientTelemetry.java
- clients/src/main/java/org/apache/kafka/clients/telemetry/DefaultClientTelemetry.java
- clients/src/main/java/org/apache/kafka/clients/telemetry/NoopClientTelemetry.java
- clients/src/main/java/org/apache/kafka/clients/telemetry/TelemetrySubscription.java
- clients/src/test/java/org/apache/kafka/clients/telemetry/DefaultClientTelemetryTest.java
Handling telemetry errors and tests
> Handling telemetry client errors

- clients/src/main/java/org/apache/kafka/clients/telemetry/DefaultClientTelemetry.java
https://confluentinc.atlassian.net/browse/CLIENTS-2015
https://confluentinc.atlassian.net/browse/CLIENTS-1898
> handling errors

- core/src/main/scala/kafka/server/BrokerServer.scala
- core/src/main/scala/kafka/server/ControllerApis.scala
- core/src/main/scala/kafka/server/ControllerConfigurationValidator.scala
- core/src/main/scala/kafka/server/metadata/BrokerMetadataPublisher.scala
- core/src/test/scala/unit/kafka/server/ClientMetricsDynamicConfigChangeTest.scala
- core/src/test/scala/unit/kafka/server/ControllerConfigurationValidatorTest.scala
- Added changes to integrate new resource type CLIENT_METRICS with KRAFT changes.
- Added unit tests
> integrate client_metrics resource with kraft changes

- clients/src/main/java/org/apache/kafka/clients/telemetry/DefaultClientTelemetry.java
- clients/src/main/java/org/apache/kafka/common/metrics/MetricsReporter.java
- clients/src/main/java/org/apache/kafka/common/protocol/Errors.java
- clients/src/main/java/org/apache/kafka/common/requests/PushTelemetryRequest.java
- core/src/main/scala/kafka/metrics/clientmetrics/ClientMetricsReceiverPlugin.scala
- core/src/main/scala/kafka/server/ClientMetricsManager.scala
- core/src/main/scala/kafka/server/DynamicBrokerConfig.scala
- core/src/test/scala/integration/kafka/server/DynamicBrokerReconfigurationTest.scala
- core/src/test/scala/kafka/metrics/ClientMetricsRequestReponseTest.scala
- core/src/test/scala/kafka/metrics/ClientMetricsTestUtils.scala
- Added changes to integrate the MetricsReporter plugin with ClientMetricsManager code.
> initialize the client metrics plugin

- Vagrantfile
When running with 4th generation instances supporting EBS only, we need
to use a larger volume or else we run out of  disk space during a system
test run.
This change also parameterizes the instance type as an env variable for
easier testing.
Reviewers: David Jacot <djacot@confluent.io>
> MINOR: kafka system tests should support larger EBS volumes for newer instances (#12382)

- gradle/dependencies.gradle
[output.txt](https://github.com/confluentinc/kafka/files/9180506/output.txt)
> KSECURITY-509: upgrading netty to v4.1.79.Final (2.6)

- gradle/dependencies.gradle
[output.txt](https://github.com/confluentinc/kafka/files/9180213/output.txt)
> KSECURITY-509: upgrading netty to v4.1.79.Final (3.1)

- gradle/dependencies.gradle
[output.txt](https://github.com/confluentinc/kafka/files/9180041/output.txt)
> KSECURITY-509: upgrading netty to v4.1.79.Final

- gradle/dependencies.gradle
[output.txt](https://github.com/confluentinc/kafka/files/9180284/output.txt)
> KSECURITY-509: upgrading netty to v4.1.79.Final (2.8)

- gradle/dependencies.gradle
[output.txt](https://github.com/confluentinc/kafka/files/9180242/output.txt)
> KSECURITY-509: upgrading netty to v4.1.79.Final (3.0)

- gradle/dependencies.gradle
[output.txt](https://github.com/confluentinc/kafka/files/9180346/output.txt)
> KSECURITY-509: upgrading netty to v4.1.79.Final (2.7)

- gradle/dependencies.gradle
[output.txt](https://github.com/confluentinc/kafka/files/9180146/output.txt)
> KSECURITY-509: upgrading netty to v4.1.79.Final (3.2)

- gradle/dependencies.gradle
[output.txt](https://github.com/confluentinc/kafka/files/9180550/output.txt)
> KSECURITY-509: upgrading netty to v4.1.79.Final (2.5)

- gradle/dependencies.gradle
[output.txt](https://github.com/confluentinc/kafka/files/9179956/output.txt)
> KSECURITY-509: upgrading netty to v4.1.79.Final (2.4)

- build.gradle
- gradle/dependencies.gradle
**Jira:** https://confluentinc.atlassian.net/browse/KSECURITY-483
Migrating log4j12 to reload4j
Migrating slf4j-log4j12 to slf4j-reload4j.jar
> KSECURITY-478: migrating log4j12 to reload4j, slf4j-log4j12 to slf4j-reload4j.jar (3.3)

- gradle/dependencies.gradle
This backports changes in https://github.com/confluentinc/ce-kafka/pull/7071
> Upgrade jetty to 9.4.48.v20220622

- checkstyle/suppressions.xml
- clients/src/main/java/org/apache/kafka/common/config/internals/BrokerSecurityConfigs.java
- clients/src/main/java/org/apache/kafka/common/protocol/ByteBufferAccessor.java
- clients/src/main/java/org/apache/kafka/common/protocol/MessageUtil.java
- clients/src/main/java/org/apache/kafka/common/protocol/Readable.java
- clients/src/main/java/org/apache/kafka/common/protocol/RecordsReadable.java
- clients/src/main/java/org/apache/kafka/common/record/DefaultRecord.java
- clients/src/main/java/org/apache/kafka/common/security/authenticator/SaslServerAuthenticator.java
- clients/src/test/java/org/apache/kafka/common/message/SimpleArraysMessageTest.java
- clients/src/test/java/org/apache/kafka/common/protocol/ByteBufferAccessorTest.java
- clients/src/test/java/org/apache/kafka/common/record/DefaultRecordTest.java
- clients/src/test/java/org/apache/kafka/common/requests/RequestContextTest.java
- clients/src/test/java/org/apache/kafka/common/requests/RequestResponseTest.java
- clients/src/test/java/org/apache/kafka/common/security/TestSecurityConfig.java
- clients/src/test/java/org/apache/kafka/common/security/authenticator/SaslAuthenticatorTest.java
- clients/src/test/java/org/apache/kafka/common/security/authenticator/SaslServerAuthenticatorTest.java
- clients/src/test/resources/common/message/SimpleArraysMessage.json
- core/src/main/scala/kafka/server/KafkaConfig.scala
- core/src/test/scala/unit/kafka/server/KafkaConfigTest.scala
- generator/src/main/java/org/apache/kafka/message/MessageDataGenerator.java
> Fixes for 2.7 branch

- checkstyle/suppressions.xml
- clients/src/main/java/org/apache/kafka/common/config/internals/BrokerSecurityConfigs.java
- clients/src/main/java/org/apache/kafka/common/protocol/ByteBufferAccessor.java
- clients/src/main/java/org/apache/kafka/common/protocol/MessageUtil.java
- clients/src/main/java/org/apache/kafka/common/protocol/Readable.java
- clients/src/main/java/org/apache/kafka/common/record/DefaultRecord.java
- clients/src/main/java/org/apache/kafka/common/security/authenticator/SaslServerAuthenticator.java
- clients/src/test/java/org/apache/kafka/common/message/SimpleArraysMessageTest.java
- clients/src/test/java/org/apache/kafka/common/protocol/ByteBufferAccessorTest.java
- clients/src/test/java/org/apache/kafka/common/record/DefaultRecordTest.java
- clients/src/test/java/org/apache/kafka/common/requests/RequestContextTest.java
- clients/src/test/java/org/apache/kafka/common/requests/RequestResponseTest.java
- clients/src/test/java/org/apache/kafka/common/security/TestSecurityConfig.java
- clients/src/test/java/org/apache/kafka/common/security/authenticator/SaslAuthenticatorTest.java
- clients/src/test/java/org/apache/kafka/common/security/authenticator/SaslServerAuthenticatorTest.java
- clients/src/test/resources/common/message/SimpleArraysMessage.json
- core/src/main/scala/kafka/server/KafkaConfig.scala
- core/src/test/scala/unit/kafka/server/KafkaConfigTest.scala
- generator/src/main/java/org/apache/kafka/message/MessageDataGenerator.java
> Fixes for 2.5 branch

- checkstyle/suppressions.xml
- clients/src/main/java/org/apache/kafka/common/config/internals/BrokerSecurityConfigs.java
- clients/src/main/java/org/apache/kafka/common/protocol/ByteBufferAccessor.java
- clients/src/main/java/org/apache/kafka/common/protocol/MessageUtil.java
- clients/src/main/java/org/apache/kafka/common/protocol/Readable.java
- clients/src/main/java/org/apache/kafka/common/record/DefaultRecord.java
- clients/src/main/java/org/apache/kafka/common/security/authenticator/SaslServerAuthenticator.java
- clients/src/test/java/org/apache/kafka/common/message/SimpleArraysMessageTest.java
- clients/src/test/java/org/apache/kafka/common/protocol/ByteBufferAccessorTest.java
- clients/src/test/java/org/apache/kafka/common/record/DefaultRecordTest.java
- clients/src/test/java/org/apache/kafka/common/requests/RequestContextTest.java
- clients/src/test/java/org/apache/kafka/common/requests/RequestResponseTest.java
- clients/src/test/java/org/apache/kafka/common/security/TestSecurityConfig.java
- clients/src/test/java/org/apache/kafka/common/security/authenticator/SaslAuthenticatorTest.java
- clients/src/test/java/org/apache/kafka/common/security/authenticator/SaslServerAuthenticatorTest.java
- clients/src/test/resources/common/message/SimpleArraysMessage.json
- core/src/main/scala/kafka/server/KafkaConfig.scala
- core/src/test/scala/unit/kafka/server/KafkaConfigTest.scala
- generator/src/main/java/org/apache/kafka/message/MessageDataGenerator.java
> Fixes for 2.6 branch

- checkstyle/suppressions.xml
- clients/src/main/java/org/apache/kafka/common/config/internals/BrokerSecurityConfigs.java
- clients/src/main/java/org/apache/kafka/common/protocol/ByteBufferAccessor.java
- clients/src/main/java/org/apache/kafka/common/protocol/MessageUtil.java
- clients/src/main/java/org/apache/kafka/common/protocol/Readable.java
- clients/src/main/java/org/apache/kafka/common/record/DefaultRecord.java
- clients/src/main/java/org/apache/kafka/common/security/authenticator/SaslServerAuthenticator.java
- clients/src/test/java/org/apache/kafka/common/message/SimpleArraysMessageTest.java
- clients/src/test/java/org/apache/kafka/common/protocol/ByteBufferAccessorTest.java
- clients/src/test/java/org/apache/kafka/common/record/DefaultRecordTest.java
- clients/src/test/java/org/apache/kafka/common/requests/RequestContextTest.java
- clients/src/test/java/org/apache/kafka/common/requests/RequestResponseTest.java
- clients/src/test/java/org/apache/kafka/common/security/TestSecurityConfig.java
- clients/src/test/java/org/apache/kafka/common/security/authenticator/SaslAuthenticatorTest.java
- clients/src/test/java/org/apache/kafka/common/security/authenticator/SaslServerAuthenticatorTest.java
- clients/src/test/resources/common/message/SimpleArraysMessage.json
- core/src/main/scala/kafka/server/KafkaConfig.scala
- core/src/test/scala/unit/kafka/server/KafkaConfigTest.scala
- generator/src/main/java/org/apache/kafka/message/MessageDataGenerator.java
> Fixes for 2.4 branch

- .github/CODEOWNERS
> Add ksql to CODEOWNERS

- README.md
- build.gradle
- connect/mirror/src/main/java/org/apache/kafka/connect/mirror/MirrorSourceConnector.java
- connect/mirror/src/test/java/org/apache/kafka/connect/mirror/MirrorSourceConnectorTest.java
- core/src/main/scala/kafka/controller/KafkaController.scala
- core/src/test/scala/integration/kafka/admin/TopicCommandIntegrationTest.scala
- core/src/test/scala/unit/kafka/controller/ControllerIntegrationTest.scala
- gradle/dependencies.gradle
- gradle/spotbugs-exclude.xml
- metadata/src/main/java/org/apache/kafka/controller/ReplicationControlManager.java
- raft/src/main/java/org/apache/kafka/raft/VotedState.java
- raft/src/test/java/org/apache/kafka/raft/ResignedStateTest.java
- raft/src/test/java/org/apache/kafka/raft/ValidOffsetAndEpochTest.java
- streams/quickstart/java/src/main/resources/archetype-resources/pom.xml
- streams/quickstart/java/src/main/resources/archetype-resources/src/main/java/LineSplit.java
- streams/quickstart/java/src/main/resources/archetype-resources/src/main/java/Pipe.java
- streams/quickstart/java/src/main/resources/archetype-resources/src/main/java/WordCount.java
- streams/src/main/java/org/apache/kafka/streams/KafkaStreams.java
- streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamThread.java
- streams/src/test/java/org/apache/kafka/streams/KafkaStreamsTest.java
- tests/kafkatest/tests/connect/connect_distributed_test.py
- tests/kafkatest/tests/connect/connect_rest_test.py
- tests/kafkatest/tests/connect/connect_test.py
PR https://github.com/apache/kafka/pull/12719 created a conflict that breaks the sync job between AK and CCS. To resolve this manually created this PR to only view the changes. 
NOTE: This PR shouldn't be merged. A manual merge is required to be done by CLI to preserve the commit history
> [DO NOT MERGE] Manual merge to resolve conflict

- gradle/dependencies.gradle
JIRA: https://confluentinc.atlassian.net/browse/KSECURITY-788
> KSECURITY-788: Upgrade jackson-databind version to 2.13.4.2

- LICENSE-binary
- bin/kafka-run-class.sh
- bin/windows/kafka-run-class.bat
- build.gradle
- core/src/main/scala/kafka/log/LazyIndex.scala
- core/src/main/scala/kafka/server/KafkaApis.scala
- core/src/test/scala/integration/kafka/api/GroupAuthorizerIntegrationTest.scala
- core/src/test/scala/integration/kafka/api/SaslGssapiSslEndToEndAuthorizationTest.scala
- core/src/test/scala/unit/kafka/admin/TopicCommandWithAdminClientTest.scala
- gradle.properties
- gradle/dependencies.gradle
- gradle/spotbugs-exclude.xml
- streams/streams-scala/src/test/scala/org/apache/kafka/streams/scala/TopologyTest.scala
- streams/streams-scala/src/test/scala/org/apache/kafka/streams/scala/WordCountTest.scala
JIRA: https://confluentinc.atlassian.net/browse/KSECURITY-792
> KSECURITY-792: Upgrade from Scala 2.13.8 to 2.13.10

- build.gradle
> CONFLUENT: Skip publishing for kafka-streams-upgrade-system-tests

- core/src/main/java/kafka/log/remote/RemoteLogManager.java
- core/src/test/java/kafka/log/remote/RemoteLogManagerTest.java
Cherrypick to fix build issues.
commit f905a5a45d87c94d369cde9d1326e6d18b95cf7e
Author: vamossagar12 <sagarmeansocean@gmail.com>
Date:   Wed Apr 19 00:46:03 2023 +0530
MINOR: Fixing gradle build during compileScala and compileTestScala (#13588)
Reviewers: Chia-Ping Tsai <chia7712@gmail.com>
> MINOR: Fixing gradle build during compileScala and compileTestScala (#13588)

- clients/src/test/java/org/apache/kafka/common/record/DefaultRecordBatchTest.java
The sync job has been delayed due to all builds timing out. I will disable the test that seems to be causing issues so we can unblock builds.
> MINOR: Disable test to unblock builds

- gradle/dependencies.gradle
> KSECURITY-1859: updating netty to 4.1.96 (3.0)

- gradle/dependencies.gradle
> KSECURITY-1859: updating netty to 4.1.96 (3.2)

- gradle/dependencies.gradle
> KSECURIYT-1859: upgrading netty to 4.1.96.Final (3.5)

- gradle/dependencies.gradle
> KSECURITY-1859: upgrading netty to 4.1.96.Final

- gradle/dependencies.gradle
> KSECURIYT-1859: updating netty to 4.1.96 (3.1)

- gradle/dependencies.gradle
> KSECURIYT-1859: updating netty to 4.1.96 (3.4)

- tests/setup.py
> KSECURITY-1789: upgrading requests to v2.31.0 (3.0)

- tests/setup.py
> KSECURITY-1789: upgrading requests to v2.31.0 (3.1)

- tests/setup.py
> KSECURITY-1789: upgrading requests to v2.31.0 (3.2)

- tests/setup.py
> KSECURITY-1789: upgrading requests to v2.31.0 (3.5)

- tests/setup.py
Reverts confluentinc/kafka#938
> Revert "KSECURITY-1789: upgrading requests to v2.31.0"

- tests/setup.py
Test unpinning the requests.
System tests when ran on branch builder ran fine (https://jenkins.confluent.io/job/system-test-kafka-branch-builder/5844/)
> [Test] Trying to fix breaking build by unpinning the Requests from system tests

- gradle/dependencies.gradle
*What*
Updated bcpkix version to 1.77
> KSECURITY-2090: Updated bcpkix version to 1.77

- clients/src/main/resources/common/message/ShareAcknowledgeRequest.json
- clients/src/main/resources/common/message/ShareAcknowledgeResponse.json
- clients/src/main/resources/common/message/ShareFetchRequest.json
- clients/src/main/resources/common/message/ShareFetchResponse.json
- core/src/test/scala/unit/kafka/server/epoch/LeaderEpochIntegrationTest.scala
- core/src/test/scala/unit/kafka/utils/TestUtils.scala
- docs/quickstart.html
PR contains the json schema for ShareFetch and ShareAcknowledge APIs for KIP-932.
> AKCORE-7: Defined request/response for ShareFetch and ShareAcknowledge APIs

- group-coordinator/src/main/java/org/apache/kafka/coordinator/group/Group.java
- group-coordinator/src/main/java/org/apache/kafka/coordinator/group/GroupMember.java
- group-coordinator/src/main/java/org/apache/kafka/coordinator/group/GroupMetadataManager.java
- group-coordinator/src/main/java/org/apache/kafka/coordinator/group/common/CurrentAssignmentBuilder.java
- group-coordinator/src/main/java/org/apache/kafka/coordinator/group/common/TargetAssignmentBuilder.java
- group-coordinator/src/main/java/org/apache/kafka/coordinator/group/consumer/ConsumerGroup.java
- group-coordinator/src/main/java/org/apache/kafka/coordinator/group/consumer/ConsumerGroupMember.java
- group-coordinator/src/main/java/org/apache/kafka/coordinator/group/share/ShareGroup.java
- group-coordinator/src/main/java/org/apache/kafka/coordinator/group/share/ShareGroupMember.java
- group-coordinator/src/main/java/org/apache/kafka/coordinator/group/share/SimpleAssignor.java
- group-coordinator/src/main/resources/common/message/ConsumerGroupMetadataValue.json
- group-coordinator/src/test/java/org/apache/kafka/coordinator/group/common/AssignmentTest.java
- group-coordinator/src/test/java/org/apache/kafka/coordinator/group/common/CurrentAssignmentBuilderTest.java
- group-coordinator/src/test/java/org/apache/kafka/coordinator/group/common/SubscribedTopicMetadataTest.java
- group-coordinator/src/test/java/org/apache/kafka/coordinator/group/common/TargetAssignmentBuilderTest.java
- group-coordinator/src/test/java/org/apache/kafka/coordinator/group/common/TopicMetadataTest.java
- group-coordinator/src/test/java/org/apache/kafka/coordinator/group/common/VersionedMetadataTest.java
- Added abstract class `GroupMember` to abstract common methods.
- Refactored existing classes to use `GroupMember` for assignment builder
- Added `SimpleAssignor`, `ShareGroup` and `ShareGroupMember` classes
- Added `boilerplate` code in `GroupMetadataManager` to support ShareGroupHeartbeat
> AKCORE-1: Refactored code to have common functionality (3/N)

- core/src/test/scala/unit/kafka/server/KafkaApisTest.scala
**About**
This PR adds a new test for verifying Share group heartbeat request failure `testShareGroupHeartbeatRequestFutureFailed`
**Testing**
The test passes as shown in the screenshot
> AKCORE-3: Added test to check failure of share group heartbeat request

- group-coordinator/src/main/java/org/apache/kafka/coordinator/group/GroupMetadataManager.java
- group-coordinator/src/main/java/org/apache/kafka/coordinator/group/RecordHelpers.java
- group-coordinator/src/main/java/org/apache/kafka/coordinator/group/share/ShareGroup.java
- group-coordinator/src/test/java/org/apache/kafka/coordinator/group/GroupMetadataManagerTest.java
- group-coordinator/src/test/java/org/apache/kafka/coordinator/group/RecordHelpersTest.java
- Share group heartbeat implementation with group epoch records on `__consumer_offsets` topic.
> AKCORE-1: Implemented share group heartbeat (4/N)

- clients/src/main/java/org/apache/kafka/clients/consumer/internals/ShareConsumerImpl.java
- clients/src/main/java/org/apache/kafka/clients/consumer/internals/ShareHeartbeatRequestManager.java
- clients/src/test/java/org/apache/kafka/clients/consumer/internals/ShareHeartbeatRequestManagerTest.java
Tidying up some loose ends in the initial implementation of KafkaShareConsumer.
> AKCORE-2: Tidying up (3/N)

- bin/kafka-console-share-consumer.sh
- bin/windows/kafka-console-share-consumer.bat
- checkstyle/suppressions.xml
- tools/src/main/java/org/apache/kafka/tools/ConsoleShareConsumer.java
- tools/src/main/java/org/apache/kafka/tools/ConsoleShareConsumerOptions.java
- tools/src/test/java/org/apache/kafka/tools/ConsoleShareConsumerOptionsTest.java
- tools/src/test/java/org/apache/kafka/tools/ConsoleShareConsumerTest.java
*What*
Added *kafka-console-share-consumer.sh* tool as part of KIP-932.
KIP-932 - https://cwiki.apache.org/confluence/display/KAFKA/KIP-932%3A+Queues+for+Kafka.
Options remaining to be added are --release, --reject and --enable-systest-events.
> AKCORE-5 : Added kafka-console-share-consumer.sh tool

- clients/src/main/java/org/apache/kafka/common/security/oauthbearer/internals/secured/JaasOptionsUtils.java
This is to make JaasOptionsUtils  compatible with ce-kafka
> MINOR: Add validateOAuthMechanismAndNonNullJaasConfig method to JaasOptionsUtils

- clients/src/main/java/org/apache/kafka/clients/consumer/internals/ShareConsumerImpl.java
- clients/src/test/java/org/apache/kafka/clients/consumer/internals/ShareConsumerImplTest.java
Added implementation of `KafkaShareConsumer.wakeup()` so that it can interrupt the network thread. This gives better behaviour during JVM shutdown.
> AKCORE-25: Enhance KafkaShareConsumer wakeup

- group-coordinator/src/test/java/org/apache/kafka/coordinator/group/GroupMetadataManagerTest.java
> MINOR: Removing unused method in test

- clients/src/main/java/org/apache/kafka/clients/admin/Admin.java
- clients/src/main/java/org/apache/kafka/clients/admin/DescribeShareGroupsOptions.java
- clients/src/main/java/org/apache/kafka/clients/admin/DescribeShareGroupsResult.java
- clients/src/main/java/org/apache/kafka/clients/admin/ForwardingAdmin.java
- clients/src/main/java/org/apache/kafka/clients/admin/KafkaAdminClient.java
- clients/src/main/java/org/apache/kafka/clients/admin/ShareGroupDescription.java
- clients/src/main/java/org/apache/kafka/clients/admin/internals/DescribeConsumerGroupsHandler.java
- clients/src/main/java/org/apache/kafka/clients/admin/internals/DescribeGroupsHandlerHelper.java
- clients/src/main/java/org/apache/kafka/clients/admin/internals/DescribeShareGroupsHandler.java
- clients/src/main/java/org/apache/kafka/common/protocol/ApiKeys.java
- clients/src/main/java/org/apache/kafka/common/requests/AbstractRequest.java
- clients/src/main/java/org/apache/kafka/common/requests/AbstractResponse.java
- clients/src/main/java/org/apache/kafka/common/requests/ShareGroupDescribeRequest.java
- clients/src/main/java/org/apache/kafka/common/requests/ShareGroupDescribeResponse.java
- clients/src/test/java/org/apache/kafka/clients/admin/KafkaAdminClientTest.java
- clients/src/test/java/org/apache/kafka/clients/admin/MockAdminClient.java
- core/src/main/scala/kafka/coordinator/group/GroupCoordinatorAdapter.scala
- core/src/main/scala/kafka/server/KafkaApis.scala
- core/src/test/scala/unit/kafka/server/KafkaApisTest.scala
- group-coordinator/src/main/java/org/apache/kafka/coordinator/group/GroupCoordinator.java
- group-coordinator/src/main/java/org/apache/kafka/coordinator/group/GroupCoordinatorService.java
- group-coordinator/src/main/java/org/apache/kafka/coordinator/group/GroupCoordinatorShard.java
- group-coordinator/src/main/java/org/apache/kafka/coordinator/group/GroupMetadataManager.java
- group-coordinator/src/main/java/org/apache/kafka/coordinator/group/Utils.java
- group-coordinator/src/main/java/org/apache/kafka/coordinator/group/consumer/ConsumerGroupMember.java
- group-coordinator/src/main/java/org/apache/kafka/coordinator/group/share/ShareGroup.java
- group-coordinator/src/main/java/org/apache/kafka/coordinator/group/share/ShareGroupMember.java
- group-coordinator/src/test/java/org/apache/kafka/coordinator/group/GroupCoordinatorServiceTest.java
- group-coordinator/src/test/java/org/apache/kafka/coordinator/group/GroupMetadataManagerTest.java
- group-coordinator/src/test/java/org/apache/kafka/coordinator/group/GroupMetadataManagerTestContext.java
> AKCORE-9: ShareGroupDescribe support for KafkaAdminclient

- clients/src/main/java/org/apache/kafka/common/requests/AbstractRequest.java
- clients/src/main/java/org/apache/kafka/common/requests/AbstractResponse.java
- clients/src/main/java/org/apache/kafka/common/requests/ShareAcknowledgeResponse.java
- clients/src/main/java/org/apache/kafka/common/requests/ShareFetchResponse.java
- clients/src/test/java/org/apache/kafka/clients/admin/KafkaAdminClientTest.java
- clients/src/test/java/org/apache/kafka/common/requests/RequestResponseTest.java
Fixed some failing tests in admin client and request handling.
> AKCORE-22: Fix test failures (2/N)

- clients/src/main/java/org/apache/kafka/clients/consumer/internals/MemberState.java
- clients/src/main/java/org/apache/kafka/clients/consumer/internals/RequestManagers.java
- clients/src/main/java/org/apache/kafka/clients/consumer/internals/ShareConsumerImpl.java
- clients/src/main/java/org/apache/kafka/clients/consumer/internals/ShareFetchBuffer.java
- clients/src/main/java/org/apache/kafka/clients/consumer/internals/ShareFetchRequestManager.java
- clients/src/main/java/org/apache/kafka/clients/consumer/internals/ShareHeartbeatRequestManager.java
- clients/src/main/java/org/apache/kafka/clients/consumer/internals/ShareMembershipManager.java
- clients/src/test/java/org/apache/kafka/clients/consumer/internals/ShareConsumerTestBuilder.java
- clients/src/test/java/org/apache/kafka/clients/consumer/internals/ShareHeartbeatRequestManagerTest.java
- clients/src/test/java/org/apache/kafka/clients/consumer/internals/ShareMembershipManagerTest.java
Create an empty ShareFetchRequestManager and ShareFetchBuffer. Also make some improvements in the state management of the membership manager.
> AKCORE-22-3: Scaffolding for fetch and improvements (3/N)

- core/src/main/java/kafka/server/SharePartitionManager.java
Initial commit to unblock others for making further changes.
> AKCORE-32: Initial commit to define share partition manager class (1/N)

- clients/src/main/java/org/apache/kafka/clients/consumer/internals/ShareSessionHandler.java
- clients/src/main/java/org/apache/kafka/common/requests/ShareAcknowledgeResponse.java
- clients/src/main/java/org/apache/kafka/common/requests/ShareFetchResponse.java
- clients/src/test/java/org/apache/kafka/clients/consumer/internals/ShareSessionHandlerTest.java
Initial implementation of ShareSessionHandler and unit test.
> AKCORE-22-4: Initial implementation of ShareSessionHandler (4/N)

- clients/src/main/java/org/apache/kafka/common/requests/ShareFetchRequest.java
- clients/src/main/java/org/apache/kafka/common/requests/ShareFetchResponse.java
- core/src/main/java/kafka/server/ShareFetchContext.java
- core/src/main/java/kafka/server/SharePartition.java
- core/src/main/java/kafka/server/SharePartitionKey.java
- core/src/main/java/kafka/server/SharePartitionManager.java
- core/src/test/java/kafka/server/SharePartitionKeyTest.java
Initial commit to define APIs for share partition manager communication with KafkaApis
Reference - [AKCORE-32](https://confluentinc.atlassian.net/browse/AKCORE-32)
[AKCORE-32]: https://confluentinc.atlassian.net/browse/AKCORE-32?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> AKCORE-32: Defined APIs for SharePartitionManager

- core/src/main/java/kafka/server/ShareFetchContext.java
- core/src/main/java/kafka/server/SharePartition.java
- core/src/main/java/kafka/server/SharePartitionKey.java
- core/src/main/java/kafka/server/SharePartitionManager.java
- core/src/test/java/kafka/server/SharePartitionKeyTest.java
- tools/src/main/java/org/apache/kafka/tools/ShareGroupsCommand.java
MINOR: Fix checkstyles issue causing build failure
> MINOR: Fix checkstyles issue

- clients/src/main/java/org/apache/kafka/clients/consumer/internals/CompletedShareFetch.java
- clients/src/main/java/org/apache/kafka/clients/consumer/internals/RequestManagers.java
- clients/src/main/java/org/apache/kafka/clients/consumer/internals/ShareConsumerImpl.java
- clients/src/main/java/org/apache/kafka/clients/consumer/internals/ShareFetchBuffer.java
- clients/src/main/java/org/apache/kafka/clients/consumer/internals/ShareFetchCollector.java
- clients/src/main/java/org/apache/kafka/clients/consumer/internals/ShareFetchRequestManager.java
- clients/src/main/java/org/apache/kafka/common/requests/ShareFetchResponse.java
- clients/src/test/java/org/apache/kafka/clients/consumer/internals/ShareConsumerImplTest.java
- clients/src/test/java/org/apache/kafka/clients/consumer/internals/ShareConsumerTestBuilder.java
Added supporting classes for fetching records for a share consumer, such as CompletedShareFetch.
> AKCORE-22-6: Initial commit of share consumer utilities (6/N)

- server/src/main/java/org/apache/kafka/server/config/Defaults.java
> AKCORE-13: Correcting data type mismatch

- clients/src/main/java/org/apache/kafka/common/security/oauthbearer/internals/secured/JaasOptionsUtils.java
This is to make JaasOptionsUtils compatible with ce-kafka
> MINOR: Add validateOAuthMechanismAndNonNullJaasConfig to JaasOptionsUtils

- clients/src/main/java/org/apache/kafka/common/requests/ShareFetchRequest.java
- core/src/test/java/kafka/test/api/PlaintextShareConsumerTest.java
Adjust the building of the ShareFetch request so that it matches the broker's expectations. Then data starts flowing, so an integration test needs changing to reflect the fact that fetching now works.
> AKCORE-22-7: Tweaks to work with broker (7/N)

- clients/src/main/resources/common/message/ShareAcknowledgeRequest.json
- clients/src/main/resources/common/message/ShareFetchRequest.json
- core/src/main/java/kafka/server/SharePartitionManager.java
AKCORE-32: Defined signature for share acknowledge functionality and added definition of Share Sessions
> AKCORE-32: Defined signature for acknowledge functionality and added definition of Share Sessions

- clients/src/main/java/org/apache/kafka/clients/consumer/internals/ShareFetchBuffer.java
- clients/src/test/java/org/apache/kafka/clients/consumer/internals/CompletedShareFetchTest.java
- clients/src/test/java/org/apache/kafka/clients/consumer/internals/ShareFetchBufferTest.java
- clients/src/test/java/org/apache/kafka/clients/consumer/internals/ShareFetchCollectorTest.java
Adding unit tests for fetching utility classes for share groups.
> AKCORE-22-8: Unit tests for fetching utility classes (9/N)

- core/src/main/scala/kafka/server/KafkaApis.scala
- core/src/test/scala/unit/kafka/server/KafkaApisTest.scala
AKCORE-12: Added check for group.share.enable config for ShareFetch RPC
> AKCORE-12: Added check for group.share.enable config for ShareFetch RPC

- core/src/main/java/kafka/server/SharePartition.java
- core/src/main/java/kafka/server/SharePartitionManager.java
- core/src/main/scala/kafka/server/KafkaApis.scala
- core/src/test/scala/unit/kafka/server/KafkaApisTest.scala
> AKCORE-15: Acknowledge API for Share Partition (1/N)

- checkstyle/suppressions.xml
- clients/src/main/java/org/apache/kafka/clients/consumer/AcknowledgeType.java
- core/src/main/java/kafka/server/SharePartition.java
- core/src/main/java/kafka/server/SharePartitionManager.java
- core/src/test/java/kafka/server/SharePartitionTest.java
> AKCORE-15: Share Partition implementation for acquire and acknowledge

- clients/src/main/java/org/apache/kafka/clients/consumer/internals/Acknowledgements.java
- clients/src/main/java/org/apache/kafka/clients/consumer/internals/ShareCompletedFetch.java
- clients/src/main/java/org/apache/kafka/clients/consumer/internals/ShareConsumerImpl.java
- clients/src/main/java/org/apache/kafka/clients/consumer/internals/ShareFetch.java
- clients/src/main/java/org/apache/kafka/clients/consumer/internals/ShareFetchCollector.java
- clients/src/main/java/org/apache/kafka/clients/consumer/internals/ShareInFlightBatch.java
- clients/src/test/java/org/apache/kafka/clients/consumer/internals/ShareCompletedFetchTest.java
- clients/src/test/java/org/apache/kafka/clients/consumer/internals/ShareFetchRequestManagerTest.java
Restructuring of code to cope with deserialization and CRC check failures.
> AKCORE-23: Handle bad records

- core/src/main/java/kafka/server/SharePartitionManager.java
- core/src/test/java/kafka/server/SharePartitionManagerTest.java
This PR contains the following changes with respect to `SharePartitionManager`- 
1. Added a function to get share session errors from a share acknowledge perspective
2. We do not need a special handling for `shareSession.isEmpty()` (case where all the partitions have been unsubscribed for the member). This should be handled how a regular `ShareSessionContext` works.
3. Solved a bug where an updated topic partition was not getting displayed in `updateAndGenerateResponseData()` for `ShareSessionContext`
4. Refractored a duplicate code block
5. Added more unit tests for `SharePartitionManager`
Here are some stats related to unit tests for SharePartitionManager - 
- **Class %** -> **100%(14/14)**
- **Method %** -> **87%(89/102)**
- **Line %** -> **80%(359/447)**
> AKCORE-41: Implement share sessions on broker(2/N)

- clients/src/main/java/org/apache/kafka/clients/consumer/AcknowledgeType.java
- core/src/main/java/kafka/server/SharePartition.java
- core/src/main/java/kafka/server/SharePartitionManager.java
- core/src/main/scala/kafka/server/KafkaApis.scala
- core/src/test/scala/unit/kafka/server/KafkaApisTest.scala
This PR contains the implementation of acknowledge function inside SharePartitionManager.java. This function is called from handleShareAcknowledgeRequest handler in KafkaApis.scala. 
Reference - [AKCORE-40](https://confluentinc.atlassian.net/jira/software/c/projects/AKCORE/issues/AKCORE-40)
[AKCORE-40]: https://confluentinc.atlassian.net/browse/AKCORE-40?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Akcore 40: Acknowledge implementation in the SharePartitionManager

- core/src/main/scala/kafka/server/KafkaApis.scala
> [Minor]: Removed unnecessary conversion and added acquired records in response

- clients/src/test/java/org/apache/kafka/clients/consumer/internals/ShareCompletedFetchTest.java
- clients/src/test/java/org/apache/kafka/clients/consumer/internals/ShareFetchCollectorTest.java
- clients/src/test/java/org/apache/kafka/clients/consumer/internals/ShareFetchRequestManagerTest.java
*What*
Added tests for checking acquired records in ShareCompletedFetch and ShareFetchRequestManager.
> AKCORE-23-Test: Added tests for checking acquired records.

- clients/src/main/java/org/apache/kafka/clients/consumer/internals/Acknowledgements.java
- clients/src/main/java/org/apache/kafka/clients/consumer/internals/ShareCompletedFetch.java
- clients/src/main/java/org/apache/kafka/clients/consumer/internals/ShareConsumerImpl.java
- clients/src/main/java/org/apache/kafka/clients/consumer/internals/ShareFetch.java
- clients/src/main/java/org/apache/kafka/clients/consumer/internals/ShareFetchBuffer.java
- clients/src/main/java/org/apache/kafka/clients/consumer/internals/ShareFetchRequestManager.java
- clients/src/main/java/org/apache/kafka/clients/consumer/internals/ShareSessionHandler.java
- clients/src/test/java/org/apache/kafka/clients/consumer/internals/ShareSessionHandlerTest.java
Implement implicit acknowledgements by sending acknowledgements in the ShareFetch requests, and handling the error code in the ShareFetch responses.
> AKCORE-23: Piggyback acknowledgements on share fetch requests

- clients/src/main/java/org/apache/kafka/clients/consumer/internals/ShareFetchRequestManager.java
- clients/src/main/java/org/apache/kafka/clients/consumer/internals/ShareSessionHandler.java
- clients/src/main/java/org/apache/kafka/common/requests/ShareFetchRequest.java
Changes to the client to align with the broker on share session management.
> AKCORE-23-6: Fixes for share session management

- clients/src/test/java/org/apache/kafka/clients/consumer/internals/ShareSessionHandlerTest.java
Fix trivial unit test failures.
> AKCORE-23-7: Fix failing unit test

- core/src/test/scala/unit/kafka/server/ShareGroupHeartbeatRequestTest.scala
- group-coordinator/src/main/java/org/apache/kafka/coordinator/group/AbstractGroup.java
- group-coordinator/src/main/java/org/apache/kafka/coordinator/group/GroupCoordinatorShard.java
- group-coordinator/src/main/java/org/apache/kafka/coordinator/group/GroupMember.java
- group-coordinator/src/main/java/org/apache/kafka/coordinator/group/GroupMetadataManager.java
- group-coordinator/src/main/java/org/apache/kafka/coordinator/group/RecordHelpers.java
- group-coordinator/src/main/java/org/apache/kafka/coordinator/group/Utils.java
- group-coordinator/src/main/java/org/apache/kafka/coordinator/group/consumer/ConsumerGroup.java
- group-coordinator/src/main/java/org/apache/kafka/coordinator/group/consumer/ConsumerGroupMember.java
- group-coordinator/src/main/java/org/apache/kafka/coordinator/group/share/ShareGroup.java
- group-coordinator/src/main/java/org/apache/kafka/coordinator/group/share/ShareGroupMember.java
- group-coordinator/src/test/java/org/apache/kafka/coordinator/group/GroupCoordinatorShardTest.java
- Abstracted consumer and share group code
- Added replay behaviour for share group
- - Added fixes for share group.
> AKCORE-44: Abstract GC code and replay records

- core/src/main/java/kafka/server/SharePartition.java
- core/src/main/java/kafka/server/SharePartitionManager.java
- core/src/main/scala/kafka/server/KafkaApis.scala
- Fixed lock handling and release for share partition (finally is incorrect, share partition lock pre-emptive release is incorrect)
- Refactored code.
> AKCORE-72: Refactored share partition manager to handle locks better

- gradle.properties
- streams/quickstart/java/pom.xml
- streams/quickstart/java/src/main/resources/archetype-resources/pom.xml
- streams/quickstart/pom.xml
- tests/kafkatest/__init__.py
- tests/kafkatest/version.py
> MINOR: Bump ccs/3.7 to 7.7.0-0-ccs

- core/src/test/scala/integration/kafka/api/AbstractShareConsumerTest.scala
- core/src/test/scala/unit/kafka/utils/TestUtils.scala
Build fix for scala 2.12 version.
> MINOR: Fixing build

- core/src/test/scala/unit/kafka/server/ShareGroupHeartbeatRequestTest.scala
- group-coordinator/src/main/java/org/apache/kafka/coordinator/group/GroupMetadataManager.java
> Fixing member heartbeat interval timeout in share group

- group-coordinator/src/main/java/org/apache/kafka/coordinator/group/share/ShareGroup.java
- group-coordinator/src/test/java/org/apache/kafka/coordinator/group/GroupMetadataManagerTest.java
- group-coordinator/src/test/java/org/apache/kafka/coordinator/group/GroupMetadataManagerTestContext.java
> AKCORE-64: Added additional tests and fixes for share group

- LICENSE-binary
- gradle/dependencies.gradle
Cherrypick https://github.com/confluentinc/kafka/pull/1103
> KSECURITY-2360 KAFKA-16210: Update jose4j to 0.9.4 (#15284)

- LICENSE-binary
- gradle/dependencies.gradle
Cherrypick https://github.com/confluentinc/kafka/pull/1103
> KSECURITY-2360 CVE 2023 51775 cherrypick fix 3.1

- core/src/main/scala/kafka/server/BrokerServer.scala
- core/src/main/scala/kafka/server/KafkaConfig.scala
- core/src/test/scala/unit/kafka/server/KafkaConfigTest.scala
- core/src/test/scala/unit/kafka/server/ShareGroupHeartbeatRequestTest.scala
- group-coordinator/src/main/java/org/apache/kafka/coordinator/group/GroupCoordinatorConfig.java
- group-coordinator/src/main/java/org/apache/kafka/coordinator/group/GroupCoordinatorShard.java
- group-coordinator/src/main/java/org/apache/kafka/coordinator/group/GroupMetadataManager.java
- group-coordinator/src/test/java/org/apache/kafka/coordinator/group/GroupCoordinatorConfigTest.java
- group-coordinator/src/test/java/org/apache/kafka/coordinator/group/GroupCoordinatorServiceTest.java
- server/src/main/java/org/apache/kafka/server/config/Defaults.java
AKCORE-78: Add `group.share.session.timeout.ms` and `group.share.heartbeat.interval.ms` configs for share group
> AKCORE-78: Add group.share.session.timeout.ms and group.share.heartbeat.interval.ms

- core/src/main/java/kafka/server/SharePartitionManager.java
Removed data structure `Evictable` form `ShareSessionCache` since it was not required. It was introduced in Fetch sessions in order to remove fetch sessions based on the size of fetch session. In share sessions, there is no such eviction policy based on size of share session. It only evicts based on staleness of a share session. I had created this data structure earlier, but never used it after realizing the eviction policy of share sessions.
> AKCORE-79: MINOR: Refactor ShareSessionCache in broker

- core/src/test/java/kafka/test/api/PlaintextShareConsumerTest.java
This PR contains multiple Integration tests to test different edge cases for shareFetchRequest
Reference : [AKCORE-61](https://confluentinc.atlassian.net/jira/software/c/projects/AKCORE/issues/AKCORE-61?jql=project%20%3D%20%22AKCORE%22%20ORDER%20BY%20created%20DESC)
[AKCORE-61]: https://confluentinc.atlassian.net/browse/AKCORE-61?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> AKCORE-61: Added more Integration tests for shareFetchRequest

- core/src/main/java/kafka/server/SharePartitionManager.java
- core/src/main/scala/kafka/server/BrokerServer.scala
- core/src/test/java/kafka/server/SharePartitionManagerTest.java
This PR contains unit tests for acknowledge function in SharePartitionMaager
Reference: [AKCORE-60](https://confluentinc.atlassian.net/jira/software/c/projects/AKCORE/issues/AKCORE-60)
[AKCORE-60]: https://confluentinc.atlassian.net/browse/AKCORE-60?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Akcore 60 : Add unit tests for acknowledge function in Share Partition Manager

- group-coordinator/src/main/java/org/apache/kafka/coordinator/group/RecordSerde.java
- group-coordinator/src/main/resources/common/message/ShareCheckpointKey.json
- group-coordinator/src/main/resources/common/message/ShareCheckpointValue.json
- group-coordinator/src/main/resources/common/message/ShareDeltaKey.json
- group-coordinator/src/main/resources/common/message/ShareDeltaValue.json
- group-coordinator/src/main/resources/common/message/ShareGroupPartitionMetadataKey.json
- group-coordinator/src/main/resources/common/message/ShareGroupPartitionMetadataValue.json
- group-coordinator/src/test/java/org/apache/kafka/coordinator/group/RecordSerdeTest.java
* ShareGroupPartitionMetadata
* ShareCheckpoint
* ShareDelta
> AKCORE-91: Added schemas for various new data records.

- clients/src/test/java/org/apache/kafka/clients/consumer/internals/ShareFetchRequestManagerTest.java
*What*
Added couple of unit tests in ShareFetchRequestManagerTest.
> AKCORE-55: Added a unit test for ShareFetchRequestManager

- clients/src/main/java/org/apache/kafka/clients/consumer/internals/ShareCompletedFetch.java
- clients/src/test/java/org/apache/kafka/clients/consumer/internals/ShareCompletedFetchTest.java
- core/src/test/java/kafka/test/api/PlaintextShareConsumerTest.java
testConsumerCloseInGroupSequential was failing with a smaller number of records processed than expected. The reason was that the broker was returning a batch of records unaligned with the set of acquired records to the extent that the number of records to skip before finding an acquired record exceeded max.poll.records. The fetch collector was counting the number of records checked, rather than the number returned.
Adding a new unit test which would have caught the bug unearthed another bug to do with maintaining the next acquired record position, so that was fixed too.
> AKCORE-94: Fix flaky integration test

- core/src/main/java/kafka/server/SharePartition.java
- core/src/main/java/kafka/server/SharePartitionManager.java
- core/src/main/scala/kafka/server/BrokerServer.scala
- core/src/main/scala/kafka/server/KafkaConfig.scala
- core/src/test/java/kafka/server/SharePartitionManagerTest.java
- core/src/test/java/kafka/server/SharePartitionTest.java
- gradle/spotbugs-exclude.xml
- server/src/main/java/org/apache/kafka/server/config/Defaults.java
Added the record lock duration timeout config to brokers
> AKCORE-83: Handle lock timeout on messages in share partition (1/N)

- clients/src/main/java/org/apache/kafka/clients/consumer/AcknowledgementCommitCallback.java
Fixed the delinquent javadoc for AcknowledgementCommitCallback
> AKCORE-95: Fix javadoc for AcknowledgementCommitCallback

- clients/src/main/java/org/apache/kafka/clients/consumer/AcknowledgementCommitCallback.java
- clients/src/main/java/org/apache/kafka/clients/consumer/internals/AcknowledgementCommitCallbackHandler.java
- clients/src/main/java/org/apache/kafka/clients/consumer/internals/ShareMembershipManager.java
- clients/src/main/resources/common/message/DeleteShareGroupStateResponse.json
- clients/src/main/resources/common/message/InitializeShareGroupStateResponse.json
- clients/src/main/resources/common/message/ReadShareGroupOffsetsStateResponse.json
- clients/src/main/resources/common/message/ReadShareGroupStateResponse.json
- clients/src/main/resources/common/message/ShareAcknowledgeResponse.json
- clients/src/main/resources/common/message/ShareFetchResponse.json
- clients/src/main/resources/common/message/ShareGroupDescribeResponse.json
- clients/src/main/resources/common/message/ShareGroupHeartbeatResponse.json
- clients/src/main/resources/common/message/WriteShareGroupStateResponse.json
- clients/src/test/java/org/apache/kafka/clients/consumer/internals/AcknowledgementCommitCallbackHandlerTest.java
- clients/src/test/java/org/apache/kafka/clients/consumer/internals/ShareHeartbeatRequestManagerTest.java
- clients/src/test/java/org/apache/kafka/clients/consumer/internals/ShareMembershipManagerTest.java
- clients/src/test/java/org/apache/kafka/common/requests/RequestResponseTest.java
- core/src/test/scala/unit/kafka/server/ShareGroupHeartbeatRequestTest.scala
- group-coordinator/src/main/java/org/apache/kafka/coordinator/group/GroupMetadataManager.java
- group-coordinator/src/test/java/org/apache/kafka/coordinator/group/Assertions.java
- group-coordinator/src/test/java/org/apache/kafka/coordinator/group/GroupMetadataManagerTest.java
- tools/src/main/java/org/apache/kafka/tools/consumer/ConsoleShareConsumerOptions.java
Updated definitions to match KIP-932 v.59.
> AKCORE-108: Update definitions to match KIP-932 v.59

- clients/src/main/java/org/apache/kafka/clients/consumer/internals/ShareMembershipManager.java
- clients/src/test/java/org/apache/kafka/clients/consumer/internals/AcknowledgementCommitCallbackHandlerTest.java
*What*
Fix failing tests in upstream merge.
> AKCORE Merge Upstream : Fix failing tests 

- clients/src/main/java/org/apache/kafka/clients/consumer/internals/ShareConsumerImpl.java
- core/src/test/java/kafka/test/api/PlaintextShareConsumerTest.java
*What*
Added acknowledgment commit callback handler in ShareConsumerImpl::poll and added integration tests.
> AKCORE-101: Added acknowledgment commit callback handler in ShareConsumerImpl

- clients/src/main/java/org/apache/kafka/common/config/AbstractConfig.java
- clients/src/main/java/org/apache/kafka/common/utils/Utils.java
- clients/src/test/java/org/apache/kafka/common/config/AbstractConfigTest.java
- connect/mirror-client/src/main/java/org/apache/kafka/connect/mirror/MirrorClientConfig.java
- connect/runtime/src/main/java/org/apache/kafka/connect/runtime/WorkerConfig.java
- connect/runtime/src/test/java/org/apache/kafka/connect/runtime/WorkerTest.java
- core/src/main/scala/kafka/admin/BrokerApiVersionsCommand.scala
- core/src/main/scala/kafka/server/DynamicBrokerConfig.scala
- core/src/main/scala/kafka/server/KafkaConfig.scala
Signed-off-by: Greg Harris <greg.harris@aiven.io>
Reviewers: Chris Egerton <chrise@aiven.io>, Mickael Maison <mickael.maison@gmail.com>, Omnia G H Ibrahim <o.g.h.ibrahim@gmail.com>, Matthias J. Sax <matthias@confluent.io>
> MINOR: AbstractConfig cleanup (apache#15597) 

- clients/src/main/java/org/apache/kafka/common/config/AbstractConfig.java
- clients/src/main/java/org/apache/kafka/common/utils/Utils.java
- clients/src/test/java/org/apache/kafka/common/config/AbstractConfigTest.java
- connect/mirror-client/src/main/java/org/apache/kafka/connect/mirror/MirrorClientConfig.java
- connect/runtime/src/main/java/org/apache/kafka/connect/runtime/WorkerConfig.java
- connect/runtime/src/test/java/org/apache/kafka/connect/runtime/WorkerTest.java
- core/src/main/scala/kafka/admin/BrokerApiVersionsCommand.scala
- core/src/main/scala/kafka/server/DynamicBrokerConfig.scala
- core/src/main/scala/kafka/server/KafkaConfig.scala
Signed-off-by: Greg Harris <greg.harris@aiven.io>
Reviewers: Chris Egerton <chrise@aiven.io>, Mickael Maison <mickael.maison@gmail.com>, Omnia G H Ibrahim <o.g.h.ibrahim@gmail.com>, Matthias J. Sax <matthias@confluent.io>
> MINOR: AbstractConfig cleanup (#15597)

- clients/src/main/java/org/apache/kafka/clients/consumer/AcknowledgeType.java
- clients/src/main/java/org/apache/kafka/clients/consumer/AcknowledgementCommitCallback.java
- clients/src/main/java/org/apache/kafka/clients/consumer/KafkaShareConsumer.java
Proper javadoc for the external interfaces for KIP-932. The most significant part is a programming guide for KafkaShareConsumer.
> AKCORE-114: Javadoc for external interfaces

- clients/src/main/java/org/apache/kafka/clients/consumer/internals/ShareConsumerImpl.java
- core/src/test/java/kafka/test/api/PlaintextShareConsumerTest.java
KafkaShareConsumer.close also needs to call the acknowledgement commit callback.
Also tightened up and added tests.
> AKCORE-102: Call acknowledgement commit callback on close

- Vagrantfile
https://semaphore.ci.confluent.io/workflows/98e9c829-e4f7-4234-b881-dc4b471cae0a?pipeline_id=878dfc55-b218-426e-81a4-c9f385e944c8
> update tags and added seamphore tags as part of semaphore migration 2.8

- Vagrantfile
- tests/setup.py
https://semaphore.ci.confluent.io/workflows/7079f670-71f5-44cb-9482-042b5b1ce35f?pipeline_id=31c1bd05-02b4-4e2b-8da4-2079b7abf548
> update tags and added seamphore tags as part of semaphore migration 3.0

- Vagrantfile
- tests/setup.py
https://semaphore.ci.confluent.io/workflows/5d360733-764b-42c4-8004-28fc0a2b96ea?pipeline_id=e7b320e0-e5f6-4ed7-9a75-42c887f944a5
> update tags and added seamphore tags as part of semaphore migration 3.3

- Vagrantfile
https://semaphore.ci.confluent.io/workflows/bb22f709-e099-400b-9332-f3f100dea315?pipeline_id=009fc6b6-5f36-452c-a6ad-d8047beaf827
> update tags and added seamphore tags as part of semaphore migration 3.6

- Vagrantfile
- tests/setup.py
https://semaphore.ci.confluent.io/workflows/fd580413-bc50-46b7-b65c-0dce4f4caca8?pipeline_id=9311ca49-c7e8-48d5-929d-57c112701337
> update tags and added seamphore tags as part of semaphore migration 3.1

- Vagrantfile
- tests/setup.py
https://semaphore.ci.confluent.io/workflows/fbbd1cae-c408-4643-babc-7e18a5c39eef?pipeline_id=10f9d349-76da-49e6-82de-0041dcc18f95
> update tags and added seamphore tags as part of semaphore migration 3.2

- Vagrantfile
- tests/setup.py
https://semaphore.ci.confluent.io/workflows/7f33c7fc-f798-40b6-b2d4-b7203120851d?pipeline_id=74ed5da7-e14f-4682-bfd6-9c6ae141b71a
> update tags and added seamphore tags as part of semaphore migration 3.4

- Vagrantfile
- tests/setup.py
https://semaphore.ci.confluent.io/workflows/9afc20fb-47ab-40c7-89f8-b5031a3023fd?pipeline_id=c698e30b-e371-4e02-8b4a-c289c5dee9ae
> update tags and added seamphore tags as part of semaphore migration 3.5

- Vagrantfile
https://semaphore.ci.confluent.io/workflows/1b637cd3-6031-47dc-928b-4826c4159191?pipeline_id=fd0629f7-0f51-42b2-97e9-9719f47711fb
> update tags and added seamphore tags as part of semaphore migration 3.7

- service.yml
following steps for custom repo [here](https://confluentinc.atlassian.net/wiki/spaces/TOOLS/pages/3211693075/Jenkins+-+Semaphore+self+migration+guide#How-do-I-migrate-from-customized-job)
> add service.yml to run service bot (moving from jenkinsfile to semaphore)

- clients/src/main/java/org/apache/kafka/clients/consumer/internals/AcknowledgementCommitCallbackHandler.java
*What*
Modified acknowledgement callback handler to process all the acknowledgements fully and then return only the first exception.
> AKCORE-124: Modified callback handler to return only the first exception

- clients/src/main/java/org/apache/kafka/clients/consumer/KafkaShareConsumer.java
- clients/src/main/java/org/apache/kafka/clients/consumer/internals/ConsumerUtils.java
- clients/src/main/java/org/apache/kafka/clients/consumer/internals/ShareConsumerDelegate.java
- clients/src/main/java/org/apache/kafka/clients/consumer/internals/ShareConsumerImpl.java
- clients/src/main/java/org/apache/kafka/clients/consumer/internals/metrics/KafkaShareConsumerMetrics.java
- clients/src/test/java/org/apache/kafka/clients/consumer/KafkaShareConsumerMetricsTest.java
- clients/src/test/java/org/apache/kafka/clients/consumer/KafkaShareConsumerTest.java
*What*
Added KafkaShareConsumerMetrics and moved some tests to KafkaShareConsumerMetricsTest.
> AKCORE-125: Added KafkaShareConsumerMetrics and updated tests

- clients/src/main/java/org/apache/kafka/clients/consumer/internals/Acknowledgements.java
- clients/src/main/java/org/apache/kafka/clients/consumer/internals/ShareCompletedFetch.java
- clients/src/main/java/org/apache/kafka/clients/consumer/internals/ShareHeartbeatRequestManager.java
- clients/src/main/resources/common/message/ShareAcknowledgeRequest.json
- clients/src/main/resources/common/message/ShareFetchRequest.json
- clients/src/main/resources/common/message/ShareFetchResponse.json
- clients/src/main/resources/common/message/ShareGroupHeartbeatRequest.json
- clients/src/test/java/org/apache/kafka/clients/consumer/KafkaShareConsumerTest.java
- clients/src/test/java/org/apache/kafka/clients/consumer/internals/AcknowledgementsTest.java
- clients/src/test/java/org/apache/kafka/clients/consumer/internals/ShareCompletedFetchTest.java
- clients/src/test/java/org/apache/kafka/clients/consumer/internals/ShareConsumerTestBuilder.java
- clients/src/test/java/org/apache/kafka/clients/consumer/internals/ShareHeartbeatRequestManagerTest.java
- clients/src/test/java/org/apache/kafka/common/requests/RequestResponseTest.java
- core/src/main/java/kafka/server/SharePartition.java
- core/src/main/scala/kafka/server/KafkaApis.scala
- core/src/main/scala/kafka/server/KafkaConfig.scala
- core/src/test/java/kafka/server/SharePartitionManagerTest.java
- core/src/test/java/kafka/server/SharePartitionTest.java
- core/src/test/java/kafka/test/api/PlaintextShareConsumerTest.java
- core/src/test/scala/unit/kafka/server/KafkaApisTest.scala
- core/src/test/scala/unit/kafka/server/ShareGroupHeartbeatRequestTest.scala
- group-coordinator/src/main/java/org/apache/kafka/coordinator/group/GroupMetadataManager.java
- group-coordinator/src/main/java/org/apache/kafka/coordinator/group/share/ShareGroupMember.java
- group-coordinator/src/test/java/org/apache/kafka/coordinator/group/GroupMetadataManagerTest.java
- server/src/main/java/org/apache/kafka/server/config/Defaults.java
Update to KIP-932 v.70 definitions.
> AKCORE-113: Update code to match KIP-932

- clients/src/main/java/org/apache/kafka/clients/consumer/internals/ShareFetchRequestManager.java
*What*
Called handleAcknowledgementResponse in ShareFetchRequestManager::handleShareFetchFailure.
> AKCORE-139: Fixed bug in handleShareFetchFailure

- core/src/main/java/kafka/server/SharePartition.java
Minor refactor while printing InflightState and InflightBatch objects
> MINOR: InflightBatch and InflightState refactor for print - spaces and commas

- service.yml
https://confluent.slack.com/archives/C09EP1SS3/p1715355026704279?thread_ts=1715276889.073929&cid=C09EP1SS3
changed to only allow a more specific path
> changed package paths for codeartifact

- clients/src/main/java/org/apache/kafka/clients/consumer/internals/AsyncKafkaConsumer.java
- clients/src/main/java/org/apache/kafka/clients/consumer/internals/ConsumerUtils.java
- clients/src/main/java/org/apache/kafka/clients/consumer/internals/FetchMetricsAggregator.java
- clients/src/main/java/org/apache/kafka/clients/consumer/internals/NetworkClientDelegate.java
- clients/src/main/java/org/apache/kafka/clients/consumer/internals/RequestManagers.java
- clients/src/main/java/org/apache/kafka/clients/consumer/internals/ShareCompletedFetch.java
- clients/src/main/java/org/apache/kafka/clients/consumer/internals/ShareConsumerImpl.java
- clients/src/main/java/org/apache/kafka/clients/consumer/internals/ShareConsumerMetrics.java
- clients/src/main/java/org/apache/kafka/clients/consumer/internals/ShareFetchMetricsAggregator.java
- clients/src/main/java/org/apache/kafka/clients/consumer/internals/ShareFetchMetricsManager.java
- clients/src/main/java/org/apache/kafka/clients/consumer/internals/ShareFetchMetricsRegistry.java
- clients/src/main/java/org/apache/kafka/clients/consumer/internals/ShareFetchRequestManager.java
- clients/src/test/java/org/apache/kafka/clients/consumer/internals/ShareCompletedFetchTest.java
- clients/src/test/java/org/apache/kafka/clients/consumer/internals/ShareConsumerTestBuilder.java
- clients/src/test/java/org/apache/kafka/clients/consumer/internals/ShareFetchBufferTest.java
- clients/src/test/java/org/apache/kafka/clients/consumer/internals/ShareFetchCollectorTest.java
- clients/src/test/java/org/apache/kafka/clients/consumer/internals/ShareFetchMetricsManagerTest.java
- clients/src/test/java/org/apache/kafka/clients/consumer/internals/ShareFetchRequestManagerTest.java
*What*
Implemented share-consumer-fetch-manager-metrics listed in the KIP.
The Acknowledgement metrics are yet to be recorded in this PR. They will be implemented after the revised ShareFetchRequestManager is pushed.
> AKCORE-144: Implemented share-consumer-fetch-manager-metrics

- service.yml
adds the correct paths to codeartifact
> added specific paths to code artifact

- clients/src/main/java/org/apache/kafka/clients/consumer/internals/ShareFetchMetricsAggregator.java
- clients/src/test/java/org/apache/kafka/clients/consumer/internals/ShareCompletedFetchTest.java
- clients/src/test/java/org/apache/kafka/clients/consumer/internals/ShareFetchCollectorTest.java
*What*
Minor change while initializing Set<TopicPartition> in `ShareFetchMetricsAggregator.`
> AKCORE-150: Minor change in ShareFetchMetricsAggregator

- clients/src/main/java/org/apache/kafka/clients/consumer/internals/ConsumerUtils.java
- clients/src/main/java/org/apache/kafka/clients/consumer/internals/ShareConsumerImpl.java
- clients/src/main/java/org/apache/kafka/clients/consumer/internals/ShareFetchBuffer.java
- clients/src/main/java/org/apache/kafka/clients/consumer/internals/ShareFetchRequestManager.java
- clients/src/main/java/org/apache/kafka/clients/consumer/internals/ShareHeartbeatRequestManager.java
- clients/src/main/java/org/apache/kafka/clients/consumer/internals/metrics/ShareRebalanceMetricsManager.java
- clients/src/test/java/org/apache/kafka/clients/consumer/KafkaShareConsumerMetricsTest.java
- clients/src/test/java/org/apache/kafka/clients/consumer/internals/ShareFetchMetricsManagerTest.java
- clients/src/test/java/org/apache/kafka/clients/consumer/internals/ShareFetchRequestManagerTest.java
- clients/src/test/java/org/apache/kafka/clients/consumer/internals/ShareHeartbeatRequestManagerTest.java
- clients/src/test/java/org/apache/kafka/clients/consumer/internals/ShareMembershipManagerTest.java
- clients/src/test/java/org/apache/kafka/clients/consumer/internals/metrics/HeartbeatMetricsManagerTest.java
*What*
Updated metric names according to the KIP and added logic to record acknowledgement metrics in ShareFetchRequestManager.
> AKCORE-151: Updated metric names and added logic to record acknowledgement metrics

- checkstyle/import-control.xml
- core/src/main/scala/kafka/server/BrokerServer.scala
- core/src/main/scala/kafka/server/metadata/BrokerMetadataPublisher.scala
- core/src/test/scala/unit/kafka/server/metadata/BrokerMetadataPublisherTest.scala
- group-coordinator/src/main/java/org/apache/kafka/coordinator/group/share/ShareCoordinator.java
- group-coordinator/src/main/java/org/apache/kafka/coordinator/group/share/ShareCoordinatorMetrics.java
- group-coordinator/src/main/java/org/apache/kafka/coordinator/group/share/ShareCoordinatorMetricsShard.java
- group-coordinator/src/main/java/org/apache/kafka/coordinator/group/share/ShareCoordinatorRuntimeMetrics.java
- group-coordinator/src/main/java/org/apache/kafka/coordinator/group/share/ShareCoordinatorService.java
- group-coordinator/src/main/java/org/apache/kafka/coordinator/group/share/ShareCoordinatorShard.java
- server/src/main/java/org/apache/kafka/server/config/Defaults.java
* Added builder for `ShareCoordinatorService`.
* Added `ShareCoordinatorShard` class with builders.
* Added lifecycle methods for SCR in `BrokerServer`.
* Added placeholder metrics classes for coordinator, coordinator runtime and metrics shard.
* SCR startup and shutdown in `BrokerMetadataPublisher` and `BrokerServer` respectively.
> AKCORE-145: Added builders and support classes for SCR.

- checkstyle/import-control.xml
- core/src/main/java/kafka/server/SharePartitionManager.java
- core/src/main/scala/kafka/server/BrokerServer.scala
- core/src/test/java/kafka/server/SharePartitionManagerTest.java
- core/src/test/scala/unit/kafka/server/KafkaApisTest.scala
- server-common/src/main/java/org/apache/kafka/server/group/share/DefaultStatePersister.java
- server-common/src/main/java/org/apache/kafka/server/group/share/NoOpShareStatePersister.java
- server-common/src/main/java/org/apache/kafka/server/group/share/Persister.java
- server-common/src/main/java/org/apache/kafka/server/group/share/PersisterConfig.java
- server-common/src/main/java/org/apache/kafka/server/group/share/PersisterStateManager.java
- server/src/main/java/org/apache/kafka/server/config/Defaults.java
* Find coordinator RPC impl for share group CRUD RPCs.
* Added PersisterStateManager to handle RPCs.
* Added PersisterConfig class to supply config for Persister.
* Updated Persister interface to add `stop` and `configure` methods.
* Updated broker server which now instantiates and manages the persister instance creation and pass it to appropriate classes.
Major update:
__share_group_state topic is getting created if not exisiting
> AKCORE-152: Added code for find coord invocation.

- checkstyle/import-control.xml
- core/src/main/scala/kafka/server/BrokerServer.scala
- core/src/main/scala/kafka/server/metadata/BrokerMetadataPublisher.scala
- group-coordinator/src/main/java/org/apache/kafka/coordinator/group/RecordHelpers.java
- group-coordinator/src/main/java/org/apache/kafka/coordinator/group/RecordSerde.java
- group-coordinator/src/main/java/org/apache/kafka/coordinator/group/share/GroupTopicPartitionLeader.java
- group-coordinator/src/main/java/org/apache/kafka/coordinator/group/share/ShareCoordinator.java
- group-coordinator/src/main/java/org/apache/kafka/coordinator/group/share/ShareCoordinatorService.java
- group-coordinator/src/main/java/org/apache/kafka/coordinator/group/share/ShareCoordinatorShard.java
- group-coordinator/src/main/java/org/apache/kafka/coordinator/group/share/ShareGroupOffset.java
- group-coordinator/src/main/java/org/apache/kafka/coordinator/group/share/ShareRecordSerde.java
- group-coordinator/src/main/resources/common/message/ShareSnapshotValue.json
- group-coordinator/src/main/resources/common/message/ShareUpdateValue.json
- server-common/src/main/java/org/apache/kafka/server/group/share/DefaultStatePersister.java
- server-common/src/main/java/org/apache/kafka/server/group/share/PersisterStateManager.java
- server-common/src/main/java/org/apache/kafka/server/group/share/ShareGroupHelper.java
* Code to create ShareSnapshot type records.
* Update PersisterStateManager main handler.
* Add lifecycle methods in ShareCoordinator.
* Create timelinehashmaps in ShareCoordinatorShard to store soft state.
> Common code to support read and write RPC.

- clients/src/main/java/org/apache/kafka/clients/consumer/internals/RequestManagers.java
- clients/src/main/java/org/apache/kafka/clients/consumer/internals/ShareConsumeRequestManager.java
- clients/src/main/java/org/apache/kafka/clients/consumer/internals/ShareSessionHandler.java
- clients/src/test/java/org/apache/kafka/clients/consumer/internals/ShareConsumeRequestManagerTest.java
- clients/src/test/java/org/apache/kafka/clients/consumer/internals/ShareConsumerTestBuilder.java
*What*
Updated commitSync() logic. Now the ShareAcknowledgeRequests will be built inside the poll() of the ShareConsumeRequestManager.
> AKCORE-181: Updated commitSync() logic

- group-coordinator/src/main/java/org/apache/kafka/coordinator/group/share/ShareCoordinatorShard.java
- server-common/src/main/java/org/apache/kafka/server/group/share/DefaultStatePersister.java
- server-common/src/main/java/org/apache/kafka/server/group/share/GroupTopicPartitionData.java
- server-common/src/main/java/org/apache/kafka/server/group/share/Persister.java
* Added code to validate the arguments for persister interface and its impls.
* If the arguments fail sanity checks, an exception is thrown and no RPC is issued.
> AKCORE-196: Added client side validations for share state RPCs.

- clients/src/main/java/org/apache/kafka/clients/consumer/internals/AcknowledgementBatch.java
- clients/src/main/java/org/apache/kafka/clients/consumer/internals/Acknowledgements.java
- clients/src/main/java/org/apache/kafka/clients/consumer/internals/ShareSessionHandler.java
- clients/src/test/java/org/apache/kafka/clients/consumer/internals/AcknowledgementsTest.java
*What*
Optimised use of acknowledgement batch in Acknowledgements.
> AKCORE-175: Optimised use of acknowledgement batch

- clients/src/main/java/org/apache/kafka/clients/consumer/internals/ShareConsumerImpl.java
- core/src/test/java/kafka/test/api/ShareConsumerTest.java
*What*
Updated Acknowledgement Mode handling in ShareConsumer.
> AKCORE-213 : Updated acknowledgement state handling in ShareConsumer

- .semaphore/semaphore.yml
Removed vault references from semaphore
> removed vault secrets

- .semaphore/semaphore.yml
Do not depend on vault on public CI
- [ x] Verify design and implementation 
- [ x] Verify test coverage and CI build status
- [ x] Verify documentation (including upgrade notes)
> do not depend on vault on public CI

- core/src/main/java/kafka/server/SharePartitionManager.java
- core/src/main/java/kafka/server/ShareSessionContext.java
Investigated thread safety for share session cache and found these places in the code where we should have synchronized access.
> AKCORE-215: Synchronized cache and share sessions wherever found missing

- clients/src/main/java/org/apache/kafka/common/requests/WriteShareGroupStateResponse.java
- group-coordinator/src/main/java/org/apache/kafka/coordinator/group/share/ShareCoordinatorShard.java
- group-coordinator/src/test/java/org/apache/kafka/coordinator/group/share/ShareCoordinatorConfigTest.java
- group-coordinator/src/test/java/org/apache/kafka/coordinator/group/share/ShareCoordinatorServiceTest.java
- group-coordinator/src/test/java/org/apache/kafka/coordinator/group/share/ShareCoordinatorShardTest.java
- server-common/src/main/java/org/apache/kafka/server/group/share/PersisterStateManager.java
- server-common/src/test/java/org/apache/kafka/server/group/share/DefaultStatePersisterTest.java
- server-common/src/test/java/org/apache/kafka/server/group/share/PersisterStateManagerTest.java
This PR includes unit tests in the following files - 
- ShareCoordinatorConfigTest.java
- DefaultStatePersisterTest.java
- PersisterStateManagerTest.java
- ShareCoordinatorServiceTest.java
- ShareCoordinatorShardTest.java
Reference - [AKCORE-185](https://confluentinc.atlassian.net/jira/software/c/projects/AKCORE/issues/AKCORE-185?jql=project%20%3D%20%22AKCORE%22%20ORDER%20BY%20created%20DESC)
[AKCORE-185]: https://confluentinc.atlassian.net/browse/AKCORE-185?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> AKCORE-185: Added unit tests for WriteShareGroupState and ReadShareGroupState APIs

- clients/src/main/java/org/apache/kafka/clients/consumer/internals/Acknowledgements.java
- clients/src/main/java/org/apache/kafka/clients/consumer/internals/ShareConsumeRequestManager.java
- clients/src/main/java/org/apache/kafka/clients/consumer/internals/ShareConsumerImpl.java
- clients/src/main/java/org/apache/kafka/clients/consumer/internals/ShareFetch.java
- clients/src/main/java/org/apache/kafka/clients/consumer/internals/ShareFetchCollector.java
- clients/src/main/java/org/apache/kafka/clients/consumer/internals/ShareInFlightBatch.java
- clients/src/test/java/org/apache/kafka/clients/consumer/internals/ShareCompletedFetchTest.java
- core/src/test/java/kafka/test/api/ShareConsumerTest.java
Handle situations in which the application only acknowledges a subset of the records returns on a poll. Also, some refactoring to improve code structure.
> AKCORE-214: Handle partially acknowledged batches

- clients/src/main/java/org/apache/kafka/clients/consumer/internals/ShareConsumeRequestManager.java
*What*
Optimised the number of background events sent by ShareConsumeRequestManager
> AKCORE-216 : Updated CommitResultHandler to send background event

- checkstyle/import-control.xml
- group-coordinator/src/main/java/org/apache/kafka/coordinator/group/GroupMetadataManager.java
- group-coordinator/src/main/java/org/apache/kafka/coordinator/group/metrics/GroupCoordinatorMetrics.java
- group-coordinator/src/main/java/org/apache/kafka/coordinator/group/metrics/GroupCoordinatorMetricsShard.java
- group-coordinator/src/test/java/org/apache/kafka/coordinator/group/GroupMetadataManagerTest.java
* Added rebalance count and rate metric
* num-partitions metric in group group-coordinator-metrics removed as discussed in https://confluent.slack.com/archives/C06E4G1KHDJ/p1719388029303499
> AKCORE-184: Added rebalance count and rate metrics [3/N]

- server-common/src/main/java/org/apache/kafka/server/group/share/DefaultStatePersister.java
- server-common/src/main/java/org/apache/kafka/server/group/share/PersisterStateManager.java
* Changed log level for verbose logs in share state RPC client side (DefaultStatePersister, PersisterStateManager).
> MINOR: Changed level for share RPC client side logs.

- core/src/test/scala/unit/kafka/utils/TestUtils.scala
Fix compilation failures due to upstream change : https://github.com/apache/kafka/pull/16464
> MINOR: Fix compilation error in TestUtils.getBrokerListStrFromServers

- clients/src/main/java/org/apache/kafka/clients/consumer/internals/RequestManagers.java
- clients/src/main/java/org/apache/kafka/clients/consumer/internals/ShareConsumeRequestManager.java
- clients/src/main/java/org/apache/kafka/clients/consumer/internals/events/ApplicationEventProcessor.java
- clients/src/test/java/org/apache/kafka/clients/consumer/internals/ShareConsumeRequestManagerTest.java
- clients/src/test/java/org/apache/kafka/clients/consumer/internals/ShareConsumerTestBuilder.java
Refactored events to match changes in Apache Kafka.
> AKCORE-233: Refactor event timeout code

- clients/src/main/java/org/apache/kafka/clients/consumer/internals/TimedRequestState.java
> AKCORE-236: Add missing TimedRequestState class

- .gitignore
- .semaphore/semaphore.yml
- Makefile
> [master] removes mk-include

- clients/src/main/java/org/apache/kafka/clients/consumer/internals/ShareConsumeRequestManager.java
If a share session existed but all delivered records had been acknowledged, the final ShareAcknowledge (which is empty) was not being sent. This means the share session was not closed, and the acquired record locks needed to time out before being available for another client.
The area of in-flight acknowledgements which need to be completed during closing of a consumer needs to be reworked, but this code change should be sufficient to get the performance tests working more smoothly.
> AKCORE-241: Make sure share sessions are closed in all situations

- core/src/test/java/kafka/test/api/ShareConsumerTest.java
* As a result of using `DefaultStatePersister`, when the first poll request is made by a share consumer there is some latency to create the internal topic SGS and load the coordinator.
* This messes up the timing info specified in the poll requests. However, this should not be a problem in production.
* To counter this, this PR adds a `warmup` method which creates a test topic and produces a single record into it. Then a share consumer polls the topic and as a side effect causes creation of SGS and coordinator shard load.
* This helps in assertions on subsequent polls.
> MINOR: Added warmup to tests to mitigate initial poll delay.

- core/src/main/java/kafka/server/SharePartitionManager.java
- core/src/test/java/kafka/server/SharePartitionManagerTest.java
- group-coordinator/src/main/java/org/apache/kafka/coordinator/group/share/ShareCoordinatorMetrics.java
- group-coordinator/src/test/java/org/apache/kafka/coordinator/group/share/ShareCoordinatorServiceTest.java
* Renamed write-latency-total to write-latency-max and updated that stat from cumulative-sum to max.
* Updated some incorrect descriptions.
* Updated tests.
> AKCORE-184: Incorporate metrics changes in kip-932 [5/N].
