- stream/src/main/java/org/apache/kafka/streaming/processor/TopologyBuilder.java
- stream/src/main/java/org/apache/kafka/streaming/processor/internals/ProcessorNode.java
- stream/src/main/java/org/apache/kafka/streaming/processor/internals/ProcessorTopology.java
- stream/src/main/java/org/apache/kafka/streaming/processor/internals/SinkNode.java
@guozhangwang 
Simpler topology construction by taking an advantage that sources/sinks/processors are always added in a topological order. Processor nodes are constructed in the same order as API calls (addSource, addSink, addProcessor). I will use this guarantee in the join support.
> refactor TopologyBuilder

- stream/src/main/java/org/apache/kafka/streaming/kstream/internals/KStreamJoin.java
@guozhangwang 
actually use context.joinable() and remove unnecessary imports.
> cleanup KStreamJoin

- stream/src/main/java/org/apache/kafka/streaming/KafkaStreaming.java
- stream/src/main/java/org/apache/kafka/streaming/kstream/internals/KStreamJoin.java
- stream/src/main/java/org/apache/kafka/streaming/kstream/internals/KStreamWindowedImpl.java
@guozhangwang This is a bit cleaner, I guess.
> Simplified join processor

- stream/src/main/java/org/apache/kafka/streaming/processor/internals/RecordCollector.java
- stream/src/main/java/org/apache/kafka/streaming/processor/internals/StreamTask.java
@guozhangwang 
Callers know which serializers to use and always specify them explicitly.
> no need for RecordCollector to know default serializers

- stream/src/main/java/org/apache/kafka/streaming/processor/TopologyBuilder.java
Since the methods returned `void` before, this change has no impact on existing code.
> TopologyBuilder methods return the builder to allow methods to be chained together.

- build.gradle
Modified the `build.gradle` file's configuration for the 'stream' project to include the test JAR when uploading artifacts into Maven. Without these minor changes, the stream project's normal JAR and source JAR are uploaded to Maven, but the test JAR never is.
> Streaming build fix

- streams/src/main/java/org/apache/kafka/streams/processor/internals/ProcessorContextImpl.java
- streams/src/main/java/org/apache/kafka/streams/processor/internals/PunctuationSchedule.java
- streams/src/main/java/org/apache/kafka/streams/processor/internals/Punctuator.java
- streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java
- streams/src/test/java/org/apache/kafka/streams/processor/internals/PunctuationQueueTest.java
@guozhangwang 
* moved the node stack operation from ProcessorContextImpl to StreamTask.
* made sure that punctuation set the current node correctly and clear it afterwards.
> hide node stack in streamtask

- streams/src/main/java/org/apache/kafka/streams/examples/WallclockTimestampExtractor.java
- streams/src/main/java/org/apache/kafka/streams/processor/TimestampExtractor.java
- streams/src/main/java/org/apache/kafka/streams/processor/internals/RecordQueue.java
- streams/src/test/java/org/apache/kafka/test/MockTimestampExtractor.java
@guozhangwang 
Changed the signature of TimestampExtractor.extract(). Now it takes a ConsumerRecord instance. ConsumerRecord can provide more information to TimestampExtractor. Once KIP-32 is implemented, and the createTime and logAppendTime is exposed to a consumer,I expect it will be done through ConsumerRecord.
> change timestampextractor signature

- streams/src/main/java/org/apache/kafka/streams/processor/TopologyBuilder.java
- streams/src/main/java/org/apache/kafka/streams/processor/TopologyException.java
- streams/src/main/java/org/apache/kafka/streams/processor/internals/ProcessorTopology.java
- streams/src/test/java/org/apache/kafka/streams/processor/TopologyBuilderTest.java
- streams/src/test/java/org/apache/kafka/streams/processor/internals/ProcessorTopologyTest.java
- streams/src/test/java/org/apache/kafka/streams/processor/internals/StreamTaskTest.java
@ymatsuda 
1. Enforce unique topic names in sinks.
2. Du-duplicate sink / source nodes in sources() / sinks().
> ProcessorTopology unit tests

- streams/src/main/java/org/apache/kafka/streams/processor/internals/ProcessorStateManager.java
- streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java
- streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamThread.java
- streams/src/test/java/org/apache/kafka/streams/processor/internals/StreamTaskTest.java
@guozhangwang 
The current implementation of StreamThread.maybeClean() is a nasty time bomb. It destroys local state after the cleanup delay time.
StreamThread cleans up unused state directories after the cleanup delay time. But it knows only the tasks assigned to it. It means it deletes any task directory that does not belong to itself. Thus the threads destroys each other's local state. :(
To solve this, I added a lock file to each state directory as protection. ProcessorStateManager acquires this lock. maybeClean() also tries to acquire this lock before cleaning up the directory. If successful, it can clean the directory, otherwise, skip it. This works when there are multiple instance of KafkaStreaming running either in the same JVM or different JVMs. 
I also added a code to reset …
> fix state directory cleanup

- streams/src/main/java/org/apache/kafka/streams/KafkaStreaming.java
This issue causes the JavaDoc creation for streaming to fail.
> The greater than cannot be used in JavaDoc.

- streams/src/main/java/org/apache/kafka/streams/KafkaStreaming.java
- streams/src/main/java/org/apache/kafka/streams/examples/KStreamJob.java
- streams/src/main/java/org/apache/kafka/streams/examples/ProcessorJob.java
- streams/src/main/java/org/apache/kafka/streams/kstream/KStream.java
- streams/src/main/java/org/apache/kafka/streams/kstream/internals/KStreamImpl.java
- streams/src/test/java/org/apache/kafka/streams/kstream/KStreamBuilderTest.java
- streams/src/test/java/org/apache/kafka/streams/kstream/internals/KStreamImplTest.java
@ymatsuda 
Also I am thinking if we can rename KStream.sendTo() to just KStream.to(), which is more symmetric to builder.from().
> Add unit tests for KStreamImpl

- streams/src/main/java/org/apache/kafka/streams/processor/internals/ProcessorContextImpl.java
- streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java
> move statemgr construction to streamtask

- build.gradle
- streams/src/main/java/org/apache/kafka/streams/kstream/KStream.java
- streams/src/main/java/org/apache/kafka/streams/kstream/internals/KStreamFlatMapValues.java
- streams/src/main/java/org/apache/kafka/streams/kstream/internals/KStreamImpl.java
> More comments addressed

- streams/src/main/java/org/apache/kafka/streams/state/InMemoryKeyValueStore.java
- streams/src/main/java/org/apache/kafka/streams/state/KeyValueStore.java
- streams/src/main/java/org/apache/kafka/streams/state/MeteredKeyValueStore.java
- streams/src/main/java/org/apache/kafka/streams/state/RocksDBKeyValueStore.java
@ymatsuda 
Currently the delete() call does not really remove the key-value pair in the tree map, making it not feasible with nullable values, and also takes unnecessary memory usage.
> Fix delete in in-memory store, and let delete return old value

- streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java
@guozhangwang 
Since a change log is a redo log, it makes sense to flush it before flushing the state store to a local disk.
> flush records and state changelog before local state

- streams/src/main/java/org/apache/kafka/streams/kstream/Windowed.java
Author: Ewen Cheslack-Postava <me@ewencp.org>
> HOTFIX: Fix checkstyle failure in KStreams by providing fully qualified class names

- streams/src/main/java/org/apache/kafka/streams/StreamsConfig.java
- streams/src/test/java/org/apache/kafka/streams/StreamsConfigTest.java
Enable user provided consumer and producer configs to override the streams default configs.
Author: Damian Guy <damian.guy@gmail.com>
Reviewers: Eno Thereska, Matthias J. Sax, Guozhang Wang
Closes #2084 from dguy/kafka-4361
> KAFKA-4361: Streams does not respect user configs for "default" params

- checkstyle/import-control.xml
- clients/src/main/java/org/apache/kafka/clients/producer/internals/RecordBatch.java
- clients/src/main/java/org/apache/kafka/common/record/MemoryRecordsBuilder.java
This enables the import-control checks to go untouched.
> Remove dependence of MemoryRecordsBuilder on TransactionState

- streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java
- streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamThread.java
- streams/src/test/java/org/apache/kafka/streams/processor/internals/StreamThreadTest.java
1. Capture `CommitFailedException` in `StreamThread#suspendTasksAndState`; also fix log4j outputs for error and warn.
2. Minor fixes on `StreamTask` class for comments alignment etc.
> Handle commit failed exception on stream thread

- checkstyle/suppressions.xml
- clients/src/main/java/org/apache/kafka/clients/producer/KafkaProducer.java
- clients/src/main/java/org/apache/kafka/clients/producer/ProducerConfig.java
- clients/src/main/java/org/apache/kafka/clients/producer/internals/ProducerBatch.java
- clients/src/main/java/org/apache/kafka/clients/producer/internals/RecordAccumulator.java
- clients/src/main/java/org/apache/kafka/clients/producer/internals/Sender.java
- clients/src/test/java/org/apache/kafka/clients/producer/KafkaProducerTest.java
- clients/src/test/java/org/apache/kafka/clients/producer/internals/SenderTest.java
- clients/src/test/java/org/apache/kafka/clients/producer/internals/TransactionManagerTest.java
We solve the problem of expired batches not being retried by providing the a separate config `batch.expiry.ms` which controls how long to wait before batches are expired. Before this patch, we would expire batches once `request.timeout.ms` elapsed. By setting the new config to be very high, we ensure that batches are never expired, which has the same effect as being retried indefinitely.
> CPKAFKA-1054 : introduce batch expiry config

- clients/src/main/java/org/apache/kafka/clients/producer/KafkaProducer.java
- clients/src/main/java/org/apache/kafka/clients/producer/ProducerConfig.java
- clients/src/main/java/org/apache/kafka/clients/producer/internals/ProducerBatch.java
- clients/src/main/java/org/apache/kafka/clients/producer/internals/RecordAccumulator.java
- clients/src/main/java/org/apache/kafka/clients/producer/internals/Sender.java
- clients/src/test/java/org/apache/kafka/clients/producer/KafkaProducerTest.java
- clients/src/test/java/org/apache/kafka/clients/producer/internals/SenderTest.java
- clients/src/test/java/org/apache/kafka/clients/producer/internals/TransactionManagerTest.java
This is a cherry-pick from 0.11.0 to 1.0 as KIP-91 will
only land in 1.1.0 or later. We should not merge this
to trunk.
We solve the problem of expired batches not being retried
by providing the a separate config `confluent.batch.expiry.ms`
which controls how long to wait before batches are expired.
Before this patch, we would expire batches once
`request.timeout.ms` elapsed. By setting the new config
value to be very high, we ensure that batches are never expired,
which has the same effect as being retried indefinitely.
> CPKAFKA-1054: Introduce batch expiry config

- build.gradle
- support-metrics-common/src/test/java/io/confluent/support/metrics/common/FilterTest.java
Fix a bug where support-metrics-common tests could sometimes not find
the definition of the IntegrationTest annotation.
Fix a bug where FilterTest was using Properties#contains where
Properties#containsKey was appropriate.
> CONFLUENT: some support-metrics-common test fixes

- tests/kafkatest/services/kafka/kafka.py
System tests in https://jenkins.confluent.io/job/system-test-kafka/job/master/ have been failing. Most of the failures are because of a port conflict for `JmxMixin`. This is because of a leak from an earlier test where `KafkaService` startup raises an exception, preventing cleanup of `JmxMixin` which causes all other tests that use `JmxMixin` to fail with a port conflict.
With the change to integrate support metrics in this repo, we should now expect the main class to be `SupportedKafka` instead of `kafka.Kafka`. This fix will address the startup failure.
Kicked off build with fix: https://jenkins.confluent.io/job/system-test-kafka-branch-builder/2549/
> CONFLUENT: Expect SupportedKafka as the classname in system tests

- clients/src/main/java/org/apache/kafka/common/network/Selector.java
- clients/src/main/java/org/apache/kafka/common/network/SslTransportLayer.java
- clients/src/test/java/org/apache/kafka/common/network/SelectorTest.java
- clients/src/test/java/org/apache/kafka/common/network/SslSelectorTest.java
- clients/src/test/java/org/apache/kafka/common/network/SslTransportLayerTest.java
- core/src/main/scala/kafka/network/SocketServer.scala
- core/src/test/scala/unit/kafka/network/SocketServerTest.scala
- KAFKA-3702: Change log level of SSL close_notify failure (apache#5397)
- KAFKA-7454: Use lazy allocation for SslTransportLayer buffers
- KAFKA-7453: Expire registered channels not selected within idle timeout
- KAFKA-7304: Limit connection accept rate to prioritize other channels
- Other small fixes incorporated in #181
> 4.1.1 Hotfix for SSL connection-related issues

- build.gradle
This has 2 benefits:
- Avoid the `core` dependency that is not needed by most projects.
They typically only care about `ConfluentSubmitter`.
- Workaround a bug where any Java project depending on `core`
ends up overwriting the core dependency to have the Scala version
from the last build. That is, if you build 2.12 and then 2.11,
the pom for the Java project will depend on `kafka_2.11`.
> CONFLUENT: support-metrics should use compileOnly for `core` dependency

- clients/src/main/java/org/apache/kafka/clients/consumer/internals/Fetcher.java
- clients/src/main/java/org/apache/kafka/common/record/ByteBufferLogInputStream.java
- clients/src/main/java/org/apache/kafka/common/record/MemoryRecords.java
- clients/src/test/java/org/apache/kafka/clients/consumer/internals/FetcherTest.java
- clients/src/test/java/org/apache/kafka/common/record/MemoryRecordsTest.java
- core/src/main/scala/kafka/coordinator/group/GroupMetadataManager.scala
- core/src/main/scala/kafka/log/LogCleaner.scala
- core/src/main/scala/kafka/log/ProducerStateManager.scala
- core/src/main/scala/kafka/tools/DumpLogSegments.scala
- core/src/test/scala/unit/kafka/coordinator/group/GroupMetadataManagerTest.scala
- core/src/test/scala/unit/kafka/log/LogCleanerTest.scala
- core/src/test/scala/unit/kafka/log/ProducerStateManagerTest.scala
This hotfix includes backports of two bugs related to Log Cleaner:
* [KAFKA-6834](https://issues.apache.org/jira/browse/KAFKA-6834) Log cleaner fails when encountering a message large than `max.message.bytes`
* [KAFKA-7467](https://issues.apache.org/jira/browse/KAFKA-7467) NoSuchElementException is raised because controlBatch is empty
> Hotfix for 4.1.1

- config/server.properties
- config/zookeeper.properties
- streams/src/main/java/org/apache/kafka/streams/StreamsConfig.java
This reverts the changes done in: https://github.com/confluentinc/kafka/commit/e5a6ed3471efa501e3ea96b2302447a10d43b137
> CONFLUENT: Change default dir paths from /var/lib to /tmp

- bin/kafka-run-class.sh
- bin/windows/kafka-run-class.bat
- clients/src/main/java/org/apache/kafka/clients/admin/KafkaAdminClient.java
- clients/src/main/java/org/apache/kafka/clients/producer/RoundRobinPartitioner.java
- clients/src/main/java/org/apache/kafka/common/protocol/ApiKeys.java
- clients/src/main/java/org/apache/kafka/common/protocol/types/Struct.java
- clients/src/main/java/org/apache/kafka/common/requests/AbstractResponse.java
- clients/src/main/java/org/apache/kafka/common/requests/ExpireDelegationTokenRequest.java
- clients/src/main/java/org/apache/kafka/common/requests/ExpireDelegationTokenResponse.java
- clients/src/test/java/org/apache/kafka/clients/producer/RoundRobinPartitionerTest.java
- clients/src/test/java/org/apache/kafka/common/requests/RequestResponseTest.java
- core/src/main/scala/kafka/server/KafkaApis.scala
- core/src/test/scala/unit/kafka/server/RequestQuotaTest.scala
- gradle.properties
- gradle/dependencies.gradle
- streams/src/main/java/org/apache/kafka/streams/kstream/internals/metrics/Sensors.java
- streams/src/main/java/org/apache/kafka/streams/processor/internals/ProcessorNode.java
- streams/src/main/java/org/apache/kafka/streams/processor/internals/metrics/StreamsMetricsImpl.java
- streams/src/main/java/org/apache/kafka/streams/processor/internals/metrics/ThreadMetrics.java
- streams/src/main/java/org/apache/kafka/streams/state/internals/AbstractRocksDBSegmentedBytesStore.java
- streams/src/main/java/org/apache/kafka/streams/state/internals/InMemorySessionStore.java
- streams/src/main/java/org/apache/kafka/streams/state/internals/InMemoryWindowStore.java
- streams/src/main/java/org/apache/kafka/streams/state/internals/NamedCache.java
- streams/src/main/java/org/apache/kafka/streams/state/internals/ThreadCache.java
- streams/src/main/java/org/apache/kafka/streams/state/internals/metrics/Sensors.java
- streams/src/test/java/org/apache/kafka/streams/processor/internals/metrics/StreamsMetricsImplTest.java
- streams/src/test/java/org/apache/kafka/streams/processor/internals/metrics/ThreadMetricsTest.java
- support-metrics-client/src/test/java/io/confluent/support/metrics/collectors/BasicCollectorTest.java
The avro upgrade was needed to fix the following error during
':support-metrics-client:generateAvro':
> Caused by: org.apache.velocity.exception.MethodInvocationException: Variable $velocityCount has not been set at ...
Conflicts:
* gradle.properties -> trivial fix, `scalaVersion` is next to `version`, which
is different in ccs kafka
* gradle/dependencies.gradle -> removed unused `httpclient` and `httpmime` in
the `versions` array since they were unused and were the reason for the
divergence with upstream.
> Sync from apache/kafka (8 August 2019) and upgrade avro to 1.9.0

- Jenkinsfile
The Jenkinsfile uses `env.CHANGE_FORK` in PR builds, which is not set when a PR is opened from the `confluentinc` fork:
```[Pipeline] echo
17:06:23  Schedule test-cp-downstream-builds with :
[Pipeline] echo
17:06:23  Muckrake branch : 5.3.x
[Pipeline] echo
17:06:23  PR fork repo : null/kafka.git
[Pipeline] echo
17:06:23  PR fork branch : 5.3.2-bump
[Pipeline] build
17:06:23  Scheduling project: test-cp-downstream-builds
```
This change explicitly sets `confluentinc` when the variable is not set.
> MINOR: Use confluentinc when CHANGE_FORK is not set

- Jenkinsfile
As per the new Slack changes we want all the notifications from bots
which are not immediately actionable to go to a different channel. Moving
the jenkins build alerts to #kafka-warn.
> Updating the Jenkins config file to post to #kafka-warn

- connect/runtime/src/main/java/org/apache/kafka/connect/runtime/WorkerSourceTask.java
- connect/runtime/src/test/java/org/apache/kafka/connect/runtime/WorkerSourceTaskTest.java
KAFKA-8586: Fail source tasks when producers fail to send records 
Changed Connect's `WorkerSourceTask` to capture non-retriable exceptions from the `producer.send(...)` (e.g., authentication or authorization errors) and to fail the connector task when such an error is encountered. Modified the existing unit tests to verify this functionality.
Note that most producer errors are retriable, and Connect will (by default) set up each producer with 1 max in-flight message and infinite retries. This change only affects non-retriable errors.
(cherry picked from commit 3aa9f99)
for …
> KAFKA-8586: Hot fix

- Jenkinsfile
`gradlew` now downloads the correct gradle version
as needed, so we should not invoke the `gradle`
executable installed in the system.
> CONFLUENT: Remove `gradle` invocation

- docs/js/templateData.js
- gradle.properties
- kafka-merge-pr.py
- streams/quickstart/java/pom.xml
- streams/quickstart/java/src/main/resources/archetype-resources/pom.xml
- streams/quickstart/pom.xml
- tests/kafkatest/__init__.py
- tests/kafkatest/version.py
Now that 5.4.0 is out, this change bumps up the version to
5.4.1-ccs-SNAPSHOT
> CONFLUENT: Bump up version to 5.4.1

- Jenkinsfile
Move kafka build to Artifactory
Use Gradle Artifactory Credentials.
Kafka Team, please help cherry pick this into other branches once PR build passes and merged into master
> Changes to migrate to Artifactory

- gradle/dependencies.gradle
Upgrade to Avro 1.9.2, only for 2.5, not master
The Avro dependency has been removed from master
> Upgrade to Avro 1.9.2

- tests/kafkatest/services/kafka/kafka.py
SupportedKafka needs to be detectable for downgrade_test and upgrade_test to use older ccs version binaries.
> MINOR: kafka.py does not correctly detect pids for deprecated SupportedKafka (#1286)

- clients/src/main/java/org/apache/kafka/common/config/SslConfigs.java
- clients/src/test/java/org/apache/kafka/common/network/SslTransportLayerTest.java
- clients/src/test/java/org/apache/kafka/test/TestSslUtils.java
> KCORE-105: Revert "KAFKA-9460: Enable only TLSv1.2 by default and disable other TLS protocol versions (KIP-553) (#7998)"

- gradle/spotbugs-exclude.xml
The support metrics code has been deleted.
> CONFLUENT: Remove support metrics exclusion from spotbugs-exclude.xml

- clients/src/main/java/org/apache/kafka/clients/admin/KafkaAdminClient.java
- core/src/main/scala/kafka/admin/ConfigCommand.scala
- core/src/test/scala/unit/kafka/admin/ConfigCommandTest.scala
There was a conflict in an import statement in ConfigCommand.
Conflicts:
core/src/main/scala/kafka/admin/ConfigCommand.scala
> CONFLUENT: Sync from apache/kafka 2.5 branch (5 March 2020)

- Jenkinsfile
This PR changes the way jenkins works to make cp-downstream-builds failures mark the build as unstable (yellow) rather than failed (red). We have previously seen committers treating red/failed builds as successful due to a lack of test failures, even though code may have failed to compile or jenkins workers may have exited with non-zero status codes.
We now also capture a text file with the downstream build number in it as a jenkins artifact.
> MINOR: cp-downstream-builds failures should be treated as UNSTABLE

- Jenkinsfile
Fixes groovy.lang.MissingPropertyException: No such property: downstreamBuildFailureOutput for class: WorkflowScript
This happened because we run things slightly differently on master compared to a PR.
> MINOR: fix downstream build failure

- build.gradle
This PR revert two commits that disable the RAT. 
`./gradlew rat` fails unless we have https://github.com/confluentinc/kafka/pull/282 too, in which case it passes. 
> CONFLUENCE: Enable rat gradle task

- gradle.properties
There was a mistake in the version bumping replacement (commit [here](https://github.com/confluentinc/kafka/commit/2a8712bc23efe2e215d54d87ee34a5756144af5f)), so -ccs was removed from the version when bumping for 6.0.x-alpha1, resulting in packaging builds to [fail](https://jenkins.confluent.io/job/confluentinc/job/packaging/job/6.0.x-alpha1/3/console). This commit fixes the version in kafka to include ccs in the versioning.
> Use correct versioning for alpha release

- Jenkinsfile
An exception is caught and marked 'ignored' even though it's actually used in
the catch block. Declare the caught Exception.
This is a backport of https://github.com/confluentinc/ce-kafka/pull/1430 and validated there.
> MINOR: Fix Jenkinsfile.

- Jenkinsfile
- build.gradle
**Context:** Preview release artifacts (in particular jars for 6.0.0-ccs-alpha1) were not getting published to Artifactory. As a result, 6.0.x-alpha1 branches in `common` and other PLATFORM repos were not able to build successfully.
**Changes:** This commit updates the Jenkinsfile to handle preview release jobs. It checks if the job is a preview job (denoted by -alpha in the branch name), and use specific preview release settings for publishing to `maven-releases-preview` in Artifactory if so.
This was tested with replay option on [this 6.0.x-alpha1 job](https://jenkins.confluent.io/job/confluentinc/job/kafka/job/6.0.x-alpha1/17/) and it ran successfully, publishing artifacts to Artifactory and allowing platform repos to build (e.g. [successful build in …
> Publish preview jobs with preview release settings

- Jenkinsfile
1st change: The Kafka job for the 1.0 Branch has been failing on `./gradlew: not found` - 1.0 and 1.1 do not contain the wrapper script, so call gradle to do an initial "bootstrap" - this is the failing job:
https://jenkins.confluent.io/job/confluentinc/job/kafka/job/1.0/
This change seemed to make it work on my replay:
https://jenkins.confluent.io/job/confluentinc/job/kafka/job/1.0/42/replay/diff
2nd change: Use `test-cp-downstream-builds-jdk7` as the 4.0.x and 4.1.x versions use JDK7.
I will merge this into 1.1 as well since it too is suffering from the same failure.
Other notes:
> Why am I removing `spotlessScalaCheck`? 
That doesn't seem to be a valid target for 1.0:
https://jenkins.confluent.io/job/confluentinc/job/kafka/job/1.0/40/console
> MINOR: Fix Jenkins build

- core/src/test/scala/unit/kafka/log/LogTest.scala
- core/src/test/scala/unit/kafka/server/ReplicaAlterLogDirsThreadTest.scala
Partial cherry-pick of changes from 2.5 leave documentation changes.
> Porting scala 2.11 compatible from 2.5  to 2.4

- gradle.properties
- tests/kafkatest/__init__.py
- tests/kafkatest/version.py
This is a manual version Bump to 5.5.1
Upon approval, I will `git push` this change directly to confluent/kafka.
> Bump AK version to 5.5.1

- core/src/main/scala/kafka/log/Log.scala
- core/src/main/scala/kafka/log/LogCleanerManager.scala
- core/src/test/scala/unit/kafka/log/LogCleanerManagerTest.scala
- core/src/test/scala/unit/kafka/log/LogTest.scala
- core/src/test/scala/unit/kafka/server/ReplicaAlterLogDirsThreadTest.scala
Merge conflict in core/src/test/scala/unit/kafka/server/ReplicaAlterLogDirsThreadTest.scala
Kept the version from the most recent AK change, so the diff shows the change.
> Sync from upstream ak ccs 29 apr 2020

- build.gradle
- raft/src/test/resources/log4j.properties
Adds default log4j.properties to test resources and the log4j library as a test dependence.
> Add test logging support

- clients/src/main/java/org/apache/kafka/common/record/MemoryRecordsBuilder.java
- core/src/main/scala/kafka/raft/KafkaMetadataLog.scala
- core/src/main/scala/kafka/raft/KafkaNetworkChannel.scala
- core/src/test/scala/unit/kafka/raft/KafkaNetworkChannelTest.scala
- raft/src/main/java/org/apache/kafka/raft/ConnectionCache.java
- raft/src/main/java/org/apache/kafka/raft/KafkaRaftClient.java
- raft/src/main/java/org/apache/kafka/raft/NetworkChannel.java
- raft/src/main/java/org/apache/kafka/raft/RaftMessage.java
- raft/src/main/java/org/apache/kafka/raft/RaftRequest.java
- raft/src/main/java/org/apache/kafka/raft/RaftResponse.java
- raft/src/main/java/org/apache/kafka/raft/ReplicatedLog.java
- raft/src/test/java/org/apache/kafka/raft/ConnectionCacheTest.java
- raft/src/test/java/org/apache/kafka/raft/KafkaRaftClientTest.java
- raft/src/test/java/org/apache/kafka/raft/MockLog.java
- raft/src/test/java/org/apache/kafka/raft/MockLogTest.java
- raft/src/test/java/org/apache/kafka/raft/MockNetworkChannel.java
- raft/src/test/java/org/apache/kafka/raft/RaftEventSimulationTest.java
This PR addresses some of @guozhangwang's comments from this commit: https://github.com/confluentinc/kafka/commit/854133695b39518c5223c8e5b838b86e8cd01405. 
Specifically this patch makes the following changes:
1. Replace the usage of `requestId` with `correlationId`, which is already widely used in Kafka.
2. Make `MockLog` aware of record batching to make its behavior more consistent with the `Log` implementation and to 
3. Add test coverage to `ConnectionCache`.
> MINOR: Address review comments and improve test coverage

- gradle.properties
- tests/kafkatest/__init__.py
- tests/kafkatest/version.py
This is a version bump for CCS Kafka now that 5.4.2 is released. I will merge this over to ce-kafka after approval here.
> MINOR: Bump version to 5.4.3

- .gitignore
- build.gradle
- checkstyle/import-control.xml
- checkstyle/suppressions.xml
- core/src/main/scala/kafka/raft/KafkaNetworkChannel.scala
- core/src/main/scala/kafka/security/authorizer/AclAuthorizer.scala
- core/src/test/scala/unit/kafka/raft/KafkaNetworkChannelTest.scala
- raft/src/main/java/org/apache/kafka/raft/ElectionState.java
- raft/src/main/java/org/apache/kafka/raft/FileBasedStateStore.java
- raft/src/main/java/org/apache/kafka/raft/KafkaRaftClient.java
- raft/src/main/java/org/apache/kafka/raft/QuorumState.java
- raft/src/main/java/org/apache/kafka/raft/QuorumStateStore.java
- raft/src/main/resources/common/META-INF/services/org.apache.kafka.common.config.provider.ConfigProvider
- raft/src/main/resources/common/message/QuorumState.json
- raft/src/test/java/org/apache/kafka/raft/FileBasedStateStoreTest.java
- raft/src/test/java/org/apache/kafka/raft/KafkaRaftClientTest.java
- raft/src/test/java/org/apache/kafka/raft/MockLog.java
- raft/src/test/java/org/apache/kafka/raft/MockQuorumStateStore.java
- raft/src/test/java/org/apache/kafka/raft/QuorumStateTest.java
- raft/src/test/java/org/apache/kafka/raft/RaftEventSimulationTest.java
- raft/src/test/java/org/apache/kafka/raft/SimpleKeyValueStoreTest.java
This patch adds the auto generation framework to Raft package, create QuorumState as a data type, and use local file to materialize election state, etc.
> KCORE-349: Add quorum-state file

- raft/src/main/java/org/apache/kafka/raft/CandidateState.java
- raft/src/main/java/org/apache/kafka/raft/FollowerState.java
- raft/src/main/java/org/apache/kafka/raft/KafkaRaftClient.java
- raft/src/main/java/org/apache/kafka/raft/LeaderState.java
- raft/src/main/java/org/apache/kafka/raft/QuorumState.java
- raft/src/test/java/org/apache/kafka/raft/CandidateStateTest.java
- raft/src/test/java/org/apache/kafka/raft/KafkaRaftClientTest.java
- raft/src/test/java/org/apache/kafka/raft/LeaderStateTest.java
- raft/src/test/java/org/apache/kafka/raft/QuorumStateTest.java
- raft/src/test/java/org/apache/kafka/raft/RaftEventSimulationTest.java
- raft/src/test/java/org/apache/kafka/raft/SimpleKeyValueStoreTest.java
Address review comments from https://github.com/confluentinc/kafka/commit/9f52a740aba457dcf27c5babd12d6dbbe31d5e4f. Most of the changes are cosmetic (changing naming or state representation), but we also fix a couple issues:
1. We ensure that jitter is respected after the election timeout expires when we are a candidate.
2. We reject appends if we are not the leader.
> Address comments from review of core raft implementation

- Jenkinsfile
This pr is to enable downstream validation on kafka master branch and some minor changes. 
1. It will compile all downstream repos that depend on kafka. If some repos fail to compile, the result will be marked `UNSTABLE`.
2. Add gradlew install as part of the build cmd since we need artifacts to be install at local m2 repository.
3. I think the stage Run Tests and build cp-downstream-builds did not output anything, I don't think we need that stage at all. Remove it can make the stage view more clear.
4. Following ce-kafka's decision, the build frequency will be changed to `@weekly` instead `@midnight` to prevent build storm(all pr build at the same time).
> Minor: enable downstreamValidation

- clients/src/main/java/org/apache/kafka/common/errors/InconsistentVoterSetException.java
- clients/src/main/java/org/apache/kafka/common/protocol/Errors.java
- raft/src/main/java/org/apache/kafka/raft/ConnectionCache.java
- raft/src/main/java/org/apache/kafka/raft/FollowerState.java
- raft/src/main/java/org/apache/kafka/raft/KafkaRaftClient.java
- raft/src/main/java/org/apache/kafka/raft/QuorumState.java
- raft/src/main/java/org/apache/kafka/raft/RaftResponse.java
- raft/src/test/java/org/apache/kafka/raft/FollowerStateTest.java
- raft/src/test/java/org/apache/kafka/raft/KafkaRaftClientTest.java
- raft/src/test/java/org/apache/kafka/raft/MockNetworkChannel.java
- raft/src/test/java/org/apache/kafka/raft/QuorumStateTest.java
The purpose of this patch is to get rid of the clumsy error handling in `maybeHandleError` and establish more consistent conventions for request/response handling.
> KCORE-414; Make request/response error handling more conventional

- build.gradle
We have updated gradle daemon heap memory to 2g. This PR is to increase the scalac heap size to 2g. This will make consistent memory settings
> MINOR: Increase scalac heap size to 2g

- clients/src/main/java/org/apache/kafka/common/utils/Timer.java
- clients/src/test/java/org/apache/kafka/common/utils/TimerTest.java
- raft/src/main/java/org/apache/kafka/raft/FollowerState.java
- raft/src/main/java/org/apache/kafka/raft/KafkaRaftClient.java
- raft/src/main/java/org/apache/kafka/raft/LeaderState.java
- raft/src/main/java/org/apache/kafka/raft/RaftConfig.java
- raft/src/test/java/org/apache/kafka/raft/KafkaRaftClientTest.java
- raft/src/test/java/org/apache/kafka/raft/RaftEventSimulationTest.java
- raft/src/test/java/org/apache/kafka/raft/SimpleKeyValueStoreTest.java
1. Introduce the fetch timeout config.
2. Leader relying on the fetch timeout to send find-quorum if does not receive from a majority of quorum.
3. Voter relying on fetch timeout to become candidate (not relying on election timeout).
We also merge the two timers into a single timer, and also added unit tests. Simulation tests now passed.
> KCORE-353: Leader progress timeout

- checkstyle/suppressions.xml
- clients/src/main/java/org/apache/kafka/common/utils/Utils.java
- clients/src/main/resources/common/message/FetchQuorumRecordsRequest.json
- clients/src/test/java/org/apache/kafka/common/utils/MockScheduler.java
- clients/src/test/java/org/apache/kafka/common/utils/MockTime.java
- core/src/main/scala/kafka/raft/KafkaFuturePurgatory.scala
- core/src/main/scala/kafka/raft/KafkaNetworkChannel.scala
- core/src/test/scala/unit/kafka/raft/KafkaFuturePurgatoryTest.scala
- raft/src/main/java/org/apache/kafka/raft/FuturePurgatory.java
- raft/src/main/java/org/apache/kafka/raft/KafkaRaftClient.java
- raft/src/main/java/org/apache/kafka/raft/LeaderState.java
- raft/src/main/java/org/apache/kafka/raft/RaftUtil.java
- raft/src/test/java/org/apache/kafka/raft/KafkaRaftClientTest.java
- raft/src/test/java/org/apache/kafka/raft/MockFuturePurgatory.java
- raft/src/test/java/org/apache/kafka/raft/MockFuturePurgatoryTest.java
- raft/src/test/java/org/apache/kafka/raft/MockNetworkChannel.java
- raft/src/test/java/org/apache/kafka/raft/RaftEventSimulationTest.java
- raft/src/test/java/org/apache/kafka/raft/SimpleKeyValueStoreTest.java
This patch adds a simple purgatory interface and integration with Kafka's `DelayedOperationPurgatory`. For the moment, we only support max wait time, which has been added to the `FetchQuorumRecords` request schema.
Note that this patch is piggy-backed on #319. The most-recent commit is the one that should be reviewed here.
> KCORE-368; Add basic purgatory for quorum fetches

- raft/src/main/java/org/apache/kafka/raft/KafkaRaftClient.java
- raft/src/main/java/org/apache/kafka/raft/RecordAppender.java
- raft/src/main/java/org/apache/kafka/raft/ReplicatedStateMachine.java
- raft/src/main/java/org/apache/kafka/raft/SimpleKeyValueStore.java
- raft/src/test/java/org/apache/kafka/raft/KafkaRaftClientTest.java
- raft/src/test/java/org/apache/kafka/raft/MockStateMachine.java
- raft/src/test/java/org/apache/kafka/raft/NoOpStateMachine.java
- raft/src/test/java/org/apache/kafka/raft/RaftEventSimulationTest.java
- raft/src/test/java/org/apache/kafka/raft/ReplicatedCounter.java
- raft/src/test/java/org/apache/kafka/raft/SimpleKeyValueStoreTest.java
This PR addresses some of the suggested improvements from KCORE-403, including:
1. Rename `DistributedStateMachine` to `ReplicatedStateMachine`
2. Make StateMachine interface extends `AutoClosable`
3. Get a separate `RecordAppender` interface to decouple the circular dependency between state machine and raft client
> KCORE-403: Refactor Raft StateMachine API

- raft/src/main/java/org/apache/kafka/raft/CandidateState.java
- raft/src/main/java/org/apache/kafka/raft/ElectionState.java
- raft/src/main/java/org/apache/kafka/raft/FileBasedStateStore.java
- raft/src/main/java/org/apache/kafka/raft/FollowerState.java
- raft/src/main/java/org/apache/kafka/raft/LeaderState.java
- raft/src/main/java/org/apache/kafka/raft/QuorumState.java
- raft/src/test/java/org/apache/kafka/raft/FileBasedStateStoreTest.java
- raft/src/test/java/org/apache/kafka/raft/FollowerStateTest.java
- raft/src/test/java/org/apache/kafka/raft/KafkaRaftClientTest.java
- raft/src/test/java/org/apache/kafka/raft/MockQuorumStateStore.java
- raft/src/test/java/org/apache/kafka/raft/QuorumStateTest.java
- raft/src/test/java/org/apache/kafka/raft/RaftEventSimulationTest.java
- raft/src/test/java/org/apache/kafka/raft/SimpleKeyValueStoreTest.java
Amend a gap for quorum state information to add the known voters into the state file.
> KCORE-440: add voter information towards the quorum-state file

- bin/raft-server-start.sh
- config/raft-log4j.properties
- config/raft.properties
- core/src/main/scala/kafka/log/Log.scala
- core/src/main/scala/kafka/raft/KafkaFuturePurgatory.scala
- core/src/main/scala/kafka/raft/KafkaMetadataLog.scala
- core/src/main/scala/kafka/raft/KafkaNetworkChannel.scala
- core/src/main/scala/kafka/server/KafkaApis.scala
- core/src/main/scala/kafka/server/KafkaRequestHandler.scala
- core/src/main/scala/kafka/server/RaftRequestHandler.scala
- core/src/main/scala/kafka/server/RaftServer.scala
- core/src/test/scala/unit/kafka/raft/KafkaFuturePurgatoryTest.scala
- raft/src/main/java/org/apache/kafka/raft/ConnectionCache.java
- raft/src/main/java/org/apache/kafka/raft/ElectionState.java
- raft/src/main/java/org/apache/kafka/raft/FileBasedStateStore.java
- raft/src/main/java/org/apache/kafka/raft/KafkaRaftClient.java
- raft/src/main/java/org/apache/kafka/raft/QuorumState.java
- raft/src/main/java/org/apache/kafka/raft/QuorumStateStore.java
- raft/src/main/java/org/apache/kafka/raft/RaftConfig.java
- raft/src/main/java/org/apache/kafka/raft/ReplicatedCounter.java
- raft/src/test/java/org/apache/kafka/raft/ConnectionCacheTest.java
- raft/src/test/java/org/apache/kafka/raft/KafkaRaftClientTest.java
- raft/src/test/java/org/apache/kafka/raft/MockQuorumStateStore.java
- raft/src/test/java/org/apache/kafka/raft/QuorumStateTest.java
- raft/src/test/java/org/apache/kafka/raft/RaftEventSimulationTest.java
This patch adds the wiring to startup a dummy server which uses the `DistributedCounter` state machine. It more or less works after fixing a few minor bugs, but there are problems with the `FindQuorum` discovery logic.
> Minimal raft server implementation for more interesting testing

- streams/quickstart/java/src/main/resources/archetype-resources/pom.xml
- streams/quickstart/pom.xml
Manual version bump for CCS Kafka. `gradle.properties` is already at `version=6.0.0-ccs-SNAPSHOT`
> Move CCS Kafka to Confluent Versions in 2.6

- clients/src/main/resources/common/message/EndQuorumEpochRequest.json
- raft/src/main/java/org/apache/kafka/raft/KafkaRaftClient.java
- raft/src/main/java/org/apache/kafka/raft/LeaderState.java
- raft/src/test/java/org/apache/kafka/raft/KafkaRaftClientTest.java
- raft/src/test/java/org/apache/kafka/raft/LeaderStateTest.java
This PR attempts to make the EndEpoch logic smarter by always picking the most up-to-date follower to send the TimeOut signal to. It will wait for every election timeout and resend the request to the next up-to-date follower who hasn't been sent yet. So eventually when we run out of followers to send EndQuorum to, the finish timer times out and shutdown will be complete.
Quote Guozhang's idea here:
> Given that the motivation of EndQuorum is to shorten the timeout before election, maybe we can just do sth. like: say the fetch.timeout is X, and `election.timeout` is Y << X let the old leader send the EndQuorum to her “favorite” voter right away, while intentionally delaying the EndQuorum by Z where Y < Z < X to other voters, hoping that by then the favorite voter already successfully …
> KCORE-444: Revise EndQuorum logic to send to preferred followers first

- raft/src/main/java/org/apache/kafka/raft/KafkaRaftClient.java
- raft/src/test/java/org/apache/kafka/raft/KafkaRaftClientTest.java
- raft/src/test/java/org/apache/kafka/raft/MockLog.java
- raft/src/test/java/org/apache/kafka/raft/MockLogTest.java
It is important that we preserve batch boundaries in the MockLog implementation since they may (eventually) have semantic significance. For example, we may use batches to atomically apply a set of operations.
Note that the replication protocol guarantees that followers can only send fetch offsets on batch boundaries, which also implies that the high watermark is aligned. If there was a misaligned fetch, then it would result in a validation error and an offset reset.
> MockLog should only read full batches

- core/src/main/scala/kafka/raft/KafkaMetadataLog.scala
- raft/src/main/java/org/apache/kafka/raft/KafkaRaftClient.java
- raft/src/main/java/org/apache/kafka/raft/ReplicatedLog.java
- raft/src/test/java/org/apache/kafka/raft/KafkaRaftClientTest.java
- raft/src/test/java/org/apache/kafka/raft/MockLog.java
- raft/src/test/java/org/apache/kafka/raft/MockLogTest.java
If the fetch response has no data, then the log append currently fails with an `Append failed unexpectedly` error. The problem is that there is no start offset for an empty append. This patch fixes the problem by adding a check in the response handler and skipping the append if the record set is empty. We also formally make empty appends invalid in the API and add some testing for this.
> Require non-empty record set in append APIs

- raft/src/test/java/org/apache/kafka/raft/MockLog.java
- raft/src/test/java/org/apache/kafka/raft/MockQuorumStateStore.java
- raft/src/test/java/org/apache/kafka/raft/QuorumStateTest.java
- raft/src/test/java/org/apache/kafka/raft/RaftEventSimulationTest.java
I found that most of the time running the simulation test was spent validating committed data. I turned this into a `Validation`, which is run after simulation completion rather than an `Invariant` which is checked after each event. I have also added a couple additional invariants. This dropped the time to run these tests from over 3-5 minutes to about 30 seconds.
> Improve simulation performance and validation

- core/src/main/scala/kafka/log/Log.scala
- core/src/main/scala/kafka/raft/KafkaMetadataLog.scala
- core/src/main/scala/kafka/raft/SegmentPosition.scala
- raft/src/main/java/org/apache/kafka/raft/EpochState.java
- raft/src/main/java/org/apache/kafka/raft/FollowerState.java
- raft/src/main/java/org/apache/kafka/raft/KafkaRaftClient.java
- raft/src/main/java/org/apache/kafka/raft/LeaderState.java
- raft/src/main/java/org/apache/kafka/raft/LogFetchInfo.java
- raft/src/main/java/org/apache/kafka/raft/LogOffsetMetadata.java
- raft/src/main/java/org/apache/kafka/raft/OffsetMetadata.java
- raft/src/main/java/org/apache/kafka/raft/QuorumState.java
- raft/src/main/java/org/apache/kafka/raft/ReplicatedLog.java
- raft/src/main/java/org/apache/kafka/raft/internals/KafkaRaftMetrics.java
- raft/src/test/java/org/apache/kafka/raft/FollowerStateTest.java
- raft/src/test/java/org/apache/kafka/raft/KafkaRaftClientTest.java
- raft/src/test/java/org/apache/kafka/raft/LeaderStateTest.java
- raft/src/test/java/org/apache/kafka/raft/MockLog.java
- raft/src/test/java/org/apache/kafka/raft/MockLogTest.java
- raft/src/test/java/org/apache/kafka/raft/QuorumStateTest.java
- raft/src/test/java/org/apache/kafka/raft/RaftEventSimulationTest.java
- raft/src/test/java/org/apache/kafka/raft/internals/KafkaRaftMetricsTest.java
Cache the high watermark by remembering all replica's end offset as the LogOffsetMetadata.
Note that comparing with https://github.com/confluentinc/kafka/pull/344 we are only caching hw on the leader side, not on follower since the updated HW does not match the append log info, while the state machine application executes on both leader and followers --- i.e. on follower-side we still need to read the hw every time.
> KCORE-579: Cache high watermark on the leader

- clients/src/main/java/org/apache/kafka/common/utils/Timer.java
- clients/src/test/java/org/apache/kafka/common/utils/TimerTest.java
- core/src/main/scala/kafka/raft/KafkaMetadataLog.scala
- core/src/main/scala/kafka/raft/KafkaNetworkChannel.scala
- core/src/main/scala/kafka/server/RaftServer.scala
- core/src/test/scala/unit/kafka/raft/KafkaFuturePurgatoryTest.scala
- raft/src/main/java/org/apache/kafka/raft/KafkaRaftClient.java
- raft/src/main/java/org/apache/kafka/raft/NetworkChannel.java
- raft/src/main/java/org/apache/kafka/raft/QuorumState.java
- raft/src/main/java/org/apache/kafka/raft/RaftClient.java
- raft/src/main/java/org/apache/kafka/raft/ReplicatedLog.java
- raft/src/test/java/org/apache/kafka/raft/KafkaRaftClientTest.java
- raft/src/test/java/org/apache/kafka/raft/MockLog.java
- raft/src/test/java/org/apache/kafka/raft/MockLogTest.java
- raft/src/test/java/org/apache/kafka/raft/QuorumStateTest.java
- raft/src/test/java/org/apache/kafka/raft/RaftEventSimulationTest.java
This patch does the following:
- Fixes shutdown logic so that the resigning leader stays alive long enough to help its successor get elected.
- Add graceful shutdown to simulation test cases
- Add graceful shutdown logic to `RaftServer`
- Improve graceful shutdown test coverage
- Add more logging on shutdown
> Graceful shutdown improvements

- gradle.properties
- tests/kafkatest/__init__.py
- tests/kafkatest/version.py
Now that 5.5.1 is released, we need to bump CCS Kafka to 5.5.2.
I will do a CCS -> CE merge after this.
> MINOR: Bump CCS version to 5.5.2

- raft/src/main/resources/common/message/QuorumState.json
To align with KIP-595, we need to remove the target voter set for now.
> MINOR: Remove target voters from quorum state data

- Jenkinsfile
When I refactored the jenkinsfile to get the secrets from vault I missed the part where we need to get different artifactory settings for preview releases. This will get the correct settings depending if its regular build or preview release build.
> ST-3402: Fix to get artifactory settings for preview release builds

- clients/src/main/java/org/apache/kafka/common/requests/BeginQuorumEpochRequest.java
- clients/src/main/java/org/apache/kafka/common/requests/BeginQuorumEpochResponse.java
- clients/src/main/java/org/apache/kafka/common/requests/DescribeQuorumRequest.java
- clients/src/main/java/org/apache/kafka/common/requests/DescribeQuorumResponse.java
- clients/src/main/java/org/apache/kafka/common/requests/EndQuorumEpochRequest.java
- clients/src/main/java/org/apache/kafka/common/requests/EndQuorumEpochResponse.java
- clients/src/main/java/org/apache/kafka/common/requests/VoteRequest.java
- clients/src/main/java/org/apache/kafka/common/requests/VoteResponse.java
- clients/src/main/resources/common/message/BeginQuorumEpochRequest.json
- clients/src/main/resources/common/message/BeginQuorumEpochResponse.json
- clients/src/main/resources/common/message/DescribeQuorumRequest.json
- clients/src/main/resources/common/message/DescribeQuorumResponse.json
- clients/src/main/resources/common/message/EndQuorumEpochRequest.json
- clients/src/main/resources/common/message/EndQuorumEpochResponse.json
- clients/src/main/resources/common/message/VoteRequest.json
- clients/src/main/resources/common/message/VoteResponse.json
- core/src/test/scala/unit/kafka/raft/KafkaNetworkChannelTest.scala
- core/src/test/scala/unit/kafka/server/RequestQuotaTest.scala
- raft/src/main/java/org/apache/kafka/raft/KafkaRaftClient.java
- raft/src/main/java/org/apache/kafka/raft/RaftUtil.java
- raft/src/test/java/org/apache/kafka/raft/KafkaRaftClientTest.java
On top of https://github.com/confluentinc/kafka/pull/357. Will be rebased after the dependent PR gets merged.
> KC-700: Replace Begin/EndQuorum RPC with Multi-raft

- bin/kafka-run-class.sh
Add share/java/confluent-telemetry to kafka's classpath.
This is where we'll install the confluent-metrics jar (as part of packaging) and we need this jar for telemetry to work.
> METRICS-1988: add confluent-telemetry directory to kafka classpath

- Jenkinsfile
- build.gradle
- ci.py
- gradle.properties
- streams/quickstart/java/pom.xml
- streams/quickstart/java/src/main/resources/archetype-resources/pom.xml
- streams/quickstart/pom.xml
- tests/README.md
- tests/kafkatest/__init__.py
- tests/kafkatest/tests/streams/streams_upgrade_test.py
- tests/kafkatest/utils/util.py
- tests/kafkatest/version.py
Implementing nano versioning for kafka repo.
Set all the version properties to include a build number and no longer use snapshot qualifier
Updated the skip signing condition to skip signing for these new versions.
Added a ci.py script to perform additional updates to version properties during CI builds.
This was tested on the nano versioning branch in the nano versioning jenkins org. The PR build will probably fail right now because there are changes to ci-tools and jenkins-common that need to be merged in order for this to work properly. The nano versioning jenkins organization contained these changes which is why the tests work there.
> ST-3458: Implement Nano versioning

- bin/kafka-run-class.sh
backports https://github.com/confluentinc/kafka/pull/381 to 2.6 branch
> backport METRICS-1988: add confluent-telemetry directory to kafka classpath 

- Jenkinsfile
I am temporarily disabling the down stream validation because it is not working with nano versioned artifacts. I will follow up with a solution for getting this to work and then re-enable this here.
> ST-3461: Temporarily disable down stream validation because it is not working with nano versioned artifacts

- Jenkinsfile
In the initial nano versioning commit I forgot to include the code in the jenkins file to trigger the down stream repos, in this case common. After we publish the artifacts we need to trigger the common build. We do the same thing in ce-kafka, but some how when merging I missed this. This was tested in the nano versioning branch.
This does not address the issue that we are publishing the artifacts before we run the unit and integration tests. I will address that in another PR but need to get this fixed right away other wise new artifacts from kafka will never get used by down stream repos.
> ST-3461: Trigger down stream builds after publishing artifacts

- build.gradle
- gradle/dependencies.gradle
This pull request updates `confluent-log4j` from `1.2.17-cp1` to `1.2.17-cp2`. The former had a few accidental commits that made the repackaged version slightly different than the upstream `log4j`. `1.2.17-cp2` fixes the issue and applies a CVE fix (and no additional code changes) to the upstream `log4j:1.2.17`.
This commit ought to be cherry picked to 2.6 branch as well.
Testing performed: Confluent jenkins system testing with a draft branch with the requested change with two small smoke tests that services start appropriately, and that logging is as expected. Also checked class paths for any odd issues. More details: https://confluentinc.atlassian.net/browse/SEC-1334?focusedCommentId=340490
> SEC-1334: update confluent-log4j version

- ci.py
Merge from AK trunk is failing because `gradlew :rat" fails due to missing license in `ci.py`. For example, https://jenkins.confluent.io/job/apache-kafka-test/job/trunk/1745 failed with:
```
14:53:00  > Task :rat FAILED
14:53:00  Unknown license: /home/jenkins/workspace/apache-kafka-test_trunk/kafka/ci.py
```
> CONFLUENT: Add license to ci.py to pass license check

- gradle/dependencies.gradle
Update Jackson to 2.10.5 and Jersey to 2.30. Note that the versions in
master are already aligned.
> CPKAFKA-5791: Bump Jersey and Jackson versions for 6.0.x: Align jersey and jackson versions with `confluentinc/common` for 2.6/6.0.x

- tests/docker/Dockerfile
- tests/setup.py
ducktape diff: https://github.com/confluentinc/ducktape/compare/v0.7.8...v0.7.9
- bcrypt (a dependency of ducktape) dropped Python2.7 support.
ducktape-0.7.9 now pins bcrypt to a Python2.7-supported version.
Author: Andrew Egelhofer <aegelhofer@confluent.io>
Reviewers: Dhruvil Shah <dhruvil@confluent.io>, Manikumar Reddy <manikumar.reddy@gmail.com>
Closes #9192 from andrewegel/trunk
(cherry picked from commit f6c26eaa04d8eb44c8decf91bb80b621e4086e84)
Signed-off-by: Manikumar Reddy <manikumar.reddy@gmail.com>
Cherry-picking this fix into 2.6
> MINOR: Use new version of ducktape

- bin/kafka-run-class.sh
- checkstyle/import-control.xml
- checkstyle/suppressions.xml
- clients/src/main/java/org/apache/kafka/common/protocol/ApiMessageAndVersion.java
- gradle/spotbugs-exclude.xml
- metadata/src/main/java/org/apache/kafka/controller/Controller.java
- metadata/src/main/java/org/apache/kafka/controller/LeaderAndIsr.java
- metadata/src/main/java/org/apache/kafka/controller/LocalLogManager.java
- metadata/src/main/java/org/apache/kafka/controller/MetaLogManager.java
- metadata/src/main/java/org/apache/kafka/controller/PartitionLeaderElectionResult.java
- metadata/src/main/java/org/apache/kafka/controller/QuorumController.java
- metadata/src/main/java/org/apache/kafka/metadata/MetadataParser.java
- metadata/src/test/java/org/apache/kafka/controller/LocalLogManagerTest.java
- metadata/src/test/java/org/apache/kafka/controller/LocalLogManagerTestEnv.java
- metadata/src/test/java/org/apache/kafka/controller/MockMetaLogManagerListener.java
- metadata/src/test/java/org/apache/kafka/controller/QuorumControllerTest.java
Add MetaLogManager, which manages the log which the kip-500 controller
relies on.  It handles things like claiming leadership, renouncing
leadership, applying records that have been committed, and so forth.
Eventually, we will have a MetaLogManager that hooks up to Raft.  For
now, we have a simple implementation based on a local log file which is
shared.
> Add MetaLogManager

- config/raft-log4j.properties
- core/src/main/scala/kafka/raft/KafkaNetworkChannel.scala
- core/src/main/scala/kafka/server/KafkaApis.scala
- core/src/main/scala/kafka/server/TestRaftServer.scala
- raft/src/main/java/org/apache/kafka/raft/CandidateState.java
- raft/src/main/java/org/apache/kafka/raft/ElectionState.java
- raft/src/main/java/org/apache/kafka/raft/FollowerState.java
- raft/src/main/java/org/apache/kafka/raft/KafkaRaftClient.java
- raft/src/main/java/org/apache/kafka/raft/LeaderState.java
- raft/src/main/java/org/apache/kafka/raft/QuorumState.java
- raft/src/main/java/org/apache/kafka/raft/RequestManager.java
- raft/src/main/java/org/apache/kafka/raft/UnattachedState.java
- raft/src/main/java/org/apache/kafka/raft/VotedState.java
- raft/src/main/java/org/apache/kafka/raft/internals/KafkaRaftMetrics.java
- raft/src/test/java/org/apache/kafka/raft/CandidateStateTest.java
- raft/src/test/java/org/apache/kafka/raft/FollowerStateTest.java
- raft/src/test/java/org/apache/kafka/raft/KafkaRaftClientTest.java
- raft/src/test/java/org/apache/kafka/raft/LeaderStateTest.java
- raft/src/test/java/org/apache/kafka/raft/QuorumStateTest.java
- raft/src/test/java/org/apache/kafka/raft/RaftEventSimulationTest.java
- raft/src/test/java/org/apache/kafka/raft/RequestManagerTest.java
- raft/src/test/java/org/apache/kafka/raft/VotedStateTest.java
- raft/src/test/java/org/apache/kafka/raft/internals/KafkaRaftMetricsTest.java
This PR attempts to improve timeout/backoff logic in the raft client. It does the following:
- Split the Follower state into three separates and document all state transitions 
- Move fetch/election timer into respective `EpochState` implementations
- Take into account backoffs when setting poll timeout
Plus a bunch of small fixes. Note that this builds off #390. I will rebase after it is merged.
> Refactor state/poll backoffs and timeouts

- clients/src/main/java/org/apache/kafka/common/utils/EventQueue.java
- clients/src/main/java/org/apache/kafka/common/utils/KafkaEventQueue.java
- clients/src/test/java/org/apache/kafka/common/utils/KafkaEventQueueTest.java
- gradle/spotbugs-exclude.xml
Add an event queue for use with the new Kafka Controller.  It supports
deferred operations, as well as timeouts on events.
> Add KafkaEventQueue

- clients/src/main/java/org/apache/kafka/clients/consumer/KafkaConsumer.java
- clients/src/main/java/org/apache/kafka/clients/consumer/internals/AbstractCoordinator.java
- clients/src/main/java/org/apache/kafka/clients/consumer/internals/ConsumerCoordinator.java
- clients/src/main/java/org/apache/kafka/clients/consumer/internals/Heartbeat.java
- clients/src/test/java/org/apache/kafka/clients/ClientUtilsTest.java
- clients/src/test/java/org/apache/kafka/clients/ClusterConnectionStatesTest.java
- clients/src/test/java/org/apache/kafka/clients/MockClient.java
- clients/src/test/java/org/apache/kafka/clients/admin/KafkaAdminClientTest.java
- clients/src/test/java/org/apache/kafka/clients/consumer/KafkaConsumerTest.java
- clients/src/test/java/org/apache/kafka/clients/consumer/internals/AbstractCoordinatorTest.java
- clients/src/test/java/org/apache/kafka/clients/consumer/internals/ConsumerCoordinatorTest.java
- core/src/main/scala/kafka/coordinator/group/GroupCoordinator.scala
- core/src/test/scala/integration/kafka/network/DynamicConnectionQuotaTest.scala
- core/src/test/scala/unit/kafka/coordinator/group/GroupCoordinatorTest.scala
- streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamThread.java
- streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamsPartitionAssignor.java
- streams/src/test/java/org/apache/kafka/streams/processor/internals/StreamThreadTest.java
- tests/kafkatest/tests/streams/streams_static_membership_test.py
- tests/kafkatest/tests/streams/streams_upgrade_test.py
- tests/kafkatest/tests/streams/utils/__init__.py
- tests/kafkatest/tests/streams/utils/util.py
Cherry-picking following PRs:
- https://github.com/apache/kafka/commit/7e7bb184d2abe34280a7f0eb0f0d9fc0e32389f2
- https://github.com/apache/kafka/commit/5ee3ecb1e3bb4f6a8f8e344229c1a88b1d230e73
- https://github.com/apache/kafka/commit/bc7674fe1bd50bfa8e6b568ab84d112412b1d3e5
- https://github.com/apache/kafka/commit/bd462df20321ff5b75a7e3eae70634268582d90b
test failure fixes:
- https://github.com/apache/kafka/commit/1443f24ace98aac9e15f5ec8178040f848ff3d74
- https://github.com/apache/kafka/commit/e4eab377e1489fc0cc90edec3eeb382b1192a442
- https://github.com/apache/kafka/commit/e9251a11dc60122893c7bcfb2be36c3cd0521902
> Cherry-pick commits to KsqlDB 0.13 release

- build.gradle
- core/src/test/scala/unit/kafka/coordinator/group/GroupMetadataManagerTest.scala
One merge conflict - Jenkinsfile due to adding that to AK (kept the version in CCS so you don't see changes here).  Can you confirm @mumrah ?
> Sync upstream AK 2.4 -> CCS 2.4 -  1 oct 2020

- gradle.properties
- streams/quickstart/java/src/main/resources/archetype-resources/pom.xml
- streams/quickstart/pom.xml
- tests/kafkatest/__init__.py
- tests/kafkatest/version.py
With 5.5.2 out the door, its time to bump the versions in CCS Kafka to 5.5.3
- In the past we've not bumped the streams versions from AK to CCS
versions, but we should begin.
> MINOR: CCS Version Bump to 5.5.3-ccs-SNAPSHOT

- clients/src/test/java/org/apache/kafka/clients/ClientUtilsTest.java
- clients/src/test/java/org/apache/kafka/clients/ClusterConnectionStatesTest.java
These tests were fragile, so we made a temporary fix #9294
These changes need to be back-ported to previous versions.
The tests in question passed locally.
> MINOR: Backported changes to ClientUtils.resolve tests to 2.4 

- streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java
- streams/src/test/java/org/apache/kafka/streams/processor/internals/StreamTaskTest.java
This was a cherry-pick of https://github.com/apache/kafka/commit/ef0f2d96f93c502cfc33062426721bf8e2807d45 from https://github.com/apache/kafka/pull/8181 into the `5.5.0-cp2` hotfix branch for https://confluentinc.atlassian.net/browse/ESCALATION-3652 https://confluentinc.atlassian.net/browse/RM-38
> KAFKA-9584: Fix Headers ConcurrentModificationException in Streams (#8181)

- core/src/main/scala/kafka/server/BrokerLifecycleManager.scala
- core/src/main/scala/kafka/server/KafkaServerManager.scala
- core/src/main/scala/kafka/server/metadata/BrokerMetadataListener.scala
- core/src/main/scala/kafka/server/metadata/PartitionMetadataProcessor.scala
- core/src/test/scala/unit/kafka/server/BrokerLifecycleManagerTest.scala
- core/src/test/scala/unit/kafka/server/metadata/BrokerMetadataListenerTest.scala
- core/src/test/scala/unit/kafka/server/metadata/PartitionMetadataProcessorTest.scala
- metadata/src/main/java/org/apache/kafka/controller/MetaLogManager.java
This patch does the following:
1) Events are handled in order. The previous logic attempted to route the out-of-band registration/fencing messages to the front of the queue, but it seems simpler to let them be handled in order. I am not sure it is worthwhile optimizing for the case when there is a backlog of events to be processed.
2) Event failures are propagated. Previously we incremented an error counter, but an event failure leaves the broker state machine in an indeterminate state and it seems dangerous to try and continue. 
3) Simplify processor API. Rather than overloading `process`, we can use a single method and let the processor `match` on the events it wants to handle.
4) Hook up `MetaLogManager.Listener`. The only real change here is that I preferred to retain the java List …
> Hook up MetaLogManager.Listener to broker and simplify event processing loop

- Jenkinsfile
- gradle.properties
- streams/src/main/java/org/apache/kafka/streams/state/internals/RocksDBGenericOptionsToDbOptionsColumnFamilyOptionsAdapter.java
Cherry-picks https://github.com/confluentinc/kafka/commit/35deb2f7c4a735924b6452c6c60016fbe7dc54e0
to the v6.1.0-beta200916191548 hotfix branch and bumps the hotfix version.
> MINOR: call super.close() when closing RocksDB options (#9498)

- .bumpversion.cfg
- gradle.properties
- streams/quickstart/java/src/main/resources/archetype-resources/pom.xml
- streams/quickstart/pom.xml
- tests/kafkatest/__init__.py
- tests/kafkatest/version.py
This PR has two goals:
* Codify version bumps using the bump2version project - Thats what https://github.com/confluentinc/kafka/commit/a8f047d7b5ab8da735be31025276a1b2edeb4d28 did, initially with the current logical value of 6.0.1-ccs-SNAPSHOT
* Now that 6.0.1 is released, we need to update this project to the "next" version of 6.0.2, which was done by executing `bump2version patch`, which resulted in this commit https://github.com/confluentinc/kafka/commit/2f75e8c7287fe9d9f0b9ba6d416c1671a749c0d1
> MINOR: Codify version bumps and bump 2.6 to 6.0.2

- core/src/main/scala/kafka/log/LogManager.scala
- core/src/main/scala/kafka/server/BrokerLifecycleManager.scala
- core/src/main/scala/kafka/server/Kip500Broker.scala
- core/src/main/scala/kafka/server/LegacyBroker.scala
- core/src/test/scala/unit/kafka/log/LogManagerTest.scala
Moves log recovery out of LogManager constructor and into `startup()` so we can delay recovery until we have caught up on the metadata log.  This is necessary because topic configs are currently required for log recovery.  We may work to remove this dependency on configs later.
ReplicaManager, GroupCoordinator, and TransactionCoordinator al have their `startup()` delayed as well.
Note that this means the broker will transition between states upon startup as follows:
`SHUTDOWN => REGISTERING => FENCED [=> RECOVERING_FROM_UNCLEAN_SHUTDOWN] => RUNNING`
This differs from what is currently stated in KIP-631, which has `RECOVERING_FROM_UNCLEAN_SHUTDOWN` occurring **before** `REGISTERING`
> Recover logs after LogManager construction, upon startup()

- core/src/main/scala/kafka/server/metadata/PartitionMetadataProcessor.scala
Remove all logic associated with broker-side fencing and rely exclusively on one-sided, controller-only fencing.
We currently rely on the initial unfence event from the heartbeat to identify that we have caught up on the metadata log.  We are going to add a new `RECOVERY` broker state in a separate PR now that log recovery happens after catching up, so entering that new state will be the trigger for catching up -- and we'll change the trigger/remove the `FenceBrokerEvent` in `BrokerMetadataListener` in that other PR rather than here.
Note that we never added tests for broker-side fencing because the implementation was unclear/incomplete.  So nothing to remove there -- just implementation.
> One-sided/controller-only fencing

- config/kip500-broker.properties
- config/kip500-combined.properties
- config/kip500-controller.properties
Rename 3 config files more intuitively
Remove metadata.log.dir so it defaults to log.dir
Make sure log.dir never overlaps across the 3 configs
Was able to format log dirs in both `kip-500` branch on on https://github.com/confluentinc/kafka/pull/467 (with fixes applied as mentioned in that PR).  On that PR branch I was able to start with `kip500-controller.properties`; I was unable to successfully start with `kip500-{broker,combined}.properties` but it was not a config issue -- more a PR issue.
> Config file renames/changes

- Jenkinsfile
After the nano version change, function `downStreamValidation ` has an extra parameter config.nanoVersion which need to be set false before any version prior 6.1.0 which is 2.7 in this repo. Otherwise PR build will fail.
Downstream validation is current disabled after 6.1.0 due to some incompatible issue, so we do not need to change it in branches after 2.7.
Tested in PR builder
> Add an extra parameter to fix downstream validation

- metadata/src/main/java/org/apache/kafka/controller/ReplicationControlManager.java
- metadata/src/test/java/org/apache/kafka/controller/ReplicationControlManagerTest.java
- tests/kafkatest/tests/streams/streams_smoke_test.py
Return `TOPIC_ALREADY_EXISTS` if an attempt is made to create a topic with a name that already exists.
Appended a few lines to existing create-topic test to try creating the same topic a second time and confirming that we get the expected error; the test failed prior to the fix and succeeded with it.  Augmented `streams_smoke_test.py` system test to use both Zookeeper and Raft quorums; the Raft quorum cases were flaky before the fix and reliably passed with the fix.
> Avoid duplicate topic creation

- core/src/main/scala/kafka/server/ForwardingManager.scala
- core/src/main/scala/kafka/server/KafkaApis.scala
Adds support for auto topic creation in KIP-500.  This implementation is a quick-and-dirty one that should be jettisoned in favor of https://github.com/apache/kafka/pull/9579 when that is merged to `trunk` and then to `kip-500`.  In the meantime, this PR allows KIP-500 system tests as implemented in https://github.com/confluentinc/kafka/pull/480 to pass.
> Add support for auto topic creation in KIP-500

- core/src/main/scala/kafka/network/RequestChannel.scala
- core/src/main/scala/kafka/server/AuthHelper.scala
- core/src/main/scala/kafka/server/ControllerApis.scala
- core/src/main/scala/kafka/server/KafkaApis.scala
- core/src/main/scala/kafka/server/RequestHandlerHelper.scala
- core/src/main/scala/kafka/server/metadata/BrokerMetadataListener.scala
- core/src/test/scala/unit/kafka/server/ControllerApisTest.scala
- core/src/test/scala/unit/kafka/server/KafkaApisTest.scala
- metadata/src/test/java/org/apache/kafka/controller/ReplicationControlManagerTest.java
When we upstreamed ApisUtils, a lot changed. This is a cherry-pick of that commit (https://github.com/apache/kafka/pull/9715)
> Downstream request helpers from trunk

- core/src/test/java/kafka/testkit/KafkaClusterTestKit.java
The test kit is setting the wrong id for brokers in `MetaProperties`.
> Test kit sets wrong id for broker in MetaProperties

- streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamThread.java
- streams/src/main/java/org/apache/kafka/streams/processor/internals/TaskManager.java
Remove all INFO-level logging from the main StreamThread loop in favor of a summary with a 2min interval
Reviewers: Walker Carlson <carlson@confluent.io>, Guozhang Wang <guozhang@confluent.io>
> MINOR: log 2min processing summary of StreamThread loop (#9941)

- gradle/dependencies.gradle
Httpclient client is used in support-metrics-common/support-metrics-client modules.
will backport the commit to 2.3 branch
> KC-1457 : Update Httpclient to 4.5.13

- docs/js/templateData.js
- gradle.properties
- kafka-merge-pr.py
- streams/quickstart/java/pom.xml
- streams/quickstart/java/src/main/resources/archetype-resources/pom.xml
- streams/quickstart/pom.xml
- tests/kafkatest/__init__.py
- tests/kafkatest/version.py
For now AK's version will be 2.9. CP will be 7.0.
> Bump CCS kafka to AK 2.9 CP 7.0

- gradle/dependencies.gradle
https://confluentinc.atlassian.net/browse/KC-1458: Update jackson databind to "2.9.10.8" to fix https://nvd.nist.gov/vuln/detail/CVE-2020-25649 
Kafka System tests and Platform system tests look good. Test failures are not related to the changes. 
http://confluent-platform-branch-builder-system-test-results.s3-us-west-2.amazonaws.com/2021-02-18--002.1613702401--omkreddy--HEAD--d269c4ca/report.html
> KC-1458: Update JacksonDatabind to "2.9.10.8"

- Jenkinsfile
Re-enable downstream validation on kafka PR. The current build order will be 
```
[["common","master","common-7.0.0"],["common-docker","master","common-docker-7.0.0"],["newwave","master","newwave-7.0.0"],["cc-docker-schema-registry","master","cc-docker-schema-registry-7.0.0"],["hub-client","master","hub-client-7.0.0"],["confluent-rebalancer","master","confluent-rebalancer-7.0.0"],["rest-utils","master","rest-utils-7.0.0"],["schema-registry","master","schema-registry-7.0.0"],["kafka-rest","master","kafka-rest-7.0.0"],["kafka-connect-replicator","master","kafka-connect-replicator-7.0.0"],["ksql","master","ksql-7.0.0"],["ce-kafka-http-server","master","ce-kafka-http-server-7.0.0"],["schema-registry-plugins","master","schema-registry-plugins-7.0.0"],[ …
```
> Enable downstream validation

- checkstyle/suppressions.xml
- connect/runtime/src/main/java/org/apache/kafka/connect/runtime/distributed/DistributedHerder.java
- connect/runtime/src/test/java/org/apache/kafka/connect/runtime/distributed/DistributedHerderTest.java
Preemptive backport of #527 in time for the 6.1.x code freeze.
> KAFKA-12252 and KAFKA-12262: Fix session key rotation when leadership changes

- core/src/main/scala/kafka/log/Log.scala
- core/src/main/scala/kafka/log/ProducerStateManager.scala
- core/src/test/scala/unit/kafka/log/LogTest.scala
- core/src/test/scala/unit/kafka/log/ProducerStateManagerTest.scala
When we truncate the log, the first unstable offset might become valid. On the other hand, the logic in `updateHighWatermarkMetadata` assumes that the first stable offset remains at a valid position. Since this method can be reached through either `updateLogStartOffset` or `updateLogEndOffset` in the truncation paths, we need to ensure that the first unstable offset first reflects the truncated state.
Reviewers: Chia-Ping Tsai <chia7712@gmail.com>, Jun Rao <junrao@gmail.com>
**Conflicts:**
- core/src/main/scala/kafka/log/Log.scala
- core/src/main/scala/kafka/raft/KafkaMetadataLog.scala (not required in 5.5.x)
> KAFKA-12153; Update producer state before updating start/end offsets after truncation (#9838)

- gradle/dependencies.gradle
This will fix the following three CVEs brought by io.netty:netty-codec-http2 and io.netty:netty-codec-http.
https://confluentinc.atlassian.net/browse/SEC-1883
https://confluentinc.atlassian.net/browse/SEC-2016
https://confluentinc.atlassian.net/browse/SEC-2022
> SEC-1883: Upgrade Netty version to 4.1.61.Final

- gradle/dependencies.gradle
This will fix the following three CVEs brought by io.netty:netty-codec-http2 and io.netty:netty-codec-http.
https://confluentinc.atlassian.net/browse/SEC-1883
https://confluentinc.atlassian.net/browse/SEC-2016
https://confluentinc.atlassian.net/browse/SEC-2022
Trying to pick the change on https://github.com/confluentinc/kafka/pull/538 and apply to 2.7
> SEC-1883: Upgrade Netty version to 4.1.62.Final 

- gradle/dependencies.gradle
This will fix the following three CVEs brought by io.netty:netty-codec-http2 and io.netty:netty-codec-http.
https://confluentinc.atlassian.net/browse/SEC-1883
https://confluentinc.atlassian.net/browse/SEC-2016
https://confluentinc.atlassian.net/browse/SEC-2022
Trying to pick the change on #538 and apply to 2.6
> SEC-1883: Upgrade Netty version to 4.1.62.Final

- gradle/dependencies.gradle
This will fix the following three CVEs brought by io.netty:netty-codec-http2 and io.netty:netty-codec-http.
https://confluentinc.atlassian.net/browse/SEC-1883
https://confluentinc.atlassian.net/browse/SEC-2016
https://confluentinc.atlassian.net/browse/SEC-2022
> SEC-2022: Upgrade netty to 4.1.62.Final

- gradle/dependencies.gradle
This brings fix to 2.5 to CCS-Kafka: https://github.com/apache/kafka/pull/10526 
Ref: https://nvd.nist.gov/vuln/detail/CVE-2021-28165
> Upgrade Jetty to 9.4.39.v20210325

- gradle/dependencies.gradle
Guava 20 has CVE:  https://nvd.nist.gov/vuln/detail/CVE-2018-10237
This was introduced through transitive dependency:
+--- org.reflections:reflections:0.9.11
|    +--- com.google.guava:guava:20.0
|    \--- org.javassist:javassist:3.21.0-GA -> 3.25.0-GA
After the change 
|    +--- org.reflections:reflections:0.9.12
|    |    \--- org.javassist:javassist:3.26.0-GA
Our tooling is good. I missed this when reviewing the scan result.
> Upgrade org.reflections:reflections to 0.9.12

- clients/src/main/java/org/apache/kafka/common/network/SaslChannelBuilder.java
- clients/src/main/java/org/apache/kafka/common/security/authenticator/SaslClientAuthenticator.java
- clients/src/main/java/org/apache/kafka/common/security/kerberos/KerberosError.java
- clients/src/main/java/org/apache/kafka/common/security/kerberos/KerberosLogin.java
- core/src/test/scala/integration/kafka/server/GssapiAuthenticationTest.scala
We use a background thread for Kerberos to perform re-login before tickets expire. The thread performs logout() followed by login(), relying on the Java library to clear and then populate credentials in Subject. This leaves a timing window where clients fail to authenticate because credentials are not available. We cannot introduce any form of locking since authentication is performed on the network thread. So this commit treats NO_CRED as a transient failure rather than a fatal authentication exception in clients.
Reviewers: Ron Dagostino <rdagostino@confluent.io>, Manikumar Reddy <manikumar.reddy@gmail.com>
> KAFKA-10727; Handle Kerberos error during re-login as transient failure in clients (#9605)

- connect/runtime/src/main/java/org/apache/kafka/connect/runtime/isolation/DelegatingClassLoader.java
- connect/runtime/src/test/java/org/apache/kafka/connect/runtime/isolation/DelegatingClassLoaderTest.java
We're encountering this on 2.4 / 5.4.x: https://issues.apache.org/jira/browse/KAFKA-9712 after https://github.com/confluentinc/kafka/pull/551/files was merged into 2.4. Cherry-pick applied cleanly.
This commit works around a bug in version v0.9.12 of the upstream `reflections` library by catching and handling the exception thrown.
The reflections issue is tracked by:
https://github.com/ronmamo/reflections/issues/273
New unit tests were introduced to test the behavior.
* KAFKA-9712: Catch and handle exception thrown by reflections scanner
* Update connect/runtime/src/main/java/org/apache/kafka/connect/runtime/isolation/DelegatingClassLoader.java
Co-Authored-By: Konstantine Karantasis <konstantine@confluent.io>
* Move result initialization back to right before it is used
* Use …
> KAFKA-9712: Catch and handle exception thrown by reflections scanner (#8289)

- clients/src/main/java/org/apache/kafka/common/security/kerberos/KerberosLogin.java
- core/src/test/scala/integration/kafka/server/GssapiAuthenticationTest.scala
Conflicts:
- clients/src/main/java/org/apache/kafka/common/security/kerberos/KerberosLogin.java
- core/src/test/scala/integration/kafka/server/GssapiAuthenticationTest.scala
> Sync from apache/kafka 2.6 (6 May 2021)

- core/src/test/scala/integration/kafka/server/GssapiAuthenticationTest.scala
> CONFLUENT: Fix GssapiAuthenticationTest to work with scala 2.11

- gradle/dependencies.gradle
Upgrade org.apache.maven:apache-maven.
> APPSEC-60: Upgrade org.apache.maven:apache-maven

- gradle/dependencies.gradle
avro: "1.9.2" is breaking some of downstream projects. reverting the version to 1.8.1
> CONFLUENT: Revert avro version to 1.8.1

- tests/kafkatest/utils/util.py
A couple of the sanity-check system tests confirm that the version of Kafka on the CLASSPATH during the test is the one that is expected. These tests were failing for the 2.8 release due to the version 6.2.0-ccs not being accounted for correctly in the various regex's. This patch revamps the regex set to be more organized and complete with the various possibilities clearly identified.
> CONFLUENT: Complete version regex check in system tests

- clients/src/main/java/org/apache/kafka/clients/admin/ConfigEntry.java
- clients/src/main/java/org/apache/kafka/common/config/ConfigDef.java
- clients/src/main/java/org/apache/kafka/common/utils/ConfigUtils.java
- clients/src/test/java/org/apache/kafka/common/utils/ConfigUtilsTest.java
- core/src/main/scala/kafka/log/LogConfig.scala
- core/src/main/scala/kafka/log/LogManager.scala
- core/src/main/scala/kafka/network/RequestChannel.scala
- core/src/main/scala/kafka/server/AdminManager.scala
- core/src/main/scala/kafka/server/DynamicBrokerConfig.scala
- core/src/main/scala/kafka/server/KafkaConfig.scala
- core/src/test/scala/unit/kafka/log/LogConfigTest.scala
- gradle/spotbugs-exclude.xml
This is a backport of https://github.com/confluentinc/kafka/pull/584
In addition, for baseline compatibility it partially backports https://github.com/confluentinc/kafka/commit/7e2fb89f33438a5576264d7d6388d4cef4c4a20b to only include
1. clients/src/main/java/org/apache/kafka/common/utils/ConfigUtils.java
2. clients/src/test/java/org/apache/kafka/common/utils/ConfigUtilsTest.java
> Fix a series of secret logging leakage issues

- clients/src/main/java/org/apache/kafka/clients/ClusterConnectionStates.java
- clients/src/main/java/org/apache/kafka/clients/admin/ConfigEntry.java
- clients/src/main/java/org/apache/kafka/common/requests/MetadataRequest.java
- clients/src/main/resources/common/message/MetadataRequest.json
- clients/src/test/java/org/apache/kafka/clients/NetworkClientTest.java
- clients/src/test/java/org/apache/kafka/common/requests/MetadataRequestTest.java
- core/src/main/scala/kafka/server/DynamicBrokerConfig.scala
- core/src/main/scala/kafka/server/KafkaApis.scala
- core/src/test/scala/unit/kafka/server/KafkaApisTest.scala
- streams/src/main/java/org/apache/kafka/streams/kstream/internals/InternalStreamsBuilder.java
- streams/src/main/java/org/apache/kafka/streams/kstream/internals/graph/SourceGraphNode.java
- streams/src/main/java/org/apache/kafka/streams/kstream/internals/graph/StreamSourceNode.java
- streams/src/main/java/org/apache/kafka/streams/kstream/internals/graph/TableSourceNode.java
Sync was stuck on some conflicts which were around comments and indentation:
```
Conflicts: 
clients/src/main/java/org/apache/kafka/clients/admin/ConfigEntry.java
core/src/main/scala/kafka/server/DynamicBrokerConfig.scala
```
> AK to CCS Sync in 2.8

- connect/runtime/src/main/java/org/apache/kafka/connect/runtime/rest/RestClient.java
- connect/runtime/src/main/java/org/apache/kafka/connect/runtime/rest/RestServer.java
- connect/runtime/src/main/java/org/apache/kafka/connect/runtime/rest/util/SSLUtils.java
- connect/runtime/src/test/java/org/apache/kafka/connect/runtime/rest/util/SSLUtilsTest.java
- tools/src/main/java/org/apache/kafka/trogdor/rest/JsonRestServer.java
After a recent upgrade of jetty in https://github.com/confluentinc/kafka/pull/565 we also need the changes in https://github.com/apache/kafka/pull/6668 (https://issues.apache.org/jira/browse/KAFKA-8316) to avoid errors when Connect starts with keystores that contain multiple certificates. 
The change is tested with existing tests and the tests in this PR.
Below follows the original description:
* Remove deprecated class Slf4jRequestLog: use Slf4jRequestLogWriter, CustomRequestLog instread.
1. Remove '@SuppressWarnings("deprecation")' from RestServer#initializeResources, JsonRestServer#start.
2. Remove unused JsonRestServer#httpRequest.
* Fix deprecated class usage: SslContextFactory -> SslContextFactory.[Server, Client]
1. Split SSLUtils#createSslContextFactory into …
> KAFKA-8316: Remove deprecated usage of Slf4jRequestLog, SslContextFactory (backport on 2.2)

- README.md
- build.gradle
- gradle/dependencies.gradle
- gradle/wrapper/gradle-wrapper.properties
- gradlew
This reverts commit 855011f92a20c07ae5ee5a93f29f11a356e30ba3.
Commit 855011f's bump to Gradle 7.1.1 seems to be causing (yet to be
RCA'd) issues with publishing to Artifactory. Confirmed this works in
CI/CD through another branch [1] with this commit reverted.
Conflicts:
Jenkinsfile: Kept CCS-Kafka/master's version
gradle/dependencies.gradle: Downgraded gradle version. Kept
dropwizard version bump
[1] https://jenkins.confluent.io/view/CP%207.0%20Projects/job/confluentinc/job/kafka/job/7.0.x/
> Revert "MINOR: Upgrade Gradle to 7.1.1 and remove JDK 15 build (#10968)"

- clients/src/main/java/org/apache/kafka/common/record/MemoryRecords.java
- core/src/main/scala/kafka/coordinator/transaction/TransactionMetadata.scala
- core/src/main/scala/kafka/coordinator/transaction/TransactionStateManager.scala
- core/src/main/scala/kafka/utils/Pool.scala
- core/src/test/scala/unit/kafka/coordinator/AbstractCoordinatorConcurrencyTest.scala
- core/src/test/scala/unit/kafka/coordinator/transaction/TransactionCoordinatorConcurrencyTest.scala
- core/src/test/scala/unit/kafka/coordinator/transaction/TransactionStateManagerTest.scala
(This is a cherry-pick of apache/kafka#11098.)
When expiring transactionalIds, we group the tombstones together into batches. Currently there is no limit on the size of these batches, which can lead to `MESSAGE_TOO_LARGE` errors when a bunch of transactionalIds need to be expired at the same time. This patch fixes the problem by ensuring that the batch size respects the configured limit. Any transactionalIds which are eligible for expiration and cannot be fit into the batch are postponed until the next periodic check.
Reviewers: David Jacot <djacot@confluent.io>, Guozhang Wang <wangguoz@gmail.com>
> KAFKA-13099; Transactional expiration should account for max batch size

- tests/kafkatest/services/security/security_config.py
After updating the java version in our testing frameworks, test failures had occurred due to more robust ssl checking.  This commit was done to fix later versions in the past, now it needs to be moved back to fix these.
after the backport the failing system tests passed
> backport KAFKA-9319 to 2.1

- build.gradle
- gradle/dependencies.gradle
A new version of JGit that is used by grgit that is used by gradle
causes the following error:
org/eclipse/jgit/storage/file/FileRepositoryBuilder has been compiled
by a more recent version of the Java Runtime (class file version 55.0),
this version of the Java Runtime only recognizes class file versions
up to 52.0
The reason is that version 6.0.0.202111291000-r of JGrit was compiled
with a newer Java version than Java 8, probably Java 11.
Explicitly setting the version of JGrit in gradle to 5.12.0.202106070339-r fixes
the issue.
Reviewers: David Jacot <djacot@confluent.io>, Ismael Juma <ismael@juma.me.uk>, Alexander Stohr, David Arthur <mumrah@gmail.com>
the squashed commit message, so use a …
> HOTFIX: Set version of jgit to avoid unsupported version error (#11554)

- gradle/dependencies.gradle
> MINOR: Upgrade jetty-server to 9.4.44.v20210927 (2.7 branch)

- gradle/dependencies.gradle
> MINOR: Upgrade jetty-server to 9.4.44.v20210927 (2.6 branch)

- gradle/dependencies.gradle
> MINOR: Upgrade jetty-server to 9.4.44.v20210927 (2.5 branch)

- gradle/dependencies.gradle
> MINOR: Upgrade jetty-server to 9.4.44.v20210927 (2.4 branch)

- gradle/dependencies.gradle
> MINOR: Upgrade jetty-server to 9.4.44.v20210927 (2.3 branch)

- clients/src/main/java/org/apache/kafka/clients/CommonClientConfigs.java
- clients/src/main/java/org/apache/kafka/clients/producer/KafkaProducer.java
- clients/src/main/java/org/apache/kafka/clients/producer/ProducerConfig.java
- clients/src/test/java/org/apache/kafka/clients/producer/KafkaProducerTest.java
- connect/runtime/src/main/java/org/apache/kafka/connect/storage/KafkaStatusBackingStore.java
- core/src/main/scala/kafka/tools/ConsoleProducer.scala
- core/src/test/scala/integration/kafka/api/AuthorizerIntegrationTest.scala
- core/src/test/scala/integration/kafka/api/ConsumerWithLegacyMessageFormatIntegrationTest.scala
- core/src/test/scala/integration/kafka/api/EndToEndAuthorizationTest.scala
- core/src/test/scala/integration/kafka/api/MetricsTest.scala
- core/src/test/scala/integration/kafka/api/SaslClientsWithInvalidCredentialsTest.scala
- core/src/test/scala/integration/kafka/server/DynamicBrokerReconfigurationTest.scala
- core/src/test/scala/unit/kafka/server/LogDirFailureTest.scala
- docs/upgrade.html
- log4j-appender/src/test/java/org/apache/kafka/log4jappender/KafkaLog4jAppenderTest.java
Cherry-pick:
- KAFKA-13598: enable idempotence producer by default and validate the configs (#11691)
- MINOR: Fix 3.1 upgrade notes for idempotence bug (#11737)
- MINOR: Clarify producer idempotence default in upgrade docs (#11757)
- KAFKA-13673: disable idempotence when config conflicts (#11788)
One conflict in KafkaProducerTest.java since a new test was added in another commit in AK 3.1 which is not yet in confluentinc/kafka 3.1.
> CONFLUENT: Cherry pick idempotent-by-default fixes from Apache Kafka

- clients/src/main/java/org/apache/kafka/clients/telemetry/TelemetrySubscription.java
- clients/src/main/java/org/apache/kafka/common/metrics/stats/HistogramStat.java
- clients/src/main/java/org/apache/kafka/common/metrics/stats/LinearHistogram.java
- clients/src/test/java/org/apache/kafka/common/metrics/stats/HistogramStatTest.java
- clients/src/test/java/org/apache/kafka/common/metrics/stats/LinearHistogramTest.java
Basic Histogram Implementation.  A few noticeable points are:
1. The bins uses tags, upper_limit and lower_limit
2. The bin sizes if configured by the caller.  We could either use a default bin size in the AbstractClientMetricRecorder, or have it set by the callers in Consumers/Producer/etc.
An example usage of this:
```
public Sensor histogramSensor(MetricName metricName, int maxBin, int numBins) {
// stuff happening here
sensor.add(new LinearHistogram(metricName, maxBin, numBins));
return sensor;
}
```
> basic histogram iml

- clients/src/main/java/org/apache/kafka/clients/telemetry/AbstractClientMetricRecorder.java
- clients/src/main/java/org/apache/kafka/clients/telemetry/DefaultClientInstanceMetricRecorder.java
- clients/src/main/java/org/apache/kafka/clients/telemetry/DefaultConsumerMetricRecorder.java
- clients/src/main/java/org/apache/kafka/clients/telemetry/DefaultProducerTopicMetricRecorder.java
For now: consumer and producer recorder are setting a default histogram max bin and bin size.  We use that as the first pass.  A few follow up questions:
1. Is linear bin a good choice? Maybe we should be using exponential histogram instead as we want more bins at lower latency, and less bins at higher latency. i.e., the lower latency distribution is more important
2. What exactly is the best way to set the bin size? I don't know at this point.
> Histogram Sensor Usage

- streams/src/main/java/org/apache/kafka/streams/processor/internals/CorruptedRecord.java
- streams/src/main/java/org/apache/kafka/streams/processor/internals/RecordQueue.java
- streams/src/main/java/org/apache/kafka/streams/processor/internals/StampedRecord.java
- streams/src/main/java/org/apache/kafka/streams/processor/internals/StreamTask.java
- streams/src/test/java/org/apache/kafka/streams/processor/internals/RecordQueueTest.java
- streams/src/test/java/org/apache/kafka/streams/processor/internals/StreamTaskTest.java
This PR is a port of https://github.com/apache/kafka/pull/11683 requested by @SamehTawfik
> KAFKA-6502: Update consumed offsets on corrupted records. (#11683)

- tests/docker/Dockerfile
- tests/setup.py
Cherry-pick #11883 because automatic merge didn't work on jenkins for some reason.
Ensures we always have the latest published ducktape version (compatible with python 2).
This way whenever we release a new one, we won't have to cherry pick a bunch of commits across a bunch of branches.
> Cherry-pick #11883 - MINOR: unpin ducktape dependency to always use the newest version

- tests/docker/Dockerfile
- tests/docker/ducker-ak
- tests/setup.py
Fixes ducker-ak by explicitly specifying the version of debian that supports python 2.
Also move apt cache clean to the end of the execution.
This PR includes changes from #711 too.
Tested by running a simple test via ducker-ak locally.
> Fix ducker-ak

- core/src/main/scala/kafka/admin/ConsumerGroupCommand.scala
- gradle/dependencies.gradle
Updates the versions of jackson-databind to `2.13.2.2` and the rest of jackson dependencies to `2.13.2` to fix CVE-2020-36518
> KSECURITY-220: Update jackson packages to 2.13.2

- connect/runtime/src/main/java/org/apache/kafka/connect/util/TopicAdmin.java
- connect/runtime/src/test/java/org/apache/kafka/connect/util/TopicAdminTest.java
Merged commits up to https://github.com/apache/kafka/commit/0257f266063c3bffaa690fe3e98a3c876be99002 from https://github.com/apache/kafka/tree/2.6
No conflicts
> 2.6 sync ak to ccs 12 May 2022

- clients/src/main/java/org/apache/kafka/clients/consumer/internals/ConsumerCoordinator.java
- clients/src/test/java/org/apache/kafka/clients/consumer/KafkaConsumerTest.java
- clients/src/test/java/org/apache/kafka/clients/consumer/internals/ConsumerCoordinatorTest.java
cherry-pick KAFKA-13563 compatibility fixes into 3.2
Instead of letting the consumer to always try to discover coordinator in pool with either mode (subscribe / assign), we defer the clearance of discover future upon committing async only. More specifically, under manual assign mode, there are only three places where we need the coordinator:
commitAsync (both by the consumer itself or triggered by caller), this is where we want to fix.
commitSync, which we already try to re-discovery coordinator.
committed (both by the consumer itself based on reset policy, or triggered by caller), which we already try to re-discovery coordinator.
The benefits are that for manual assign mode that does not try to trigger any of the above three, then we never would be discovering coordinator. The original …
> HOTFIX: cherry-pick KAFKA-13563 compatibility fix into 3.2

- clients/src/main/java/org/apache/kafka/clients/consumer/internals/ConsumerCoordinator.java
- clients/src/test/java/org/apache/kafka/clients/consumer/KafkaConsumerTest.java
- clients/src/test/java/org/apache/kafka/clients/consumer/internals/ConsumerCoordinatorTest.java
…2244) (#12259)
This is a cherrypick commit of 3.1. Another way of fixing KAFKA-13563 other than #11631.
Instead of letting the consumer to always try to discover coordinator in pool with either mode (subscribe / assign), we defer the clearance of discover future upon committing async only. More specifically, under manual assign mode, there are only three places where we need the coordinator:
commitAsync (both by the consumer itself or triggered by caller), this is where we want to fix.
commitSync, which we already try to re-discovery coordinator.
committed (both by the consumer itself based on reset policy, or triggered by caller), which we already try to re-discovery coordinator.
The benefits are that for manual assign mode that does not try to trigger any of the above three, then we …
> HOTFIX: cherry-pick KAFKA-13563 compatiblity fix into 3.1

- tests/setup.py
With newer ducktape versions than < 0.9 system tests
may run into authentication issues with the AK system test
infrastructure.
The version will be bumped up once we have infrastructure
in place for newer paramiko versions brought in by ducktape
0.9.
Reviewers: Lucas Bradstreet <lucas@confluent.io>, Matthias J. Sax <mjsax@apache.org>, Kvicii <Karonazaba@gmail.com>
> MINOR: Cherrypick Pin ducktape version to < 0.9 (#12242)

- Vagrantfile
With https://github.com/confluentinc/kafka/commit/6f81bb1814a2f4d7b2dd12667e617d718e6f6f40 merged, we can now use c4.xlarge instances with our system tests, which are much more reliable for spot than m3.xlarge.
A future PR will upgrade our test setup code to use a later ubuntu and even newer instances.
> MINOR: default system tests to c4.xlarge

- Vagrantfile
With 6f81bb1 merged, we can now use c4.xlarge instances with our system tests, which are much more reliable for spot than m3.xlarge.
> MINOR: default system tests to c4.xlarge (#746)

- streams/src/main/java/org/apache/kafka/streams/kstream/internals/foreignkeyjoin/SubscriptionJoinForeignProcessorSupplier.java
This commit changes the version check from` !=` to `>` as the `process` method
works correctly on both version 1 and 2. `!=` incorrectly throws on v1
records.
I don't think that we need additional tests for this change:
1. We already test that the v0 record get `primaryPartition` is equal to `null` in [an existing unit test](https://github.com/apache/kafka/blob/edad31811c49856cc1b8e76de6e3f3a6c02802cd/streams/src/test/java/org/apache/kafka/streams/kstream/internals/foreignkeyjoin/SubscriptionWrapperSerdeTest.java#L132-L133).
2. If `primaryPartition` is equal to `null`, then [the RecordCollector will act as if no partition was specified](https://github.com/apache/kafka/blob/edad31811c49856cc1b8e76de6e3f3a6c02802cd/streams/src/main/java/org/apache/kafka/streams/processor/internals/RecordColl …
> KAFKA-13769 fixup

- clients/src/main/java/org/apache/kafka/clients/ClientTelemetryUtils.java
- clients/src/test/java/org/apache/kafka/clients/DeserializeMetricsDataTest.java
Implements a basic method to parse from `ByteBuffer` to `io.opentelemetry.proto.metrics.v1.MetricsData`
> CLIENTS-2403: kip-714 OTLP deserializer

- clients/src/main/java/org/apache/kafka/common/config/ConfigDef.java
- clients/src/main/java/org/apache/kafka/common/metrics/Metrics.java
- core/src/main/scala/kafka/log/LogCleaner.scala
- core/src/main/scala/kafka/security/authorizer/AclAuthorizer.scala
- core/src/main/scala/kafka/server/BrokerToControllerChannelManager.scala
- core/src/main/scala/kafka/utils/Throttler.scala
- core/src/test/scala/integration/kafka/server/DynamicBrokerReconfigurationTest.scala
- core/src/test/scala/kafka/server/BrokerToControllerRequestThreadTest.scala
- core/src/test/scala/unit/kafka/log/LogCleanerTest.scala
- core/src/test/scala/unit/kafka/security/authorizer/AclAuthorizerTest.scala
- core/src/test/scala/unit/kafka/utils/TestUtils.scala
- core/src/test/scala/unit/kafka/utils/ThrottlerTest.scala
- docs/streams/developer-guide/dsl-api.html
- docs/upgrade.html
> $ git merge-base apache-github/3.3 apache-github/trunk
> 23c92ce79366e86ca719e5e51c550c27324acd83
> $ git show 23c92ce79366e86ca719e5e51c550c27324acd83
> commit 23c92ce79366e86ca719e5e51c550c27324acd83
> Author: SC <pch838811@gmail.com>
> Date:   Mon Jul 11 11:36:56 2022 +0900
>
>    MINOR: Use String#format for niceMemoryUnits result (#12389)
>
>    Reviewers: Luke Chen <showuon@gmail.com>, Divij Vaidya <diviv@amazon.com>
> Ccs master merge 3.3 branching point

- build.gradle
- gradle/dependencies.gradle
**Jira:** https://confluentinc.atlassian.net/browse/KSECURITY-483
Migrating log4j12 to reload4j
Migrating slf4j-log4j12 to slf4j-reload4j.jar
> KSECURITY-478: migrating log4j12 to reload4j, slf4j-log4j12 to slf4j-reload4j.jar (3.2)

- streams/src/main/java/org/apache/kafka/streams/kstream/internals/foreignkeyjoin/SubscriptionJoinForeignProcessorSupplier.java
This commit changes the version check from != to > as the process method
works correctly on both version 1 and 2. != incorrectly throws on v1
records.
> KAFKA-13769 Fix version check in SubscriptionJoinForeignProcessorSupplier (#752)

- streams/src/main/java/org/apache/kafka/streams/kstream/internals/foreignkeyjoin/CombinedKey.java
- streams/src/main/java/org/apache/kafka/streams/kstream/internals/foreignkeyjoin/SubscriptionResponseWrapper.java
- streams/src/main/java/org/apache/kafka/streams/kstream/internals/foreignkeyjoin/SubscriptionStoreReceiveProcessorSupplier.java
- streams/src/main/java/org/apache/kafka/streams/kstream/internals/foreignkeyjoin/SubscriptionWrapper.java
- streams/src/test/java/org/apache/kafka/streams/kstream/internals/foreignkeyjoin/ForeignJoinSubscriptionProcessorSupplierTest.java
- streams/src/test/java/org/apache/kafka/streams/kstream/internals/foreignkeyjoin/SubscriptionStoreReceiveProcessorSupplierTest.java
- streams/src/test/java/org/apache/kafka/streams/kstream/internals/foreignkeyjoin/SubscriptionWrapperSerdeTest.java
* KAFKA-13769: Add tests for ForeignJoinSubscriptionProcessorSupplier (#12437)
Reviewers: Adam Bellemare <adam.bellemare@gmail.com>, John Roesler <vvcephei@apache.org>
* KAFKA-13769 Fix version check in SubscriptionStoreReceiveProcessorSupplier
> KAFKA-13769 Fix version check in SubscriptionStoreReceiveProcessorSup… (#784)

- gradle/dependencies.gradle
This is to backport change in https://github.com/confluentinc/ce-kafka/pull/7069
> Upgrade Jetty version to 9.4.48.v20220622

- gradle/dependencies.gradle
https://github.com/confluentinc/ce-kafka/pull/7068
When upgrade Jetty version in Kafka,  ccs-kafka is missing. This is to sync the change from ce-kafka to ccs-kafka.
> Upgrade jetty to 9.4.48.v20220622

- core/src/main/scala/kafka/cluster/Partition.scala
- core/src/main/scala/kafka/server/ReplicaManager.scala
- core/src/test/scala/unit/kafka/server/ReplicaManagerTest.scala
The current preferred read replica selection logic relies on partition.leaderReplicaIdOpt to determine if the selection must be run. The issue is that partition.leaderReplicaIdOpt is defined for both the leader and the followers thus the logic is ran all the time. The impact is not too bad as the leader is selected most of the time when the logic is ran by the follower and the leader is filtered out. However there are cases where the selection on a follower could redirect the consumer to another follower under certain rare conditions. For instance with the RackAwareReplicaSelector , the follower must have stale replica states from a previous leadership and must have other followers in the same rack for instance. Other implementation of the selection logic could be more impacted.
This …
> KAFKA-13778: Fetch from follower should never run the preferred read replica selection (3.1)

- core/src/main/scala/kafka/cluster/Partition.scala
- core/src/main/scala/kafka/server/ReplicaManager.scala
- core/src/test/scala/unit/kafka/server/ReplicaManagerTest.scala
The current preferred read replica selection logic relies on partition.leaderReplicaIdOpt to determine if the selection must be run. The issue is that partition.leaderReplicaIdOpt is defined for both the leader and the followers thus the logic is ran all the time. The impact is not too bad as the leader is selected most of the time when the logic is ran by the follower and the leader is filtered out. However there are cases where the selection on a follower could redirect the consumer to another follower under certain rare conditions. For instance with the RackAwareReplicaSelector , the follower must have stale replica states from a previous leadership and must have other followers in the same rack for instance. Other implementation of the selection logic could be more impacted.
This …
> KAFKA-13778: Fetch from follower should never run the preferred read replica selection (3.2)

- .github/CODEOWNERS
If entries are on two distinct lines, the last ones wins and it is effectively the code owner. If the entries are on the same line, an approval of only one of the entries is required.
> Fix format of CODEOWNERS

- streams/src/main/java/org/apache/kafka/streams/processor/internals/TaskManager.java
- streams/src/test/java/org/apache/kafka/streams/processor/internals/TaskManagerTest.java
Updating the input partitions of tasks also updates the mapping from source nodes to input topics in the processor topology within the task. The mapping is updated with the topics from the topology metadata. The topology metadata does not prefix intermediate internal topics with the application ID. Thus, if a standby task has input partitions from an intermediate internal topic the update of the mapping in the processor topology leads to an invalid topology exception during recycling of a standby task to an active task when the input queues are created. This is because the input topics in the processor topology and the input partitions of the task do not match because the former miss the application ID prefix.
The added verification to only update input partitions of standby tasks if they …
> HOTFIX: Only update input partitions of standby tasks if they really changed

- Jenkinsfile
Confluent is migrating from JFrog to CodeArtifact. The current vault secret has the contents of a `gradle.init` file with credentials for JFrog. CodeArtifact's credentials only last 12 hours, so it needs to be refreshed.
The `withGradleFile` closure wraps the `withVaultFile` closure, but refreshes and substitutes to CodeArtifact token into the file.
Merging this pull request **will not** cause the repo to publish to CodeArtifact. When it is time to migrate (later this week), we will swap out the underlying vault secret.
https://confluentinc.atlassian.net/wiki/spaces/TOOLS/pages/2930704487/Java+Migration+FAQ#Jenkins
I tested this new closure in Jenkins with a custom job.
> DP-9030: Use the new withGradleFile closure

- build.gradle
###About
Added support for skipping upload task for older gradle versions.
###Testing
`./gradlewAll clean :raft:uploadArchives`
> added support for skipping upload task for older gradle versions

- Jenkinsfile
This is a follow up to the [previous pull request](https://github.com/confluentinc/kafka/pull/842) to convert the Jenkinsfile to using `withGradleFile`.
It looks like when it was cherry-picked to 2.4 and 2.5, it was incorrectly merged and uses `[[ ]]` instead of `[ ]`.
Once this is merged, it only needs to be cherry-picked to 2.5. The rest of the release branches are correct.
I tested this using a replay on 2.4 in Jenkins. …
> DP-9030: Fix a typo in withGradleFile causing failed builds

- core/src/main/scala/kafka/admin/TopicCommand.scala
- core/src/main/scala/kafka/common/AddPartitionNotAllowedDueToTopicIDMismatchException.scala
- core/src/main/scala/kafka/zk/KafkaZkClient.scala
- core/src/main/scala/kafka/zk/ZkData.scala
- core/src/test/scala/unit/kafka/admin/TopicCommandTest.scala
This PR is related to the following JIRA tickets:-
https://confluentinc.atlassian.net/browse/KENGINE-283
https://confluentinc.atlassian.net/browse/SUP-61
Issue Statement:-
Topic ID mismatch issues occur when older zk clients are used with newer versions of the controller.
When the client is using ce-kafka/Confluent Platform versions 5.4.x, 5.5.x, 6.0.x, 6.1.x with Controller of version 6.2.x with IBP 2.8+ (when usesLegacyTopicId = false and usesModernTopicId = true) the topic_id will be written into the TopicZnode. This happens due to the absence of a topicID when the topic was created. The decode in these older versions that is called after the alterTopic method is invoked isn’t equipped to read topicID(topic_id) and hence overwrites the entire TopicZnode with an empty topicID field. …
> KENGINE-283 Topic ID Mismatch Issue - Exception added to disallow Alter Topic with Zookeeper Flag

- core/src/main/scala/kafka/admin/TopicCommand.scala
- core/src/main/scala/kafka/common/AddPartitionNotAllowedDueToTopicIDMismatchException.scala
- core/src/main/scala/kafka/zk/KafkaZkClient.scala
- core/src/main/scala/kafka/zk/ZkData.scala
- core/src/test/scala/unit/kafka/admin/TopicCommandWithZKClientTest.scala
This PR is related to the following JIRA tickets:-
https://confluentinc.atlassian.net/browse/KENGINE-283
https://confluentinc.atlassian.net/browse/SUP-61
Issue Statement:-
Topic ID mismatch issues occur when older zk clients are used with newer versions of the controller.
When the client is using ce-kafka/Confluent Platform versions 5.4.x, 5.5.x, 6.0.x, 6.1.x with Controller of version 6.2.x with IBP 2.8+ (when usesLegacyTopicId = false and usesModernTopicId = true) the topic_id will be written into the TopicZnode. This happens due to the absence of a topicID when the topic was created. The decode in these older versions that is called after the alterTopic method is invoked isn’t equipped to read topicID(topic_id) and hence overwrites the entire TopicZnode with an empty topicID field. …
> KENGINE-283 Topic ID Mismatch Issue - Exception added to disallow Alter Topic with Topic ID present

- build.gradle
This is a follow-up to https://github.com/confluentinc/kafka/pull/853 that fixes the new filter in order to not publish artifacts for streams upgrade tests.
> CONFLUENT: Fix filter for not publishing streams upgrade test artifacts

- build.gradle
Build failing with this error: 
```
10:41:26  Caused by: groovy.lang.MissingPropertyException: Could not set unknown property 'showingAllVariants' for task ':clients:allDepInsight' of type org.gradle.api.tasks.diagnostics.DependencyInsightReportTask.
```
after cherry-picking this commit: https://github.com/confluentinc/kafka/commit/3fb96a6eafd1bac71f88011c2cff30179b2d7660
Remove `showingAllVariants` to revert line to before. 
Another error pops up: 
```
11:28:28  Caused by: org.gradle.internal.metaobject.AbstractDynamicObject$CustomMessageMissingMethodException: Could not find method mavenDeployer() for arguments [build_9ndviwsnxqdm89rxqiasmxx15$_run_closure7$_closure72$_closure96$_closure97$_closure99@38bab292] on extension 'signing' of type org.gradle.plugins.signing.SigningExtension. …
```
> revert: CONFLUENT: Skip publishing for kafka-streams-upgrade-system-tests & CONFLUENT: Fix filter for not publishing streams upgrade test artifacts

- gradle.properties
- streams/quickstart/java/pom.xml
- streams/quickstart/java/src/main/resources/archetype-resources/pom.xml
- streams/quickstart/pom.xml
- tests/kafkatest/__init__.py
- tests/kafkatest/version.py
When [AK version bump to 3.5](https://github.com/confluentinc/kafka/commit/c1a54671e8fc6c7daec5f5ec3d8c934be96b4989) was merged in, the 3.5 bumps were merged in correctly, but 7.5.0 CCS version bump was not applied. This commit applies 7.5.0 version bump for ccs kafka according to [changes used in previous CCS version bumps](https://github.com/confluentinc/kafka/commit/fd583b2af98082f274647c19068a33c1a7fc0b8f).
> MINOR: Fix bump master to 7.5.0-0

- gradle/dependencies.gradle
…022-41915 (#13070)
For KAFKA-14564: upgrade to Netty 4.1.86
Fixes the following:
CVE-2022-41881
CVE-2022-41915
Reviewers: Luke Chen <showuon@gmail.com>
Result of command `./gradlew allDeps | grep "io.netty:"` 
[3.1.txt](https://github.com/confluentinc/kafka/files/10553712/3.1.txt)
> KC-2332: Upgrade netty to 4.1.86 to address CVE-2022-41881, CVE-2022-41915

- gradle/dependencies.gradle
…022-41915 (#13070)
For KAFKA-14564: upgrade to Netty 4.1.86
Fixes the following:
CVE-2022-41881
CVE-2022-41915
Reviewers: Luke Chen <showuon@gmail.com>
Result of command`./gradlew allDeps | grep "io.netty:"`  [3.3.txt](https://github.com/confluentinc/kafka/files/10553174/3.3.txt)
> KC-2332: Upgrade netty to 4.1.86 to address CVE-2022-41915, CVE-2022-41881

- Vagrantfile
This change is identical to https://github.com/confluentinc/ce-kafka/pull/1488. These tags improve cost tracking.
> set Owner and role tags for Vagrant EC2 instances

- Vagrantfile
This changes the tags on the AWS resources to match the standards defined on https://confluentinc.atlassian.net/wiki/spaces/CIRE/pages/2979595324/CIRE+Cloud+Provider+Tagging+Policy+Strategy.
> update tags to match standards

- tests/docker/Dockerfile
- vagrant/base.sh
The streams upgrade test for upgrading from 3.0 to 3.1 fails on this branch (3.1) because the 3.0 jars are not loaded, resulting in ClassNotFound exception when attempting to start the 3.0 application in preparation for upgrading.
AFAICT, this test never passed on this branch for this reason. From commit history, it looks like when the 3.1 release was happening, we forgot to add upgrade tests from 3.0 and they were only added after the fact:
https://github.com/apache/kafka/pull/11716
Later, the 3.0 upgrade test was backported to 3.1 in a separate PR (https://github.com/apache/kafka/pull/12173). Interestingly, the test run linked from that PR actually fails with the same error. This PR patches the backport so the test passes.
> CONFLUENT: fix 3.0 dependency loading for streams upgrade test

- clients/src/main/java/org/apache/kafka/clients/consumer/internals/DefaultBackgroundThread.java
- clients/src/main/java/org/apache/kafka/clients/consumer/internals/PrototypeAsyncConsumer.java
- clients/src/main/java/org/apache/kafka/clients/consumer/internals/events/ApplicationEventProcessor.java
- clients/src/main/java/org/apache/kafka/clients/consumer/internals/events/MetadataUpdateApplicationEvent.java
- clients/src/main/java/org/apache/kafka/clients/consumer/internals/events/UnsubscribeApplicationEvent.java
- clients/src/test/java/org/apache/kafka/clients/consumer/internals/DefaultBackgroundThreadTest.java
- clients/src/test/java/org/apache/kafka/clients/consumer/internals/PrototypeAsyncConsumerTest.java
In this PR: I implemented assign() and assignment(). Ported the original tests from the KafkaConsumerTest.java
Different to the original Implementation:
We will explicitly send a commit event to the background thread to commit the progress
MetadataUpdate will also be send to the background thread
Missing:
Fetcher to clear the buffer
> KAFKA-14950: implement assign() and assignment()

- gradle.properties
- streams/quickstart/java/pom.xml
- streams/quickstart/java/src/main/resources/archetype-resources/pom.xml
- streams/quickstart/pom.xml
- tests/kafkatest/__init__.py
- tests/kafkatest/version.py
When [AK version bump to 3.6](https://github.com/confluentinc/kafka/commit/dc1ede8d89d0964783302e0da9ead7fa1d76fbe4) was merged in, the 3.6 bumps were merged in correctly, but 7.6.0 CCS version bump was not applied. This commit applies 7.6.0 version bump for ccs kafka in master branch
> MINOR: Fix bump master to 7.6.0-0

- gradle.properties
Making jvmargs consistent for both ce-kafka and ccs kafka.
[gradle.properties](https://github.com/confluentinc/ce-kafka/blob/master/gradle.properties) got changed recently in ce-kafka (master branch) , i think by this [PR/commit](https://github.com/confluentinc/ce-kafka/commit/7df211cafec8d9f5b60671afebfa44e83c868e47)
This is causing [packaging master build](https://jenkins.confluent.io/job/confluentinc/job/packaging/job/master/3524/execution/node/482/log/) to fail.
As per @santhoshct, we can keep the jvm args same 100m in both the places and it should not cause any issues.
Raising a PR for kafka-eng team to make some changes (if required), review and merge.
tests are expected for any …
> Fix packaging master build

- tests/setup.py
Using ducktape v0.8.18 and upgrading requests to v2.31.0
> KSECURITY-1789: upgrading requests to v2.31.0

- tests/setup.py
Trying to fix the breaking build due to requests v2.31.0. Using custom ducktape branch `libFix8`
> [Test] Trying to fix the breaking build due to requests v2.31.0

- settings.gradle
Gradle enterprise was causing build to fail and we can't use gradle enterprise at Confluent
```
21:51:42     > The Gradle Enterprise Gradle plugin is conflicting with the Test Retry Gradle plugin and has already added a retry extension to the test task test. Please either remove the Test Retry Gradle plugin from this project or disable the registration of the retry extension in the Gradle Enterprise Gradle plugin by specifying the system property 'gradle.enterprise.testretry.enabled' and setting it to 'false'.
```
> revert gradle enterprise plugin

- LICENSE-binary
- core/src/test/scala/integration/kafka/api/ProducerCompressionTest.scala
- core/src/test/scala/unit/kafka/log/LogCleanerParameterizedIntegrationTest.scala
- gradle/dependencies.gradle
bump snappy-java version to 1.1.10.5, and add more tests to verify the compressed data can be correctly decompressed and read.
For LogCleanerParameterizedIntegrationTest, we increased the message size for snappy decompression since in the new version of snappy, the decompressed size is increasing compared with the previous version. But since the compression algorithm is not kafka's scope, all we need to do is to make sure the compressed data can be successfully decompressed and parsed/read.
> KAFKA-15498: bump snappy-java version to 1.1.10.5 (#14434)

- core/src/test/scala/unit/kafka/network/ConnectionQuotasTest.scala
Flaky test failing with assertion error just outside the defined threshold. So, bumping up the delta for quota by 1.
java.util.concurrent.ExecutionException: org.opentest4j.AssertionFailedError: Expected rate (30 +- 7), but got 37.50937734433608 (600 connections / 15.996 sec) ==> expected: <30.0> but was: <37.50937734433608>
> MINOR: Increase the delta for a flaky quota test

- build.gradle
This is a follow up to https://github.com/confluentinc/kafka/commit/7089ff8afd77282278f1fac619b4d2b010fa0726
that updates Zookeeper. We need to remove the logback dependency as it introduces a CVE regression. 
Logback dependency is removed in all other Confluent maintained Kafka branches.
> CONFLUENT: remove logback dependency from Kafka 3.3

- Jenkinsfile
The jenkinsfile is carried from ak to ck probably due to a broker merge and causing security vulnerability. Overriding this to ck specific jenkins pipeline. 
Security context: https://confluent.slack.com/archives/C60B5SJ1E/p1705431867294249
> fixing jenkinsfile from ak to ck

- clients/src/main/java/org/apache/kafka/clients/consumer/AcknowledgeCommitCallback.java
- clients/src/main/java/org/apache/kafka/clients/consumer/AcknowledgeType.java
- clients/src/main/java/org/apache/kafka/clients/consumer/KafkaShareConsumer.java
- clients/src/main/java/org/apache/kafka/clients/consumer/MockShareConsumer.java
- clients/src/main/java/org/apache/kafka/clients/consumer/ShareConsumer.java
- clients/src/main/java/org/apache/kafka/clients/consumer/internals/ShareConsumerDelegateCreator.java
- clients/src/main/java/org/apache/kafka/clients/consumer/internals/ShareConsumerImpl.java
- clients/src/test/java/org/apache/kafka/clients/consumer/MockShareConsumerTest.java
Defined external interfaces for KafkaShareConsumer following the pattern of KafkaConsumer. Not functional yet but will give other team members an interface to build against.
There are no tests at this point.
> AKCORE-2: Initial interfaces for KafkaShareConsumer

- core/src/main/scala/kafka/server/KafkaApis.scala
- core/src/test/scala/unit/kafka/server/KafkaApisTest.scala
**About**
This PR completed the 2 TODOs mentioned in this [PR](https://github.com/confluentinc/kafka/pull/1003)- 
1. Send the ShareGroupHeartbeatRequest to the group coordinator and receive the response as ShareGroupHeartbeatResponse
2. Uncomment the test which verifies the functionality mentioned in point 1
Reference -[ AKCORE-3](https://confluentinc.atlassian.net/browse/AKCORE-3)
**Build** 
The build is passing as shown in the screenshot
The check styles is passing as shown in the screenshot
**Testing**
The uncommented test passes as shown in the sacreenshot
> AKCORE-3: ShareGroupHeartbeat RPC implementation using group coordinator functionality

- build.gradle
The original set of PRs for this CVE only updated the dependency version, they didn't exclude back level bouncy castles brought in via other dependencies.
This PR excludes those, so the latest bouncycastle is used everywhere
> KSECURITY-2090 3.4 update bcprov-jdk15on for the CVE in this jira

- build.gradle
The original set of PRs for this CVE only updated the dependency version, they didn't exclude back level bouncy castles brought in via other dependencies.
This PR excludes those, so the latest bouncycastle is used everywhere
> KSECURITY-2090 3.5 update bcprov-jdk15on for the CVE in this jira

- core/src/test/scala/unit/kafka/server/ShareGroupHeartbeatRequestTest.scala
**About**
This PR houses a new test which verifies the share group heartbeat responses for the following scenarios - 
1. Heartbeat request to join the group
2. Next heartbeat request to get the assigned topic partitions
3. Next heartbeat request to leave the group
Note - The scenario 1 and 3 mentioned in the PR are working fine but scenario 2 is not working due to a bug in partition assignment code. Hence, the test is disabled for now and can be enabled once the fix is merged.
> AKCORE-3: Added a new unit test for ShareGroupHeartbeat

- clients/src/main/java/org/apache/kafka/clients/consumer/internals/ShareConsumerImpl.java
For a call to `KafkaShareConsumer.poll(Duration timeout)` where the timeout exceeds 5 minutes, the consumer would leave the share group once `max.poll.interval.ms` elapsed. In fact, the timeout is intended to catch situations in which the application thread becomes unresponsive. When the thread is actually inside the Kafka consumer code, it should keep the timer refreshed automatically because there's nothing wrong.
> AKCORE-2: Refresh poll timer periodically (4/N)

- build.gradle
The original set of PRs for this CVE only updated the dependency version, they didn't exclude back level bouncy castles brought in via other dependencies.
This PR excludes those, so the latest bouncycastle is used everywhere
> KSECURITY-2090 master update bcprov-jdk15on for the CVE in this jira

- build.gradle
The original set of PRs for this CVE only updated the dependency version, they didn't exclude back level bouncy castles brought in via other dependencies.
This PR excludes those, so the latest bouncycastle is used everywhere
Also updates the bouncy castle version from 1.75 to 1.77 which is required by cves
> KSECURITY-2090 3.6 update bcprov-jdk15on for the CVE in this jira

- clients/src/test/java/org/apache/kafka/clients/admin/KafkaAdminClientTest.java
**About** 
This PR adds the following 4 unit tests for KafkaAdminClient.listShareGroups - 
- testListShareGroups
- testListShareGroupsMetadataFailure
- testListShareGroupsWithStates
- testListShareGroupsWithStatesOlderBrokerVersion
> AKCORE-10: Adding unit tests for KafkaAdminClient.listShareGroups

- core/src/test/scala/unit/kafka/server/ShareGroupHeartbeatRequestTest.scala
- group-coordinator/src/main/java/org/apache/kafka/coordinator/group/GroupMetadataManager.java
- Fixes the partition assignment and bumping of target assignment epoch.
> AKCORE-1: Fixing partition assignment for share group (5/N)

- clients/src/main/java/org/apache/kafka/clients/admin/Admin.java
- clients/src/main/java/org/apache/kafka/clients/admin/DescribeShareGroupsOptions.java
- clients/src/main/java/org/apache/kafka/clients/admin/DescribeShareGroupsResult.java
- clients/src/main/java/org/apache/kafka/clients/admin/ForwardingAdmin.java
- clients/src/main/java/org/apache/kafka/clients/admin/KafkaAdminClient.java
- clients/src/main/java/org/apache/kafka/clients/admin/ShareGroupDescription.java
- clients/src/main/java/org/apache/kafka/clients/admin/internals/DescribeConsumerGroupsHandler.java
- clients/src/main/java/org/apache/kafka/clients/admin/internals/DescribeGroupsHandlerHelper.java
- clients/src/main/java/org/apache/kafka/clients/admin/internals/DescribeShareGroupsHandler.java
- clients/src/test/java/org/apache/kafka/clients/admin/KafkaAdminClientTest.java
- clients/src/test/java/org/apache/kafka/clients/admin/MockAdminClient.java
- Updated admin client related classes in `clients` module with method impls to support describe share groups.
- Added new share group describe handler class to process server response.
- User must be able to make calls to describe share groups via admin client
- Wrote tests for KafkaAdminClient mirroring ConsumerGroups.
> AKCORE-9: ShareGroupDescribe support for KafkaAdminclient [2/N]

- clients/src/main/java/org/apache/kafka/clients/admin/Admin.java
- clients/src/main/java/org/apache/kafka/clients/admin/DescribeShareGroupsOptions.java
- clients/src/main/java/org/apache/kafka/clients/admin/DescribeShareGroupsResult.java
- clients/src/main/java/org/apache/kafka/clients/admin/ForwardingAdmin.java
- clients/src/main/java/org/apache/kafka/clients/admin/KafkaAdminClient.java
- clients/src/main/java/org/apache/kafka/clients/admin/ShareGroupDescription.java
- clients/src/main/java/org/apache/kafka/clients/admin/internals/DescribeConsumerGroupsHandler.java
- clients/src/main/java/org/apache/kafka/clients/admin/internals/DescribeGroupsHandlerHelper.java
- clients/src/main/java/org/apache/kafka/clients/admin/internals/DescribeShareGroupsHandler.java
- clients/src/main/java/org/apache/kafka/common/protocol/ApiKeys.java
- clients/src/main/java/org/apache/kafka/common/requests/AbstractRequest.java
- clients/src/main/java/org/apache/kafka/common/requests/AbstractResponse.java
- clients/src/main/java/org/apache/kafka/common/requests/ShareGroupDescribeRequest.java
- clients/src/main/java/org/apache/kafka/common/requests/ShareGroupDescribeResponse.java
- clients/src/test/java/org/apache/kafka/clients/admin/KafkaAdminClientTest.java
- clients/src/test/java/org/apache/kafka/clients/admin/MockAdminClient.java
- core/src/main/scala/kafka/coordinator/group/GroupCoordinatorAdapter.scala
- core/src/main/scala/kafka/server/KafkaApis.scala
- core/src/test/scala/unit/kafka/server/KafkaApisTest.scala
- group-coordinator/src/main/java/org/apache/kafka/coordinator/group/GroupCoordinator.java
- group-coordinator/src/main/java/org/apache/kafka/coordinator/group/GroupCoordinatorService.java
- group-coordinator/src/main/java/org/apache/kafka/coordinator/group/GroupCoordinatorShard.java
- group-coordinator/src/main/java/org/apache/kafka/coordinator/group/GroupMetadataManager.java
- group-coordinator/src/main/java/org/apache/kafka/coordinator/group/Utils.java
- group-coordinator/src/main/java/org/apache/kafka/coordinator/group/consumer/ConsumerGroupMember.java
- group-coordinator/src/main/java/org/apache/kafka/coordinator/group/share/ShareGroup.java
- group-coordinator/src/main/java/org/apache/kafka/coordinator/group/share/ShareGroupMember.java
- group-coordinator/src/test/java/org/apache/kafka/coordinator/group/GroupCoordinatorServiceTest.java
- group-coordinator/src/test/java/org/apache/kafka/coordinator/group/GroupMetadataManagerTest.java
- Added support for `shareGroupDescribe` to applicable classes in `group-coordinator`. Created new ShareGroupDescribeRequest & Response for use within GroupCoordinatorAdapter and Service.
- Additional methods have been added to ShareGroup and ShareGroupMember for creating describe share group response object.
- KafkaApis has been updated with new ApiKey for share group describe.
We want to add support for new RPC `ShareGroupDescribe`
- Clean build
- Ran existing tests
- Added new tests wherever applicable.
> AKCORE-9: Add support for ShareGroupDescribeRPC [1/N]

- clients/src/main/java/org/apache/kafka/clients/consumer/internals/RequestManagers.java
- clients/src/main/java/org/apache/kafka/clients/consumer/internals/ShareMembershipManager.java
- clients/src/test/java/org/apache/kafka/clients/consumer/internals/ShareConsumerTestBuilder.java
- clients/src/test/java/org/apache/kafka/clients/consumer/internals/ShareHeartbeatRequestManagerTest.java
- clients/src/test/java/org/apache/kafka/clients/consumer/internals/ShareMembershipManagerTest.java
Change the ShareMembershipManager to implement RequestManager. This means that reconciliation is based on polling, rather than listening to a metadata change.
> AKCORE-11: Refactor ShareMembershipManager into a RequestManager

- clients/src/main/java/org/apache/kafka/clients/admin/internals/DescribeGroupsHandlerHelper.java
- clients/src/main/java/org/apache/kafka/clients/admin/internals/DescribeShareGroupsHandler.java
- tools/src/main/java/org/apache/kafka/tools/ShareGroupsCommand.java
- tools/src/test/java/org/apache/kafka/tools/ShareGroupsCommandTest.java
```
➜  ccs-kafka git:(AKCORE-9-cli) ✗ bin/kafka-share-groups.sh --bootstrap-server localhost:9092 --describe --group group-share-x                                                     [2:05:13]
GROUP_ID             COORDINATOR_NODE     OFFSETS
group-share-x        1                    topic-share-y-0=>878
group-share-x        1                    topic-share-x-0=>665
➜  ccs-kafka git:(AKCORE-9-cli) ✗ bin/kafka-share-groups.sh --bootstrap-server localhost:9092 --describe --group group-share                                                       [2:05:16]
GROUP_ID             COORDINATOR_NODE     OFFSETS
group-share          1
➜  ccs-kafka git:(AKCORE-9-cli) ✗ bin/kafka-share-groups.sh --bootstrap-server localhost:9092 --describe --group group-share-x --offsets …
```
> AKCORE-9: Add support for describe share groups in bin script.

- clients/src/main/java/org/apache/kafka/clients/consumer/internals/ShareMembershipManager.java
- core/src/test/java/kafka/test/api/PlaintextShareConsumerTest.java
Add integration tests which exercise the various situations in which subscribe and unsubscribe can be called. Fixed a bug found by the tests too.
> AKCORE-24: More testing of subscribe and unsubscribe

- clients/src/main/java/org/apache/kafka/common/errors/InvalidRecordStateException.java
- clients/src/main/java/org/apache/kafka/common/protocol/ApiKeys.java
- clients/src/main/java/org/apache/kafka/common/protocol/Errors.java
- clients/src/main/java/org/apache/kafka/common/requests/ShareAcknowledgeRequest.java
- clients/src/main/java/org/apache/kafka/common/requests/ShareAcknowledgeResponse.java
- clients/src/main/java/org/apache/kafka/common/requests/ShareFetchRequest.java
- clients/src/main/java/org/apache/kafka/common/requests/ShareFetchResponse.java
Implementation of ShareFetch and ShareAcknowledge request and response classes to enable them to be referenced in dependent code.
> AKCORE-22: Implementation of ShareFetch/Acknowledge request classes (1/N)

- core/src/main/scala/kafka/server/KafkaConfig.scala
- server/src/main/java/org/apache/kafka/server/config/Defaults.java
Added group.share.record.lock.partition.limit configuration to KafkaConfig.scala
Default Value - 200
Min value - 100
Max value - 10000
Reference - [AKCORE-13](https://confluentinc.atlassian.net/jira/software/c/projects/AKCORE/issues/AKCORE-13)
[AKCORE-13]: https://confluentinc.atlassian.net/browse/AKCORE-13?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> AKCORE-13: Added group.share.record.lock.partition.limit configuration to KafkaConfig.scala

- clients/src/main/java/org/apache/kafka/clients/consumer/internals/ShareSessionHandler.java
- clients/src/test/java/org/apache/kafka/clients/consumer/internals/ShareSessionHandlerTest.java
Temporarily send a complete list of topic-partitions on all ShareFetch requests. The broker is currently sessionless. Also adjust the tests for this.
> AKCORE-22-8: Send topic-partitions on all ShareFetch requests (8/N)

- bin/kafka-console-share-consumer
- bin/windows/kafka-console-share-consumer.bat
- tools/src/main/java/org/apache/kafka/tools/consumer/ConsoleShareConsumer.java
- tools/src/main/java/org/apache/kafka/tools/consumer/ConsoleShareConsumerOptions.java
- tools/src/test/java/org/apache/kafka/tools/consumer/ConsoleShareConsumerOptionsTest.java
- tools/src/test/java/org/apache/kafka/tools/consumer/ConsoleShareConsumerTest.java
Since the console share consumer was originally written, the console consumer has been converted from Scala to Java. This means there is now the opportunity to use common code, such as the default formatter.
> AKCORE-18: Update console share consumer to share code with console consumer

- clients/src/main/java/org/apache/kafka/common/requests/ShareAcknowledgeResponse.java
- core/src/main/java/kafka/server/SharePartitionManager.java
- core/src/main/scala/kafka/server/KafkaApis.scala
- core/src/test/scala/unit/kafka/server/KafkaApisTest.scala
This PR includes `handleShareAcknowledgeRequest` in KafkaApis.scala and the unit tests. This RPC is for handling the ShareAknowledgeRequest. 
Reference - [AKCORE-26](https://confluentinc.atlassian.net/jira/software/c/projects/AKCORE/issues/AKCORE-26)
[AKCORE-26]: https://confluentinc.atlassian.net/browse/AKCORE-26?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> AKCORE-26-3: added handleShareAcknowledgeRequest RPC handle

- core/src/main/scala/kafka/server/KafkaApis.scala
- core/src/test/scala/unit/kafka/server/KafkaApisTest.scala
AKCORE-12: Added check for group.share.enable config for ShareAcknowledge RPC
> AKCORE-12: Support for group.share.enable broker config in ShareAcknowledge RPC

- clients/src/main/java/org/apache/kafka/clients/consumer/ConsumerRecord.java
- clients/src/test/java/org/apache/kafka/clients/consumer/ConsumerRecordTest.java
- tools/src/main/java/org/apache/kafka/tools/consumer/ConsoleShareConsumerOptions.java
- tools/src/main/java/org/apache/kafka/tools/consumer/DefaultMessageFormatter.java
- tools/src/test/java/org/apache/kafka/tools/consumer/DefaultMessageFormatterTest.java
Add optional delivery count to ConsumerRecord so share group deliveries can reveal the delivery count.
> AKCORE-45: Add delivery count to ConsumerRecord

- clients/src/main/java/org/apache/kafka/common/errors/InvalidShareSessionEpochException.java
- clients/src/main/java/org/apache/kafka/common/errors/ShareSessionIdNotFoundException.java
- clients/src/main/java/org/apache/kafka/common/errors/ShareSessionNotFoundException.java
- clients/src/main/java/org/apache/kafka/common/protocol/Errors.java
- clients/src/main/java/org/apache/kafka/common/requests/ShareFetchResponse.java
- core/src/main/java/kafka/server/ShareFetchContext.java
- core/src/main/java/kafka/server/SharePartition.java
- core/src/main/java/kafka/server/SharePartitionManager.java
- core/src/main/scala/kafka/server/BrokerServer.scala
- core/src/main/scala/kafka/server/KafkaApis.scala
- core/src/test/java/kafka/server/SharePartitionManagerTest.java
- core/src/test/scala/unit/kafka/server/KafkaApisTest.scala
**About**
This PR houses the code for share sessions on broker side. The eviction strategy for share sessions is as defined in [KIP-932](https://cwiki.apache.org/confluence/display/KAFKA/KIP-932%3A+Queues+for+Kafka#KIP932:QueuesforKafka-Batching) This PR has an assumption that we are only dealing with topic IDs and not topic names (Reference - Version 13 introduces topic IDs, earlier topic names were used)
**Testing**
Unit tests have been added in `SharePartitionManagerTest.java`
**What's Left**
1. The share sessions functionalities coded in this PR supports all the required operations for a share fetch request. However,  we will need some new functionalities + refractor to accommodate ShareAcknowledge requests
2. The unit tests are not enough in this PR. I'll add more tests in the …
> AKCORE-41: Implemented share sessions on broker (1/N)

- gradle/dependencies.gradle
> KSECURITY-2349 Fix CVE-2024-22201 for jetty

- clients/src/main/java/org/apache/kafka/clients/consumer/KafkaShareConsumer.java
- clients/src/main/java/org/apache/kafka/clients/consumer/internals/ShareConsumerImpl.java
- clients/src/main/java/org/apache/kafka/clients/consumer/internals/ShareFetch.java
- clients/src/main/java/org/apache/kafka/clients/consumer/internals/ShareFetchBuffer.java
- clients/src/main/java/org/apache/kafka/clients/consumer/internals/ShareFetchCollector.java
- clients/src/main/java/org/apache/kafka/clients/consumer/internals/ShareFetchRequestManager.java
- clients/src/test/java/org/apache/kafka/clients/consumer/internals/ShareConsumerImplTest.java
- clients/src/test/java/org/apache/kafka/clients/consumer/internals/ShareFetchBufferTest.java
- clients/src/test/java/org/apache/kafka/clients/consumer/internals/ShareFetchCollectorTest.java
- clients/src/test/java/org/apache/kafka/clients/consumer/internals/ShareFetchRequestManagerTest.java
- core/src/test/java/kafka/test/api/PlaintextShareConsumerTest.java
Refactoring the share fetching logic in preparation for supporting acknowledgements. Removed some unnecessary cruft to do with maintaining the position, which doesn't apply for share groups and was only being used to keep the subscription state happy.
> AKCORE-38-2: Refactor share fetching

- clients/src/main/java/org/apache/kafka/clients/consumer/internals/ShareCompletedFetch.java
- clients/src/main/java/org/apache/kafka/clients/consumer/internals/ShareFetchCollector.java
Remove temporary code to acquire all records in a batch when no acquired record information is provided by the broker. Now the broker supports the acquired record, the client requires it. This is in accordance with KIP-932.
> AKCORE-23: Require acquired records list from broker

- gradle/dependencies.gradle
Cherry-pick [commit](https://github.com/confluentinc/kafka/commit/0b30dc2e8276bb044ab31cb31e518997071aceee) from trunk to 3.6 
> [3.6] KSECURITY-2349 Update jetty to 9.4.54.v20240208 for CVE-2024-22201 fix (#1064)

- clients/src/main/java/org/apache/kafka/common/requests/ShareFetchRequest.java
- core/src/main/java/kafka/server/SharePartitionManager.java
- core/src/main/scala/kafka/server/KafkaApis.scala
- core/src/test/scala/unit/kafka/server/KafkaApisTest.scala
This PR adds support for PartitionMaxBytes field in the share fetch operation on broker.
**Note** - We should not merge this PR until there is support for this field on the client. Currently it comes as default value 0. Conversation details [here](https://confluent.slack.com/archives/C06E4G1KHDJ/p1710264347976979)
> AKCORE-70: Added support for PartitionMaxBytes in share fetch on broker

- clients/src/main/java/org/apache/kafka/clients/consumer/internals/ShareCompletedFetch.java
- clients/src/main/java/org/apache/kafka/clients/consumer/internals/ShareInFlightBatch.java
- core/src/test/java/kafka/test/api/PlaintextShareConsumerTest.java
- core/src/test/scala/integration/kafka/api/AbstractConsumerTest.scala
- core/src/test/scala/unit/kafka/utils/TestUtils.scala
Enhance the ShareCompletedFetch so that it handles records with gaps and acquired record sets with gaps. This enables the code to handle control records which should be filtered out, and also will work for compacted topics.
Added more integration tests which consume records, including transactional records.
> AKCORE-58: Ensure transactional control records are skipped

- gradle/dependencies.gradle
Cherry-pick [commit](https://github.com/confluentinc/kafka/commit/0b30dc2e8276bb044ab31cb31e518997071aceee) from trunk to 3.4
> [3.4] KSECURITY-2349 Update jetty to 9.4.54.v20240208 for CVE-2024-22201 fix (#1064)

- gradle/dependencies.gradle
Cherry-pick [commit](https://github.com/confluentinc/kafka/commit/0b30dc2e8276bb044ab31cb31e518997071aceee) from trunk to 3.3
> [3.3] KSECURITY-2349 Update jetty to 9.4.54.v20240208 for CVE-2024-22201 fix (#1064)

- core/src/main/java/kafka/server/SharePartitionManager.java
- core/src/test/java/kafka/server/SharePartitionManagerTest.java
This PR aims to fix the bug on broker share sessions that the share session epoch gets updated twice when the share fetch request contains acknowledgements.
We have fixed it by considering the 2 cases - 
1. Acknowledgement as a standalone request - Updates to the share session epoch and share session cache are taken care in `acknowledgeShareSessionCacheUpdate` function
2. Acknowledgement piggybacked on share fetch request - `newContext` function takes care of updating the share session epoch and share session cache
> AKCORE-56: Brokers: Bug fix for epoch update twice when fetch and acknowledge both are present

- gradle/dependencies.gradle
Cherry-pick [commit](https://github.com/confluentinc/kafka/commit/0b30dc2e8276bb044ab31cb31e518997071aceee) from trunk to 3.2
> [3.2] KSECURITY-2349 Update jetty to 9.4.54.v20240208 for CVE-2024-22201 fix (#1064)

- gradle/dependencies.gradle
Cherry-pick [commit](https://github.com/confluentinc/kafka/commit/0b30dc2e8276bb044ab31cb31e518997071aceee) from trunk to 3.1
> [3.1] KSECURITY-2349 Update jetty to 9.4.54.v20240208 for CVE-2024-22201 fix (#1064)

- gradle/dependencies.gradle
Cherry-pick [commit](https://github.com/confluentinc/kafka/commit/0b30dc2e8276bb044ab31cb31e518997071aceee) from trunk to 3.0
> [3.0] KSECURITY-2349 Update jetty to 9.4.54.v20240208 for CVE-2024-22201 fix (#1064)

- gradle/dependencies.gradle
Cherry-pick [commit](https://github.com/confluentinc/kafka/commit/0b30dc2e8276bb044ab31cb31e518997071aceee) from trunk to 2.8
> [2.8] KSECURITY-2349 Update jetty to 9.4.54.v20240208 for CVE-2024-22201 fix (#1064)

- gradle/dependencies.gradle
Cherry-pick [commit](https://github.com/confluentinc/kafka/commit/0b30dc2e8276bb044ab31cb31e518997071aceee) from trunk to 2.7
> [2.7] KSECURITY-2349 Update jetty to 9.4.54.v20240208 for CVE-2024-22201 fix (#1064)

- clients/src/main/java/org/apache/kafka/clients/consumer/internals/Acknowledgements.java
- clients/src/main/java/org/apache/kafka/clients/consumer/internals/ShareCompletedFetch.java
- clients/src/main/java/org/apache/kafka/clients/consumer/internals/ShareInFlightBatch.java
- clients/src/main/java/org/apache/kafka/clients/consumer/internals/ShareSessionHandler.java
- clients/src/main/java/org/apache/kafka/common/requests/ShareFetchRequest.java
- clients/src/test/java/org/apache/kafka/clients/consumer/internals/AcknowledgementsTest.java
- clients/src/test/java/org/apache/kafka/clients/consumer/internals/ShareCompletedFetchTest.java
- core/src/test/java/kafka/test/api/PlaintextShareConsumerTest.java
- core/src/test/scala/integration/kafka/api/AbstractConsumerTest.scala
- core/src/test/scala/integration/kafka/api/AbstractShareConsumerTest.scala
There was a problem with the Acknowledgements code for anything other than very simple batches. Added a comprehensive unit test for all the variations of records and gaps, and then updated the code to pass. Added gap support for sending in piggybacked acknowledgements and reworked an integration test that exercises this code.
> AKCORE-50: Handle gaps in batches

- core/src/test/scala/unit/kafka/server/ShareGroupHeartbeatRequestTest.scala
This PR adds integration tests for group coordinator features with respect to share groups. 
The following features are tested - 
1. Members joining, leaving and rejoining share groups have partition assignment intact
2. Partition assignment changes when subscribed topic is deleted.
3. Partition assignment when partitions are increased for a subscribed topic in the middle of consumption.
4. Change group coordinator in the middle of consumption
5. Member joining, expiring due to timeout and rejoining share groups - Disabled for now, requires investigation
> AKCORE-63: Integration test for group coordinator functionalities

- clients/src/main/java/org/apache/kafka/clients/consumer/AcknowledgeType.java
- clients/src/main/java/org/apache/kafka/clients/consumer/AcknowledgementCommitCallback.java
- clients/src/main/java/org/apache/kafka/clients/consumer/KafkaShareConsumer.java
- clients/src/main/java/org/apache/kafka/clients/consumer/internals/Acknowledgements.java
- clients/src/main/java/org/apache/kafka/clients/consumer/internals/ShareConsumerImpl.java
- clients/src/main/java/org/apache/kafka/clients/consumer/internals/ShareFetch.java
- clients/src/main/java/org/apache/kafka/clients/consumer/internals/ShareFetchRequestManager.java
- clients/src/main/java/org/apache/kafka/clients/consumer/internals/ShareInFlightBatch.java
- clients/src/main/java/org/apache/kafka/clients/consumer/internals/ShareSessionHandler.java
- clients/src/test/java/org/apache/kafka/clients/consumer/internals/ShareFetchRequestManagerTest.java
- core/src/test/java/kafka/test/api/PlaintextShareConsumerTest.java
- gradle/spotbugs-exclude.xml
Initial code for KafkaShareConsumer.acknowledge. This method is most useful for writing integration tests that exercise the various scenarios for using share groups.
> AKCORE-73: Initial code for KafkaShareConsumer.acknowledge

- core/src/main/java/kafka/server/SharePartition.java
- core/src/test/java/kafka/server/SharePartitionTest.java
Made minor changes to the broker code to tackle log message "rollback in share partition for acknowledgement". Changed the exception because `InvalidRequestException` could encompass a variety of other cases like invalid offsets in request, malformed requests etc.
> AKCORE-59: Debug console message for acknowledgement failure

- clients/src/main/java/org/apache/kafka/clients/consumer/internals/ShareFetchRequestManager.java
- clients/src/main/java/org/apache/kafka/common/requests/ShareFetchRequest.java
- core/src/test/java/kafka/test/api/PlaintextShareConsumerTest.java
Added support for MAX_PARTITION_FETCH_BYTES configuration. Reworked the code to build up the ShareFetch request to remove the restriction about the arrangement of the incoming data. Also ready for piggybacking acknowledgements when no data is required for when that is supported later on.
Added an integration test for this configuration property.
> AKCORE-71: Support for partition max bytes

- clients/src/main/java/org/apache/kafka/common/requests/ShareFetchRequest.java
- clients/src/main/resources/common/message/ShareFetchRequest.json
- clients/src/test/java/org/apache/kafka/common/requests/RequestResponseTest.java
- core/src/main/java/kafka/server/SharePartitionManager.java
- core/src/test/java/kafka/server/SharePartitionManagerTest.java
- core/src/test/scala/unit/kafka/server/KafkaApisTest.scala
Updating ShareFetch request to match KIP by removing CurrentLeaderEpoch.
> AKCORE-80: Remove CurrentLeaderEpoch from ShareFetch

- clients/src/main/java/org/apache/kafka/clients/consumer/internals/RequestManagers.java
- clients/src/main/java/org/apache/kafka/clients/consumer/internals/ShareFetchRequestManager.java
- clients/src/main/java/org/apache/kafka/clients/consumer/internals/ShareHeartbeatRequestManager.java
- clients/src/main/java/org/apache/kafka/clients/consumer/internals/ShareMembershipManager.java
- clients/src/test/java/org/apache/kafka/clients/consumer/internals/ShareConsumerTestBuilder.java
- clients/src/test/java/org/apache/kafka/clients/consumer/internals/ShareFetchRequestManagerTest.java
- clients/src/test/java/org/apache/kafka/clients/consumer/internals/ShareMembershipManagerTest.java
Set the member ID from the group coordinator in the share session handler so that the same UUID is used for group membership and fetching.
> AKCORE-51: Set member ID in share sessions

- core/src/test/scala/unit/kafka/server/ShareGroupHeartbeatRequestTest.scala
Fixing flaky GC integration [test](https://jenkins.confluent.io/job/confluentinc-pr/job/kafka/job/PR-1133/3/testReport/kafka.server/ShareGroupHeartbeatRequestTest/testMemberJoiningAndExpiring__1__Type_Raft_Isolated__MetadataVersion_3_8_IV0__Security_PLAINTEXT/) `ShareGroupHeartbeatRequestTest.testMemberJoiningAndExpiring`. The flakiness was caused due to the variation in time that it was taking to sync the metadata for topic `bar` with GC. If it was able to complete before we ran `TestUtils.waitUntilTrue()` [here](https://github.com/confluentinc/kafka/blob/kip-932/core/src/test/scala/unit/kafka/server/ShareGroupHeartbeatRequestTest.scala#L650), there was no need of an extra member epoch bump before partition reassignment and hence the actual value …
> AKCORE-82: Fix flaky test ShareGroupHeartbeatRequestTest.testMemberJoiningAndExpiring

- clients/src/test/java/org/apache/kafka/common/protocol/ApiKeysTest.java
- core/src/test/scala/unit/kafka/server/RequestQuotaTest.scala
The addition of the KIP-932 share-group state RPCs caused some test failures. These RPCs do not have a throttle time which means they need to be listed in tests that check for this.
> Fix test failures for share group state RPCs

- core/src/main/java/kafka/server/SharePartition.java
- core/src/main/java/kafka/server/SharePartitionManager.java
- core/src/test/java/kafka/server/SharePartitionManagerTest.java
- core/src/test/java/kafka/server/SharePartitionTest.java
Added utility functions to release records acquired by member.
Note - For the complete functionlity to be available on broker side, we need changes in` KafkaApis.scala` which will come in  subsequent PRs
> AKCORE-86: Add functionality to release records acquired by member when share session is closed (1/N)

- checkstyle/suppressions.xml
- group-coordinator/src/main/java/org/apache/kafka/coordinator/group/GroupCoordinatorShard.java
- group-coordinator/src/main/java/org/apache/kafka/coordinator/group/GroupMetadataManager.java
- group-coordinator/src/main/java/org/apache/kafka/coordinator/group/RecordHelpers.java
- group-coordinator/src/main/java/org/apache/kafka/coordinator/group/share/ShareGroupMember.java
- group-coordinator/src/main/resources/common/message/ShareGroupMemberMetadataKey.json
- group-coordinator/src/main/resources/common/message/ShareGroupMemberMetadataValue.json
- group-coordinator/src/test/java/org/apache/kafka/coordinator/group/GroupCoordinatorShardTest.java
- group-coordinator/src/test/java/org/apache/kafka/coordinator/group/GroupMetadataManagerTest.java
- group-coordinator/src/test/java/org/apache/kafka/coordinator/group/GroupMetadataManagerTestContext.java
Corrected unit tests to check additional persisted records and tested manually as well and verified the records on offsets topic:
```
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Reload4jLoggerFactory]
share-T1:xIO7QZkyTn6nKycw2heWIw::ShareGroupMemberMetadataValue(rackId=null, clientId='console-share-consumer', clientHost='/127.0.0.1', subscribedTopicNames=[T1], rebalanceTimeoutMs=300000)
share-T1::ConsumerGroupMetadataValue(epoch=1, type='SHARE')
share-T1:ERf0KxbYSzSZkd3PvC9i0A::ShareGroupMemberMetadataValue(rackId=null, clientId='console-share-consumer', clientHost='/127.0.0.1', subscribedTopicNames=[T1], rebalanceTimeoutMs=300000)
share-T1::ConsumerGroupMetadataValue(epoch=2, type='SHARE') …
```
> AKCORE-90: Persist share group member information

- checkstyle/suppressions.xml
- core/src/main/java/kafka/server/SharePartition.java
- core/src/main/java/kafka/server/SharePartitionManager.java
- core/src/test/java/kafka/server/SharePartitionManagerTest.java
- core/src/test/java/kafka/server/SharePartitionTest.java
- core/src/test/java/kafka/test/api/PlaintextShareConsumerTest.java
- core/src/test/scala/integration/kafka/api/AbstractShareConsumerTest.scala
Implemented the acquisition lock timeout using `SystemTimerReaper`. I have added unit tests and an integration test to confirm the working of acquisition lock.
I am not 100% sure about the way I have set the `ShareGroupRecordLockDurationMs` property for the integration test. Right now, its applied to all the integration tests by using `brokerPropertyOverrides()`. Please comment if it should be applied to all integration test or if there is a better way to applying it only for the new integration test.
> AKCORE-83: Handle lock timeout on messages in share partition (2/N)

- core/src/test/java/kafka/test/api/PlaintextShareConsumerTest.java
Fixed flaky integration test testMultipleConsumersWithDifferentGroupIds. The cause of flakiness was that the test was unable to do the complete fetch of all 'n' records as expected in the test in 1 `poll()` itself.
> AKCORE-96: Fix flaky integration test testMultipleConsumersWithDifferentGroupIds

- group-coordinator/src/main/java/org/apache/kafka/coordinator/group/GroupMetadataManager.java
- group-coordinator/src/test/java/org/apache/kafka/coordinator/group/GroupMetadataManagerTest.java
- group-coordinator/src/test/java/org/apache/kafka/coordinator/group/GroupMetadataManagerTestContext.java
MINOR: Refactor `consumerGroupMetadataRefreshIntervalMs` to `groupMetadataRefreshIntervalMs` to have it common between consumer and share groups
> AKCORE-93: MINOR: Refactor consumerGroupMetadataRefreshIntervalMs to groupMetadataRefreshIntervalMs

- clients/src/main/java/org/apache/kafka/clients/consumer/internals/RequestManagers.java
- clients/src/main/java/org/apache/kafka/clients/consumer/internals/ShareHeartbeatRequestManager.java
- clients/src/main/java/org/apache/kafka/clients/consumer/internals/ShareMembershipManager.java
- clients/src/test/java/org/apache/kafka/clients/consumer/internals/ShareConsumerTestBuilder.java
- clients/src/test/java/org/apache/kafka/clients/consumer/internals/ShareHeartbeatRequestManagerTest.java
- clients/src/test/java/org/apache/kafka/clients/consumer/internals/ShareMembershipManagerTest.java
Since the KafkaShareConsumer was originally created following on from the AsyncKafkaConsumer, there have been considerable improvements as KIP-848 approaches preview status. This PR makes the equivalent changes to the KafkaShareConsumer.
> AKCORE-68: Update share consumer following new consumer

- core/src/main/java/kafka/server/SharePartition.java
- core/src/test/java/kafka/server/SharePartitionTest.java
Include memberId in `InflightState` of Share Partition so that batch and subset are able to utilize it.
Currently, memberId is a property of `InflightBatch` which is incorrect since a batch can be reacquired in subsets by a different member.
Also did a refactor to make SharePartitionTest code cleaner by moving `sharePartition` object creation to a common function
> AKCORE-92: Brokers - Include memberId in InflightState of Share Partition

- clients/src/main/java/org/apache/kafka/clients/consumer/internals/AcknowledgementCommitCallbackHandler.java
- clients/src/main/java/org/apache/kafka/clients/consumer/internals/ShareConsumerImpl.java
- core/src/test/java/kafka/test/api/PlaintextShareConsumerTest.java
*What*
Added a check to prevent re-entry to methods of KafkaShareConsumer from user defined acknowledgement commit callback.
> AKCORE-103: Added check to disallow calls from callback to ShareConsumer

- core/src/main/java/kafka/server/SharePartitionManager.java
Incorrect synchronization caused an NPE in SharePartitionManager.ShareSessionCache.touch. This method doesn't synchronize when accessing the last-used tree.
Here's the offending stack trace:
```
java.lang.NullPointerException: Cannot assign field "color" because "this.root" is null
at java.base/java.util.TreeMap.fixAfterInsertion(TreeMap.java:2614)
at java.base/java.util.TreeMap.addEntry(TreeMap.java:770)
at java.base/java.util.TreeMap.put(TreeMap.java:828)
at java.base/java.util.TreeMap.put(TreeMap.java:534)
at kafka.server.SharePartitionManager$ShareSessionCache.touch(SharePartitionManager.java:1088)
at kafka.server.SharePartitionManager.acknowledgeShareSessionCacheUpdate(SharePartitionManager.java:306)
at kafka.server.KafkaApis.handleShareFetchRequest(KafkaApis.scala:1564)
at …
```
> AKCORE-115: Fix synchronization on share session cache

- clients/src/main/java/org/apache/kafka/clients/consumer/internals/AcknowledgementCommitCallbackHandler.java
- clients/src/main/java/org/apache/kafka/clients/consumer/internals/ShareConsumerImpl.java
- core/src/test/java/kafka/test/api/PlaintextShareConsumerTest.java
In an acknowledgement commit callback, the KafkaShareConsumer.wakeup() method is allowed and should cause the enclosing poll to return immediately with a WakeupException. The code already did that, so added tests to ensure the behaviour is as expected.
Also, altered the exception handling for the callback so that a thrown exception is propagated to the enclosing poll, which matches the offset commit callback in the regular consumer.
The exception thrown when other methods of KafkaShareConsumer are called in the callback has been changed from ConcurrentModificationException to IllegalStateException.
> AKCORE-104: Allow wakeup in acknowledgement commit callback

- clients/src/main/java/org/apache/kafka/clients/consumer/internals/ShareFetchRequestManager.java
- clients/src/main/java/org/apache/kafka/clients/consumer/internals/ShareSessionHandler.java
- clients/src/main/java/org/apache/kafka/common/requests/ShareFetchRequest.java
- clients/src/main/java/org/apache/kafka/common/requests/ShareFetchResponse.java
- clients/src/test/java/org/apache/kafka/clients/consumer/internals/ShareFetchRequestManagerTest.java
- clients/src/test/java/org/apache/kafka/clients/consumer/internals/ShareSessionHandlerTest.java
- core/src/test/java/kafka/test/api/PlaintextShareConsumerTest.java
Implement the proper rules for a share session in the client. This means that the list of topic-partitions contains changes or operations on the topic-partitions in the session only. If two requests are fetching from the same topic-partitions, only the first request will list the topic-partitions, while the second will have an empty list.
> AKCORE-37: Support for share sessions in client

- core/src/main/java/kafka/server/SharePartitionManager.java
- core/src/main/scala/kafka/server/BrokerServer.scala
- core/src/test/java/kafka/server/SharePartitionManagerTest.java
Close `Timer` objects to avoid memory leak for both tests and actual code.
> AKCORE-117: Close Timer objects to avoid thread leak

- checkstyle/suppressions.xml
- core/src/main/java/kafka/server/SharePartition.java
- core/src/main/java/kafka/server/SharePartitionManager.java
- core/src/main/scala/kafka/server/BrokerServer.scala
- core/src/main/scala/kafka/server/KafkaConfig.scala
- core/src/test/java/kafka/server/SharePartitionManagerTest.java
- core/src/test/java/kafka/server/SharePartitionTest.java
- core/src/test/scala/integration/kafka/api/AbstractShareConsumerTest.scala
- core/src/test/scala/unit/kafka/server/KafkaApisTest.scala
- server/src/main/java/org/apache/kafka/server/config/Defaults.java
This PR contains the addition of shareGroupRecordLockPartitionLimit in KafkaConfig.scala. Share Partition now uses this config to put a limit on the number of records that can be there in the cachedState at any time.
Reference : [AKCORE-66](https://confluentinc.atlassian.net/jira/software/c/projects/AKCORE/issues/AKCORE-66?filter=myopenissues&jql=project%20%3D%20%22AKCORE%22%20AND%20assignee%20IN%20%28currentUser%28%29%29%20AND%20statusCategory%20in%20%28%22To%20Do%22%2C%20%22In%20Progress%22%29%20ORDER%20BY%20created%20DESC)
[AKCORE-66]: https://confluentinc.atlassian.net/browse/AKCORE-66?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> AKCORE 66: Ensuring the partition limit of acquired records is not exceeded

- checkstyle/suppressions.xml
- core/src/main/java/kafka/server/SharePartitionManager.java
- core/src/main/scala/kafka/server/BrokerServer.scala
- core/src/main/scala/kafka/server/KafkaConfig.scala
- core/src/test/java/kafka/server/SharePartitionManagerTest.java
- core/src/test/scala/integration/kafka/api/AbstractShareConsumerTest.scala
- core/src/test/scala/unit/kafka/server/KafkaApisTest.scala
- core/src/test/scala/unit/kafka/server/KafkaConfigTest.scala
- server/src/main/java/org/apache/kafka/server/config/Defaults.java
1. Added temporary internal broker config `group.share.persister.class.name` to determine the implemented class name of `Persister.java`
2. Refactored `SharePartitionManagerTest`
3. Fixed flaky test `testAcknowledgeShareSessionCacheUpdate` in `SharePartitionManagerTest`.
> AKCORE-123: Add temporary config for supporting share persister in share partition

- server-common/src/main/java/org/apache/kafka/server/group/share/NoOpShareStatePersister.java
- server-common/src/main/java/org/apache/kafka/server/group/share/PartitionFactory.java
- Added a NoOp impl of the `Persister` interface. The `NoOpShareStatePersister` simply returns a completed future with empty lists for read operations and success error codes for other mutation operations. It logs the NoOp operation as well.
- We want to use this impl to reduce feature dependency at development time and keep this impl as the default later on (if user chooses to not have any persistence but still use share groups).
- Clean build.
> AKCORE-133: Added NoOpShareStatePersister as a noop persister.

- core/src/main/java/kafka/server/SharePartition.java
- core/src/main/java/kafka/server/SharePartitionManager.java
- core/src/test/java/kafka/server/SharePartitionManagerTest.java
This PR contains a minor bug fix
Rference: [AKCORE-129](https://confluentinc.atlassian.net/jira/software/c/projects/AKCORE/boards/2050/backlog?customFilter=4089&selectedIssue=AKCORE-129)
[AKCORE-129]: https://confluentinc.atlassian.net/browse/AKCORE-129?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> AKCORE-129: Permit fetching when some records are AVAILABLE, even when maxInFlightMessage limit is exceeded

- core/src/main/java/kafka/server/SharePartition.java
- core/src/test/java/kafka/server/SharePartitionTest.java
1. Implemented the call from share partition leader to share group persister for writing updated share group state -
a. The functionality uses exponential backoff mechanism for retries.
b. `stateEpoch` is incremented on every attempt to write share group state to persister (on retries as well).
2. Integrated the functionality mentioned in point 1 to `acknowledge()`, `releaseAcquiredRecords()` and `acquisitionLockTimeout()` features - 
a. In case of failure to write share group state to persister, we provide a `log.error` message and rollback any state transistion that happens during `acknowledge()` and `releaseAcquiredRecords()`
1. `exponentialBackoff` object initialization in `SharePartition` currently uses hardcoded configs I found in `CommonClientConfigs`, not sure if we should be …
> Integrate share persister API for write share group state

- core/src/main/java/kafka/server/SharePartition.java
- core/src/test/java/kafka/server/SharePartitionTest.java
This PR contains the logic for handling the cases where delivery count of records exceed max delivery count config when releaseAcquisitionLockOnTimeout is called in share partition. In case the cache needs to be cleared of initial batches because the state is ARCHIVED, that is also handled here.
Reference: [AKCORE-138](https://confluentinc.atlassian.net/jira/software/c/projects/AKCORE/boards/2050/backlog?selectedIssue=AKCORE-138)
[AKCORE-138]: https://confluentinc.atlassian.net/browse/AKCORE-138?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> AKCORE-138: Integrated logic for handling maxDeliveryCount and moving SPSO with releaseAcquisitionLockOnTimeout in Share Partition

- core/src/main/java/kafka/server/SharePartition.java
- core/src/test/java/kafka/server/SharePartitionTest.java
When releaseAcquiredRecords is called in sharePartition, some acquired records are released in the cachedState. If these records have a deliveryCount >= maxDeliveryCount, then these records are moved to ARCHIVED state. If these ARCHIVED records are at the beginning of the cachedState, then the SPSO needs to be updated. Also, if the initial batches in the cachedState are either acknowledged (either ACCEPT or REJECT), then these batches need to be cleared off the cache.
Reference: [AKCORE-142](https://confluentinc.atlassian.net/jira/software/c/projects/AKCORE/boards/2050/backlog?selectedIssue=AKCORE-142)
[AKCORE-142]: https://confluentinc.atlassian.net/browse/AKCORE-142?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> AKCORE-142: Update the cachedState when releaseAcquiredRecords is called in sharePartition

- core/src/test/java/kafka/test/api/PlaintextShareConsumerTest.java
Added a couple of integration tests - 
1. Share consumer subscription followed by topic creation.
2. Share consumer subscription and poll followed by topic deletion for multiple topic subscriptions - Disabled as of now since it has intermittent failures.
> AKCORE-131: Added integration tests for topic creation post subscription

- core/src/main/java/kafka/server/SharePartition.java
- core/src/test/java/kafka/server/SharePartitionTest.java
- core/src/test/scala/unit/kafka/server/KafkaApisTest.scala
Introduces `EMPTY_MEMBER_ID` which is set as the `memberId` of the batch/offsets when records are acknowledged or acquisition lock times out. The corresponding checks are also changed respectively to throw the correct errors.
> MemberId fix for SharePartition during acknowledge, release acquired records and acquisition lock timeout

- clients/src/main/java/org/apache/kafka/clients/consumer/internals/Acknowledgements.java
- clients/src/main/java/org/apache/kafka/clients/consumer/internals/ShareFetchRequestManager.java
- clients/src/main/java/org/apache/kafka/clients/consumer/internals/ShareSessionHandler.java
- clients/src/main/java/org/apache/kafka/common/requests/ShareAcknowledgeRequest.java
- clients/src/main/java/org/apache/kafka/common/requests/ShareFetchRequest.java
- clients/src/test/java/org/apache/kafka/clients/consumer/KafkaShareConsumerTest.java
- clients/src/test/java/org/apache/kafka/clients/consumer/internals/AcknowledgementsTest.java
- clients/src/test/java/org/apache/kafka/clients/consumer/internals/ShareSessionHandlerTest.java
- core/src/test/java/kafka/test/api/PlaintextShareConsumerTest.java
Use the ShareAcknowledge RPC to close the share session. This has recently been added to the broker so the original intent of KIP-932 can now be implemented.
This PR contains significant refactoring of the share session handling and fetching, with additional testing.
> AKCORE-105: Use ShareAcknowledge to close share session

- core/src/test/scala/unit/kafka/server/KafkaApisTest.scala
The tests in KafkaApisTest.scala were not passing share group related configs to the broker. Also, the tests were written for zk based cluster. Required changes have been made in this PR
Reference: [AKCORE-147](https://confluentinc.atlassian.net/jira/software/c/projects/AKCORE/issues/AKCORE-147?jql=project%20%3D%20%22AKCORE%22%20ORDER%20BY%20created%20DESC)
[AKCORE-147]: https://confluentinc.atlassian.net/browse/AKCORE-147?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> AKCORE-147: Changed tests in KafkaApisTest.scala to support share groups related configs in the broker

- service.yml
changes pipeline triggers to only the branches in kafkaMuckrakeVersionMap
> Make pipeline only trigger on branches in the kafkaMuckrakeVersionMap

- core/src/main/java/kafka/server/SharePartition.java
- core/src/main/java/kafka/server/SharePartitionManager.java
- core/src/test/java/kafka/server/SharePartitionManagerTest.java
- core/src/test/java/kafka/server/SharePartitionTest.java
- server-common/src/main/java/org/apache/kafka/server/group/share/NoOpShareStatePersister.java
Share Partition Leaders needs to use NoOpPersister instead of keeping persister object as `null`
> MINOR: Integrated NoOpPersister with share partition leader

- clients/src/main/java/org/apache/kafka/clients/consumer/AcknowledgeType.java
- clients/src/test/java/org/apache/kafka/common/requests/RequestResponseTest.java
- core/src/main/java/kafka/server/SharePartition.java
- core/src/main/scala/kafka/server/KafkaApis.scala
- core/src/test/java/kafka/server/SharePartitionManagerTest.java
- core/src/test/java/kafka/server/SharePartitionTest.java
- core/src/test/scala/unit/kafka/server/KafkaApisTest.scala
Handle changes to accept acknowledgement type as array instead of single value. Also removed gap offsets as they will be part of acknowledgment type now.
> AKCORE-87: Handle array of acknowledgement types

- clients/src/main/java/org/apache/kafka/clients/consumer/internals/ShareHeartbeatRequestManager.java
- clients/src/test/java/org/apache/kafka/clients/consumer/internals/ShareHeartbeatRequestManagerTest.java
There was a code path with an invalid state transition. The code now leaves the group in an orderly fashion if the poll interval elapses.
> AKCORE-128: Fix invalid transition from STABLE to STALE

- clients/src/main/java/org/apache/kafka/clients/consumer/internals/Acknowledgements.java
- clients/src/main/resources/common/message/ShareAcknowledgeRequest.json
- clients/src/main/resources/common/message/ShareFetchRequest.json
- clients/src/test/java/org/apache/kafka/clients/consumer/internals/AcknowledgementsTest.java
Complete the change from a single acknowledge type and a gap array per batch to an array of acknowledge types per batch. This PR does not include the planned optimisations.
> AKCORE-153: Tidy up handling of acknowledge types

- core/src/main/java/kafka/server/SharePartition.java
- core/src/main/java/kafka/server/SharePartitionManager.java
- core/src/test/java/kafka/server/SharePartitionManagerTest.java
- core/src/test/java/kafka/server/SharePartitionTest.java
- core/src/test/scala/unit/kafka/server/KafkaApisTest.scala
Introduces the handling of in-flight records, start offset and end offset in share partition when LSO advances.
In case, there are failures to write the updated states and startOffset to the persister, currently I do not rollback the startOffset and endOffset. I am rolling back the archived state updates though. In case, we decide to rollback the startOffset and endOffset, there can be cases where the consumers could terminate because of an invalid fetch offset.
1. Integration tests for LSO movement.
2. During `acknowledge()`, we need to take care that some records might have been archived due to LSO movement. So, in case we get an acknowledgement of a batch/offset which is earlier than the start offset, we will need to ignore them.
> AKCORE-149: Ensure when the Log Start Offset (LSO) moves underneath acquired records, nothing breaks (1/N)

- checkstyle/import-control-server-common.xml
- server/src/main/java/org/apache/kafka/server/config/Defaults.java
* Added clients and server modules in import control for server-common `org.apache.kafka.server.group.share`.
* Removed import for `org.apache.kafka.server.group.share.DefaultStatePersister` from Defaults.java
> MINOR: Fixed checkstyle issues for PersisterStateManager.

- core/src/main/java/kafka/server/SharePartition.java
- core/src/test/java/kafka/server/SharePartitionManagerTest.java
- core/src/test/java/kafka/server/SharePartitionTest.java
- core/src/test/java/kafka/test/api/PlaintextShareConsumerTest.java
- core/src/test/scala/unit/kafka/server/KafkaApisTest.scala
This PR carries on the work done in PR #1252 where we introduced the handling of in-flight records, start offset and end offset in share partition when LSO advances. In this PR, the following changes have been made - 
1. During `acknowledge()`, we need to take care that some records might have been archived due to LSO movement. So, in case we get an acknowledgement of a batch/offset which is earlier than the start offset, we will need to ignore them. Hence, client won't get any exceptions.
2. Integration tests for LSO movement.
> AKCORE-149: Ensure when the Log Start Offset (LSO) moves underneath acquired records, nothing breaks (2/N)

- core/src/main/java/kafka/server/SharePartition.java
Refactored `releaseAcquisitionLockOnTimeout` in `SharePartition` to make it modular and make a single write state RPC call instead of multiple RPC calls.
> MINOR: Refactor releaseAcquisitionLockOnTimeout in SharePartition

- group-coordinator/src/main/java/org/apache/kafka/coordinator/group/share/ShareGroup.java
- group-coordinator/src/test/java/org/apache/kafka/coordinator/group/GroupMetadataManagerTest.java
- tools/src/main/java/org/apache/kafka/tools/ShareGroupCommandOptions.java
- tools/src/main/java/org/apache/kafka/tools/ShareGroupsCommand.java
Change the protocol type of share groups so that they do not appear to be consumer groups. Also make the usage messages for `kafka-share-groups.sh` match KIP-932 rather than `kafka-consumer-groups.sh`.
> AKCORE_182: Improve command-line tool error handling

- clients/src/main/java/org/apache/kafka/common/requests/WriteShareGroupStateRequest.java
- clients/src/main/java/org/apache/kafka/common/requests/WriteShareGroupStateResponse.java
- core/src/main/scala/kafka/server/KafkaApis.scala
- group-coordinator/src/main/java/org/apache/kafka/coordinator/group/share/ShareCoordinatorService.java
- group-coordinator/src/main/java/org/apache/kafka/coordinator/group/share/ShareCoordinatorShard.java
- server-common/src/main/java/org/apache/kafka/server/group/share/DefaultStatePersister.java
- server-common/src/main/java/org/apache/kafka/server/group/share/GroupTopicPartitionData.java
- server-common/src/main/java/org/apache/kafka/server/group/share/PartitionAllData.java
- server-common/src/main/java/org/apache/kafka/server/group/share/PartitionData.java
- server-common/src/main/java/org/apache/kafka/server/group/share/PartitionErrorData.java
- server-common/src/main/java/org/apache/kafka/server/group/share/PartitionIdLeaderEpochData.java
- server-common/src/main/java/org/apache/kafka/server/group/share/PartitionStateBatchData.java
- server-common/src/main/java/org/apache/kafka/server/group/share/PartitionStateData.java
- server-common/src/main/java/org/apache/kafka/server/group/share/PartitionStateErrorData.java
- server-common/src/main/java/org/apache/kafka/server/group/share/PersisterStateBatch.java
- server-common/src/main/java/org/apache/kafka/server/group/share/PersisterStateManager.java
- server-common/src/main/java/org/apache/kafka/server/group/share/TopicData.java
- server-common/src/main/java/org/apache/kafka/server/group/share/WriteShareGroupStateParameters.java
* Impl for `writeState` in DefaultSharePersister, ShareCoordinatorService and ShareCoordinatorShard
* Setup in `KafkaApis` to intercept the RPC and return the result.
* The call structure from perspective of `SharePartition` is:
```
SharePartition -> persister.writeState(WriteShareGroupStateParameters) -> forEach_key_in_request.PersisterStateManager.{if client.findCoordinator then client.writeRPC} -> kafkaApis.handleShareGroupStateWrite -> ShareCoordinatorService.writeRPC(WriteShareGroupStateRequestData) -> ShareCoordinator.writeRPC(WriteShareGroupStateRequestData) [update soft state and send records to runtime to update internal topic]
```
* Sample logs
```
[2024-06-06 01:10:12,050] INFO Write share group state request received - …
```
> AKCORE-167: Write RPC complete implementation.

- core/src/main/scala/kafka/server/KafkaApis.scala
This PR resolved an issue of wrongly named function in KafkaApis.scala
> AKCORE-168-2: Minor bugfix, renamed function handleReadShareGroupStateRequest to handleReadShareGroupState in KafkaApis.scala

- core/src/main/scala/kafka/server/BrokerServer.scala
- core/src/main/scala/kafka/server/metadata/ShareCoordinatorMetadataCacheHelperImpl.scala
- server-common/src/main/java/org/apache/kafka/server/group/share/PersisterStateManager.java
- server-common/src/main/java/org/apache/kafka/server/group/share/ShareCoordinatorMetadataCacheHelper.java
* Currently find share coordinator operation is accomplished by issuing FC RPC to a random node.
* If the cluster is absolutely fresh, WE NEED the RPC as it will create the internal topic __share_group_state as a side effect.
* However, subsequent RPCs aren't necessary since the required information is present in the metadata cache.
* In this PR we have introduced the changes to facilitate this optimization. 
* The code checks if internal topic is created and if created whether it can locate the share coordinator in the cache. If it can then the node is returned from the cache.
* Otherwise, FC RPC is issued.
Sample logs
```
[2024-06-08 13:46:04,126] INFO __share_group_state internal topic already exists. (org.apache.kafka.server.group.share.PersisterStateManager$WriteStateHandler) …
```
> AKCORE-187: Use metadata cache to speed up FC RPC.

- tools/src/main/java/org/apache/kafka/tools/ShareGroupCommandOptions.java
The command line argument handling was not checking for --help or --version in the usual way. It does now.
> AKCORE-183: kafka-share-groups.sh --version works without bootstrap server

- clients/src/main/java/org/apache/kafka/clients/consumer/internals/AcknowledgementCommitCallbackHandler.java
- clients/src/main/java/org/apache/kafka/clients/consumer/internals/ShareConsumeRequestManager.java
- clients/src/main/java/org/apache/kafka/clients/consumer/internals/ShareConsumerImpl.java
- clients/src/main/java/org/apache/kafka/clients/consumer/internals/ShareFetchBuffer.java
- clients/src/main/java/org/apache/kafka/clients/consumer/internals/events/ApplicationEventProcessor.java
- clients/src/main/java/org/apache/kafka/clients/consumer/internals/events/AsyncShareAcknowledgeEvent.java
- clients/src/main/java/org/apache/kafka/clients/consumer/internals/events/ShareAcknowledgeEvent.java
- clients/src/main/java/org/apache/kafka/clients/consumer/internals/events/ShareFetchEvent.java
- clients/src/main/java/org/apache/kafka/clients/consumer/internals/events/ShareLeaveOnCloseApplicationEvent.java
- clients/src/main/java/org/apache/kafka/clients/consumer/internals/events/SyncShareAcknowledgeEvent.java
- clients/src/test/java/org/apache/kafka/clients/consumer/internals/AcknowledgementCommitCallbackHandlerTest.java
- clients/src/test/java/org/apache/kafka/clients/consumer/internals/ShareConsumeRequestManagerTest.java
- core/src/test/java/kafka/test/api/PlaintextShareConsumerTest.java
Add Acknowledgements maps to the events sent to the background thread to enable any combination of calls to poll, commitAsync and commitSync.
> AKCORE-188: Refactor handling of Acknowledgements object in ShareConsumer

- clients/src/main/java/org/apache/kafka/clients/consumer/internals/ShareHeartbeatRequestManager.java
- core/src/test/java/kafka/test/api/ShareConsumerTest.java
Replace the integration test PlaintextShareConsumerTest with ShareConsumerTest, moving over to the newer KafkaClusterTestKit. This is much neater because it no longer inherits a load of behaviour from days before KRaft.
> AKCORE-164: Adopt KafkaClusterTestKit for integration tests

- group-coordinator/src/main/java/org/apache/kafka/coordinator/group/share/ShareCoordinatorShard.java
Currently, inside the `readState` in `ShareCoordinatorShard`, when no data is found inside the shareStateMap, an error is returned. But the expected behaviour is to send a default response with no data, because the readState would be called whenever a share partition is initialised for the first time, at which point there is no data persisted for this share partition. This PR corrects this behavior
> AKCORE-168-3: Minor bugfix, sending an empty response instead of error in readState when no value is found in shareStateMap

- core/src/main/java/kafka/server/SharePartition.java
- core/src/test/java/kafka/server/SharePartitionTest.java
Bug fix for LSO movement when ack comes for an earlier InFlightBatch. Earlier code wasn't taking into account that the startOffset might be batches behind the inFlightBatch that contains the last offset of the acknowledgement batch.
Added a unit test to verify the logic change
> AKCORE-209: Bug fix for LSO movement when ack comes for an earlier InFlightBatch

- clients/src/main/java/org/apache/kafka/clients/consumer/internals/RequestManagers.java
- clients/src/main/java/org/apache/kafka/clients/consumer/internals/ShareConsumeRequestManager.java
- clients/src/main/java/org/apache/kafka/clients/consumer/internals/ShareConsumerImpl.java
- clients/src/main/java/org/apache/kafka/clients/consumer/internals/ShareFetchBuffer.java
- clients/src/main/java/org/apache/kafka/clients/consumer/internals/events/ApplicationEventProcessor.java
- clients/src/main/java/org/apache/kafka/clients/consumer/internals/events/BackgroundEvent.java
- clients/src/main/java/org/apache/kafka/clients/consumer/internals/events/ShareAcknowledgeAsyncEvent.java
- clients/src/main/java/org/apache/kafka/clients/consumer/internals/events/ShareAcknowledgeSyncEvent.java
- clients/src/main/java/org/apache/kafka/clients/consumer/internals/events/ShareAcknowledgementCommitCallbackEvent.java
- clients/src/main/java/org/apache/kafka/clients/consumer/internals/events/ShareLeaveOnCloseEvent.java
- clients/src/test/java/org/apache/kafka/clients/consumer/internals/ShareConsumeRequestManagerTest.java
- clients/src/test/java/org/apache/kafka/clients/consumer/internals/ShareConsumerImplTest.java
- clients/src/test/java/org/apache/kafka/clients/consumer/internals/ShareConsumerTestBuilder.java
Drive the acknowledgement commit callback using background events. This fits better with the design of the new consumer.
> AKCORE-214: Use background event to drive callback

- core/src/test/java/kafka/test/api/ShareConsumerTest.java
*What*
Move TestUtils to scala and call producer.close() in ShareConsumerTest
> AKCORE-208: Move TestUtils to scala and call producer.close() in ShareConsumerTest

- server-common/src/main/java/org/apache/kafka/server/group/share/PersisterStateManager.java
* Override doWork to poll requests every 10 ms
* Needs more analysis for large scale deployment
> MINOR: Override doWork for fast RPC handling.

- .semaphore/semaphore.yml
fixed public build by skipping validations, release, and downstream triggers
workaround to have it not run on public CI, have the condition on every line, this way each line can fail, and also you can expand each line in semaphore
Reason to do this:  
- we can't skip blocks by using env variables with `run: when:` semaphore does not support that
- if we put it all under one command, it is hard to read and in semaphore the output for the entire block is put under the same expand in our private CI
> skipped build, compile, validations in public CI

- clients/src/main/java/org/apache/kafka/clients/consumer/internals/ShareConsumeRequestManager.java
- clients/src/main/java/org/apache/kafka/clients/consumer/internals/ShareConsumerImpl.java
- clients/src/main/java/org/apache/kafka/clients/consumer/internals/ShareHeartbeatRequestManager.java
- clients/src/test/java/org/apache/kafka/clients/consumer/KafkaShareConsumerTest.java
- clients/src/test/java/org/apache/kafka/clients/consumer/internals/ShareConsumeRequestManagerTest.java
- core/src/test/java/kafka/test/api/ShareConsumerTest.java
The code was queuing up multiple ShareAcknowledge requests for a node, which unfortunately all had the same share session epoch. This is not allowed and made the broker very sad.
> AKCORE-221: Handle queued up ShareAcknowledge requests properly

- checkstyle/import-control.xml
- clients/src/main/java/org/apache/kafka/clients/consumer/internals/CompletedFetch.java
- clients/src/main/java/org/apache/kafka/clients/consumer/internals/ShareCompletedFetch.java
- clients/src/main/java/org/apache/kafka/common/errors/RecordDeserializationException.java
- clients/src/test/java/org/apache/kafka/clients/consumer/internals/CompletedFetchTest.java
- clients/src/test/java/org/apache/kafka/clients/consumer/internals/ShareCompletedFetchTest.java
*What*
Updated client with changes from  ([KAFKA-16507](https://github.com/apache/kafka/pull/15691/)).
> AKCORE-171 : Updated client with changes from KAFKA-16507

- group-coordinator/src/main/java/org/apache/kafka/coordinator/group/GroupMetadataManager.java
- group-coordinator/src/main/java/org/apache/kafka/coordinator/group/TimelineGaugeCounter.java
- group-coordinator/src/main/java/org/apache/kafka/coordinator/group/metrics/GroupCoordinatorMetrics.java
- group-coordinator/src/main/java/org/apache/kafka/coordinator/group/metrics/GroupCoordinatorMetricsShard.java
- group-coordinator/src/main/java/org/apache/kafka/coordinator/group/share/ShareCoordinatorShard.java
- group-coordinator/src/main/java/org/apache/kafka/coordinator/group/share/ShareGroup.java
* Added share group count and associated state metrics to ShareGroup.
* The ShareGroup is initialised in the GroupMetadataManager which gets a reference to GroupCoordinatorMetricsShard from the GroupCoordinatorShard.
* Hence, the share group count metric has been added in that specific metrics file.
* The other metrics related to the __share_group_state partition will be added in the  ShareCoordinatorMetricsShard.
> AKCORE-184: Added shareGroupCount and state metrics. [1/N]

- group-coordinator/src/main/java/org/apache/kafka/coordinator/group/share/ShareCoordinatorService.java
- group-coordinator/src/main/java/org/apache/kafka/coordinator/group/share/ShareCoordinatorShard.java
- server-common/src/main/java/org/apache/kafka/server/group/share/PersisterStateManager.java
* Read and write RPC logs were generating a lot of noise in the logs.
* This PR moves the request and response dumping to debug level instead of info.
> MINOR: Changed log level for RPC logs.

- core/src/main/java/kafka/server/SharePartitionManager.java
- core/src/main/scala/kafka/server/BrokerServer.scala
- group-coordinator/src/main/java/org/apache/kafka/coordinator/group/metrics/GroupCoordinatorRuntimeMetrics.java
- group-coordinator/src/main/java/org/apache/kafka/coordinator/group/share/ShareCoordinatorMetrics.java
- group-coordinator/src/main/java/org/apache/kafka/coordinator/group/share/ShareCoordinatorMetricsShard.java
- group-coordinator/src/main/java/org/apache/kafka/coordinator/group/share/ShareCoordinatorRuntimeMetrics.java
- group-coordinator/src/main/java/org/apache/kafka/coordinator/group/share/ShareCoordinatorService.java
- group-coordinator/src/main/java/org/apache/kafka/coordinator/group/share/ShareCoordinatorShard.java
- group-coordinator/src/test/java/org/apache/kafka/coordinator/group/metrics/GroupCoordinatorRuntimeMetricsTest.java
- group-coordinator/src/test/java/org/apache/kafka/coordinator/group/share/ShareCoordinatorRuntimeMetricsTest.java
- group-coordinator/src/test/java/org/apache/kafka/coordinator/group/share/ShareCoordinatorServiceTest.java
- group-coordinator/src/test/java/org/apache/kafka/coordinator/group/share/ShareCoordinatorShardTest.java
* Added write-total and write-rate metrics to track number of write state RPCs.
* Added write-latency-avg and write-latency-total to track time taken for write state RPC calls.
* Added share state group num-partition, partition-load-time, idle-thread metrics (via ShareCoordinatorRuntimeMetrics).
* Added tests wherever applicable.
> AKCORE-184: Share coordinator and coordinator runtime metrics. [4/N]

- clients/src/main/java/org/apache/kafka/clients/consumer/internals/ShareConsumeRequestManager.java
*What*
Updated retry logic for commitSync.
> AKCORE-229: Updated retry logic for commitSync

- build.gradle
In  apache:16295, we changed the shadow plugin to `io.github.goooler.shadow:8.1.7`. But this is not honouring archiveClassifier added in https://github.com/apache/kafka/blob/trunk/build.gradle#L1569.
This PR is downgrade the shadow plugin 8.1.3 till we fix the issue in upstream.
> CONFLUENT: Downgrade `io.github.goooler.shadow` plugin to 8.1.3

- tools/src/main/java/org/apache/kafka/tools/ShareConsumerPerformance.java
Removed a couple of duplicate output fields from `ShareConsumerPerformance.java` since we do not have any rebalance time accounted as of now as per discussion [here](https://confluentinc.atlassian.net/wiki/spaces/~712020072219e356b44c9baf2bf96249cf8a9b/pages/3483961953/Share+Consumer+Performance+Evaluation?focusedCommentId=3509978176) . The entire time output by the script is the fetch time itself.
> MINOR: Cleanup of ShareConsumerPerformance to remove duplicate fields

- .gitignore
- .semaphore/semaphore.yml
- Makefile
Removed mk-include and make init-ci in this build as it is unecessary
> 3.0 removed mk-include and make init-ci from semaphore

- build.gradle
This is fix to CP build failures
> MINOR: exclude debian control files from rat check

- core/src/test/java/kafka/test/api/ShareConsumerTest.java
This PR contains integration tests for Read and Write share group state RPCs which read and write to the default persister.
Reference: [AKCORE-186](https://confluentinc.atlassian.net/jira/software/c/projects/AKCORE/issues/AKCORE-186?jql=project%20%3D%20%22AKCORE%22%20ORDER%20BY%20created%20DESC)
[AKCORE-186]: https://confluentinc.atlassian.net/browse/AKCORE-186?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> AKCORE-186: Added Integration tests for Read and Write share group state RPCs

- group-coordinator/src/main/java/org/apache/kafka/coordinator/group/share/ShareCoordinatorShard.java
According to the `CoordinatorRuntime` code, the replay method is called eventually, which should be responsible for the updations to the TimelineHashMaps (`shareStateMap` in our case). The replay function correctly updates the `shareStateMap` with the generated records, but an additional update to the `shareStateMap` was being made in the `writeState` function to update the snapshot epoch, causing double updates for a single `WriteShareGroupState` operation. This PR removes this additional update in the `writeState` function and generates the corrected records with the correct snapshot epoch value, which will be put in the `shareStateMap` during replay
> AKCORE-167-2: Minor bugfix, shareStateMap was being updated twice for a single WriteShareGroupState operation

- .gitignore
- .semaphore/semaphore.yml
- Makefile
> 3.8 removed mk-include and make init-ci from semaphore

- .gitignore
- .semaphore/semaphore.yml
- Makefile
> 3.7 removed mk-include and make init-ci from semaphore

- .gitignore
- .semaphore/semaphore.yml
- Makefile
> 3.6 removed mk-include and make init-ci from semaphore

- .gitignore
- .semaphore/semaphore.yml
- Makefile
> 3.5 removed mk-include and make init-ci from semaphore

- .gitignore
- .semaphore/semaphore.yml
- Makefile
Removed mk-include and make [init-ci](https://confluentinc.atlassian.net/browse/INIT-ci) in this build as it is unecessary
> 3.4 removed mk-include and make init-ci from semaphore

- .gitignore
- .semaphore/semaphore.yml
- Makefile
Removed mk-include and make [init-ci](https://confluentinc.atlassian.net/browse/INIT-ci) in this build as it is unecessary
> 3.3 removed mk-include and make init-ci from semaphore

- .gitignore
- .semaphore/semaphore.yml
- Makefile
Removed mk-include and make [init-ci](https://confluentinc.atlassian.net/browse/INIT-ci) in this build as it is unecessary
> 3.2 removed mk-include and make init-ci from semaphore

- .gitignore
- .semaphore/semaphore.yml
- Makefile
Removed mk-include and make [init-ci](https://confluentinc.atlassian.net/browse/INIT-ci) in this build as it is unecessary
> 3.1 removed mk-include and make init-ci from semaphore

- .gitignore
- .semaphore/semaphore.yml
- Makefile
- build.gradle
> 2.8 removed mk-include and make init-ci from semaphore

- .gitignore
- .semaphore/semaphore.yml
- Makefile
- build.gradle
> 2.7 removed mk-include and make init-ci from semaphore

- .gitignore
- .semaphore/semaphore.yml
- Makefile
- build.gradle
> 2.6 removed mk-include and make init-ci from semaphore

- server-common/src/main/java/org/apache/kafka/server/group/share/PersisterStateManager.java
* Fail share state RPCs if find coordinator is needed but the cluster metadata cache has no node info. Because of this we don't have a destination node to send the RPC.
> MINOR: Fail RPC if no nodes in cache.

- core/src/main/java/kafka/server/SharePartition.java
- core/src/test/java/kafka/server/SharePartitionTest.java
While performance testing, I noticed that we were making an extra write state RPC call in the cases where session was getting closed and there was no records to be moved from ACQUIRED to AVAILABLE/ACKNOWLEDGED state. Hence, I have removed the cases when such extra RPC calls can occur.
> MINOR: Write state RPC does not need to be called when the stateBatches are empty

- clients/src/main/resources/common/message/ShareFetchResponse.json
- clients/src/main/resources/common/message/ShareGroupHeartbeatRequest.json
Some of the kip-932 RPC schemas in the kip-932 branch were out of date relative to the KIP. This meant that a client built off the AK trunk definitions would not work with a kip-932 broker. This PR corrects the definitions.
> AKCORE-242: Correct RPC schemas so AK client talks to kip-932 broker

- tools/src/main/java/org/apache/kafka/tools/ShareConsumerPerformance.java
On digging into the reliability issue "The number of records consumed are greater than the number of records produced", I found out that this was happening in the successive runs of produce-consume cycle apart from the first run. It was happening because share session was closing without committing the acknowledgements for the records returned.
> MINOR: Commit the acknowledgements for fetched records in ShareConsumerPerformance
